### ISSUE TITLE
Replace missing variable with custom text

### ISSUE THREAD

**Issue by JaspervRijbroek** [mde/ejs#100]
Hello,

I have a small issue/ question.

I am creating templates for emails using EJS and currently I have a lot of variables in the template but the issue is that at some times not all the variables are provided.

Is there a way to replace the missing variables with custom text?
If so do you have an example for this?

Kind Regards and Thanks in Advance,

Jasper van Rijbroek

**Comment by mde** [comment]
I don't understand what you're asking. The usual way this works is you store you custom text in variables and they get replaced in the template with the actual text. That's the main purpose of a templating system. Can you provide an example?

**Comment by JaspervRijbroek** [comment]
At this moment there are a lot of variables in our templates like this "<%=foo%>" but when this variable is absent I want to automatically replace this with something like this: "{{foo}}" so that the template renders successful.

Is this possible?

Kind Regards and Thanks in Advance.

**Comment by tconroy** [comment]
I believe he's asking if there's a way to set defaults in the template. Something like

`<%= custom_var || 'this is the default if custom_var isn't set!' %>`

I actually came here to ask the same question, so I'm curious if there's a way to set defaults within the template instead of via the object you pass to the template.

**Comment by JaspervRijbroek** [comment]
At this moment we solve everything in the code before the template is rendered. But it is a lot of work unfortunately.

**Comment by RyanZim** [comment]
I don't know of any way to do this currently.
@JaspervRijbroek, How do you feel this should be implemented?

**Comment by JaspervRijbroek** [comment]
@RyanZim I don't know anymore, it has been a while since I worked on this project and for this employer. I think it is best to just close this ticket, don't think they will do anything with it anymore ;)

**Comment by RyanZim** [comment]
OK, thanks.
Closing.
