### ISSUE TITLE
v8js

### ISSUE THREAD

**Issue by jaroslawziolkowski** [mde/ejs#103]
Hello,
how can I use it with v8js in PHP.

I have installed 2.3.3 version by npm on server

```php
$js = <<< EOT
        var template = ejs.render("",{},{});


EOT;

            try{
                $v8js->executeString($js,'ident.js');
            }catch (V8JsException $e){
                var_dump($e);
            }

```

result is 

```
Fatal error: Uncaught exception 'V8JsException' with message 'ident.js:1: ReferenceError: ejs is not defined'
```

**Comment by TimothyGu** [comment]
I'm not sure how V8JS works, but you at least need to `require` ejs somehow. Try `var ejs = require('ejs')` before you use the compile function.

**Comment by jaroslawziolkowski** [comment]
@TimothyGu I see 
```
require is not defined
```
when I use this construction

**Comment by TimothyGu** [comment]
EJS was written for Node.js. You need to get in touch with V8js on how to use CommonJS modules.
