### ISSUE TITLE
More explanation around client-side support?

### ISSUE THREAD

**Issue by spitza** [mde/ejs#106]
Apologies if this is very basic but I'm a little confused with the instructions for client-side support here: https://github.com/mde/ejs#client-side-support

Specifically with the last direction: "Include one of these on your page, and `ejs.render(str)`."

Where and how exactly should we `ejs.render(str)`?

**Comment by mde** [comment]
Heya, Phil. :) Basically, use it wherever you need your HTML generation:

```javascript
<script src="ejs.js"></script>
<script>
  var people = ['geddy', 'neil', 'alex'],
      html = ejs.render('<%= people.join(", "); %>', {people: people});
      // With JQuery
      $('.some-element-class').html(html);
      // Set the entire body
      document.body.innerHTML = html;
</script>
```

**Comment by spitza** [comment]
Thanks Matthew!! In my express app, I'm dynamically setting some html on the page (changing the url source of a video player when the video is done playing, for example) by iterating over an array of urls. I'm doing:

`var localUrls = <%- JSON.stringify(urls) %>;` because I can't use that variable in my client-side javascript unless I JSON.stringify it. Is using ejs.render a better idea?

**Comment by hariawan** [comment]
Hi @mde Is it possible if we rendering using external ejs file?

I saw in http://www.embeddedjs.com/getting_started.html said that we can call external ejs file.
`var html = new EJS({url: 'cleaning.ejs'}).render(data);`

I'm a bit confused, sorry.

**Comment by mde** [comment]
That is not the doc site for this version of EJS. Ours is at: http://ejs.co/

**Comment by hariawan** [comment]
@mde So how actually do we render using external ejs file? Is it possible?

I saw we only can render string, right?
`ejs.render('<$= users.join(" | "); $>', {users: users});`

**Comment by fchengpc** [comment]
@hariawan is this render string thing still hold true? I have an obj array. possible to render that?

**Comment by mde** [comment]
I'm not sure what you're asking. You pass the `render` method a string and a data object.

**Comment by fchengpc** [comment]
Here is my sample code 
  var html = ejs.render(template, {data: data});  << my data is array of objects. But data must be json string right?

**Comment by mde** [comment]
No, that second param is just a generic JavaScript object that can contain any JS data that you want.

**Comment by RyanZim** [comment]
@mde not sure why this is open.
