### ISSUE TITLE
rmWhitespace missing in npm install version

### ISSUE THREAD

**Issue by tomalex0** [mde/ejs#107]
When i compared github source and npm install version i do see  `rmWhitespace `  missing from `_OPTS`
https://github.com/mde/ejs/blob/master/lib/ejs.js#L55.

`version 2.3.3`

Anybody else facing the issue

**Comment by RyanZim** [comment]
`rmWhitespace` does seem to be missing.
Please upgrade to v2.3.4 or higher.

@mde: Is this an issue? v2.3.3 is outdated.

**Comment by RyanZim** [comment]
@tomalex0 `rmWhitespace` was added in v2.3.4, so it is not present in v2.3.3.
