### ISSUE TITLE
How to do Ajax with EJS, and NoSQL DB and Express?  Question

### ISSUE THREAD

**Issue by xtianus79** [mde/ejs#108]
Ok so I have a build with the above listing.  I am using DynamoDB for the data and I am rendering a query into the router so that it will render via EJS on the EJS file. 

The issue is when I do an AJAX call in general it returns the entire page and not the specific data I am looking for.  

Any insight into updating EJS through AJAX?  The method on the EJS site is outdated and doesn't pertain to this node installation.

**Comment by mde** [comment]
Which EJS site are you talking about? The one for this EJS version is http://ejs.co/

**Comment by xtianus79** [comment]
This is for node ejs. There seems to be more than one version. I need to have Ajax update. Would you be able to help.

Sent from my Windows Phone
________________________________

**Comment by RyanZim** [comment]
@xtianus79, there are quite a few versions of ejs (many of them written in node).

This probably should be submited to [stackoverflow.com](https://stackoverflow.com/) as it's more of a question than a bug.
If it turns out to be a bug you can open a new bug here.
