### ISSUE TITLE
Potential XSS issue

### ISSUE THREAD

**Issue by ksloan** [mde/ejs#110]
So according to [this SO question](http://stackoverflow.com/questions/16098397/pass-variables-to-javascript-in-expressjs/16098699#16098699) it seems like the accepted way to pass variables to JavaScript using .ejs is like so:

```html
<script>
  var foo = <%- JSON.stringify(foo) %>;
</script>
```

But I've ran into XSS issues using this method, and wanted to know if there was a better/safer way.

[This example](http://jsfiddle.net/k1x230d8) shows the vulnerability. 

This works since ```JSON.stringify("</script><script>alert('test')</script><script>")``` returns ```"</script><script>alert('test')</script><script>"``` and the ```<%- %>``` operators **do not** escape the result.

It also works for objects: ([example here](jsfiddle.net/n354ofjm)) 
 ```html
<script>
var test = {
    "text": "</script><script>alert('test')</script><script>"
}
</script>
```

I feel like a lot of people may be passing their vars this way...

**Comment by TimothyGu** [comment]
And this is the reason why you shouldn't use `<%-`. According to the [documetation](https://github.com/mde/ejs/blob/master/docs/syntax.md#--unescaped-output):

> However, always **be 100% sure** the rendered local is sanitized, to prevent cross-site scripting (XSS) attacks.
