### ISSUE TITLE
install with bower

### ISSUE THREAD

**Issue by ORESoftware** [mde/ejs#113]
sorry, I am 99% certain I asked this question before, but how can I install this lib with bower? 

```
bower install ejs
```

installs TJ's old version of this

**Comment by ORESoftware** [comment]
also, it seems like there was an AMD version of this lib, but now I can't find it anymore

**Comment by poifox** [comment]
:+1:

**Comment by rogeriopvl** [comment]
@ORESoftware you can always install from URL:

`bower install --save https://github.com/mde/ejs.git`

**Comment by mnaughto** [comment]
It'd definitely be cool if the bower link could be updated and this lib actually had a bower.json file. And was in UMD, if that's possible.

**Comment by RyanZim** [comment]
@mde, what do you think?
I personally don't have experience with bower.

**Comment by RyanZim** [comment]
Discussion about UMD/AMD is going on at #146.

**Comment by RyanZim** [comment]
@ORESoftware @poifox @mnaughto and all others:

Is there still interest for bower support?

If there is no interest, I will close this.

**Comment by RyanZim** [comment]
Closing.
