### ISSUE TITLE
browserify (ejsify)

### ISSUE THREAD

**Issue by builtbylane** [mde/ejs#114]
just wondering if anyone has had any success browserifying this ejs package. I have been working with ejs v1 without issue (https://github.com/builtbylane/ejsify/blob/patch-1/index.js), but am stuck with this version  of ejs.

**Comment by mde** [comment]
All the releases come with Browserified js files, both normal and minified: https://github.com/mde/ejs/releases/latest

**Comment by builtbylane** [comment]
thanks @mde. what I'm trying to do is browserify a bunch of my templates, using ejs as a transform. ejs functions like `include` aren't getting passed through in the transform. does that make sense?

**Comment by mde** [comment]
I maybe totally missing something here, but I don't think either flavor of `include` would be expected to work in browsers, because they access the filesystem.

**Comment by builtbylane** [comment]
I'm running this transform to fix that:  https://github.com/substack/brfs.

**Comment by TimothyGu** [comment]
> I maybe totally missing something here, but I don't think either flavor of `include` would be expected to work in browsers, because they access the filesystem.

Static inclusion *does* work if it was compiled/browserified on the server. I believe @builtbylane is trying to use the `include` function, which does NOT work in the browser because it is dynamic.

IIRC, what brfs does is basically transform a dynamic readFileSync to a static one. If this works, then you could've used the static `include` statement instead anyway.

**Comment by builtbylane** [comment]
thanks for clearing that up @TimothyGu. But shouldn't it be possible to precompile all my javascript templates using browserify? in the previous version of ejs (v1) I was having no trouble doing this.

**Comment by TimothyGu** [comment]
Basically in v1 only the static include is supplied.

**Comment by builtbylane** [comment]
what type of include is supplied in v2?

**Comment by TimothyGu** [comment]
Either v1-style static include or a function-style dynamic one. See https://github.com/mde/ejs/blob/master/docs/syntax.md#including-other-files
