### ISSUE TITLE
Custom functions (clientside)

### ISSUE THREAD

**Issue by glenn9** [mde/ejs#116]
Hi. I've used v1 in Node and trying to use this one on the clientside. Is there any way to add custom functions for all rendering? On Node I used the app.locals object

**Comment by mde** [comment]
app.locals is an Express thing, not an EJS thing. They are wrapping the call to EJS `render`. It would be simple for you to do that if you want something available everywhere you render:

```javascript
var helpers = {
  someHelper: function (stuff) { /* Do some stuff with stuff */ },
  otherHelper: function (stuff) { /* Do something different */ }
};
var renderWrapper = function (str, data) {
  // Object.assign is ES6, could use Underscore `mixin`, JQuery `extend`, etc. to copy props
  var dataWithHelpers = Object.assign({}, helpers, data);
  return ejs.render(str, dataWithHelpers);
}; 
```

**Comment by RyanZim** [comment]
@mde, any reason for this being open?

**Comment by mde** [comment]
:+1:
