### ISSUE TITLE
How to catch syntax error and have human readable error ?

### ISSUE THREAD

**Issue by jmcollin78** [mde/ejs#118]
Hi all,

I wonder how to catch syntax error in template and to have a human readable error (with line and what is wrong).
When I try/catch arround compile I've got only this mysterious error:
<code>
SyntaxError: Unexpected token catch while compiling ejs]
</code>
Is there any syntax verification function or something like that ?
I suppose this is possible because this test page: http://www.embeddedjs.com/ does display syntax error in a friendly manner.

I try compileDebug and debug without success.

Thank's in advance.

**Comment by joaomvfsantos** [comment]
Would really like to know a way to do this too.

**Comment by RyanZim** [comment]
@jmcollin78: http://www.embeddedjs.com/ is the documentation for a different implementation of EJS.
Ours is at http://ejs.co.
#129 or #130 might fix this.

**Comment by RyanZim** [comment]
@jmcollin78, @joaomvfsantos: See https://github.com/mde/ejs/issues/119#issuecomment-218600389.
