### ISSUE TITLE
Crash when tags are not closed

### ISSUE THREAD

**Issue by jadams41** [mde/ejs#121]
I have a node.js application where I accept user created templates (hence they can not be scrutinized for errors) and render them with ejs. I was testing this service myself when I accidentally forgot to close the tags `<div><%= user%></div><i><%= user%><%= user></i>` which about 10 seconds later proceeded to produce:
```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory```
and crash node. I tested again and verified the same result.

Is there any built in protection for malformatted requests that I'm missing, this seems like rather dangerous behavior to have resulting from something as simple as a typo.

**Comment by TimothyGu** [comment]
This indeed sounds dangerous; however your test case works properly in EJS 2.3.4.

```js
> require('.').compile('<div><%= user%></div><i><%= user%><%= user></i><%= user %>')
Error: Could not find matching close tag for "<%=".
    at /home/timothy-gu/ejs/ejs/lib/ejs.js:519:19
    at Array.forEach (native)
    at Object.Template.generateSource (/home/timothy-gu/ejs/ejs/lib/ejs.js:505:15)
    at Object.Template.compile (/home/timothy-gu/ejs/ejs/lib/ejs.js:427:12)
    at Object.compile (/home/timothy-gu/ejs/ejs/lib/ejs.js:288:16)
```

Can you confirm what version of EJS you are using and how to reproduce it?

**Comment by RyanZim** [comment]
@jadams41: we await your reply.

**Comment by RyanZim** [comment]
Closing as unreproducible. If this issue surfaces again, please open a new issue.
