### ISSUE TITLE
Documentation on how to use filename for include is very confusing

### ISSUE THREAD

**Issue by hackhat** [mde/ejs#124]
Hi!

I think the documentation on how to use `include`s in the ejs is very confusing. Even looking at the examples is not really clear how is supposed to work. 

Can you please update the documentation somehow?

Thanks

**Comment by hackhat** [comment]
I've noticed that if I don't include the `filename` the includes doesn't work, but if you put some random string in the `filename` it just works. I don't know how is this supposed to work, but now it just works by putting a random string or even boolean true.

**Comment by hackhat** [comment]
Here https://github.com/mde/ejs/blob/master/test/ejs.js#L674 you are doing `ejs.render('<%- include("fixtures/includes/bom.ejs") %>',
        {}, {filename: path.join(__dirname, 'f.ejs')}),` but notice that there is no file name `f.ejs` in the folder: https://github.com/mde/ejs/tree/master/test

**Comment by Liu-Young** [comment]
@hackhat Para `filename` mean absolute file path of the current file. When you use `include`, include path is relative the filename's path. For example:

 ```html
<!-- this file absolute path /user/home/project/a.ejs -->
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <link rel='stylesheet' href='/stylesheets/style.css'/>
</head>
<body>
<%- include part.ejs %>
<h1><%= title %></h1>
<p>Welcome to <%= title %></p>
</body>
</html>

```
```node
var ejs = require('ejs');
var fs = require('fs');

var filepath = '/user/home/project/a.ejs';
fs.readFile(filepath, function (err, data) {
  if (err) throw err;
  var html = ejs.render(data.toString(), {title: 'A Title'}, { filename: filepath});
  console.log(html);
});
```

**Comment by hackhat** [comment]
So how come putting a random string just works?

**Comment by RyanZim** [comment]
EJS actually only looks at the directory part of the filename (`/user/home/project/`) to find the directory that the includes are relative to and ignores the filename (`a.ejs`).

**Comment by mde** [comment]
Is this an actual issue? Can somebody either add something to the docs, or close this?

**Comment by RyanZim** [comment]
Will be updating the docs @mde.

**Comment by RyanZim** [comment]
Updates are contained in PR #138.
