### ISSUE TITLE
<%= title %> not working in Yeoman Angular-fullstack.

### ISSUE THREAD

**Issue by jay-gandhi** [mde/ejs#126]
Hey, i'm using EJS v2.3.3 to render HTML pages for client side.

```javascript
app.route('/*')
        .get((req, res) => {
          res.render(path.resolve(app.get('appPath') + '/index.html'),
                {title : 'MyTitle'});
        });
```

I've tried
```
<%= title %> 
```
Not Working.
in page, it's just rendering as a text, it shows only <%= title %>, not MyTitle

**Comment by mde** [comment]
Could you give a little more context about what flavor of not working?

**Comment by RyanZim** [comment]
@jay-gandhi if we do not receive a reply within 7 days, I will close this issue.

**Comment by mde** [comment]
Thank you for doing this cleanup!
