### ISSUE TITLE
`filename: 'src/src'` works, but `filename: 'src/'` does not?

### ISSUE THREAD

**Issue by nchase** [mde/ejs#128]
Hi folks. Really happy with EJS.

This morning I found some things that seem weird around the `<%- include %>` feature. 

Here are a couple of questions around the weirdness:

## Why do I need `filename` on CLI, but not in express?
When I render a template  with `<%- include('') %>` in an express server, I don't get an error saying that I must use the `filename` option, but when I render the same template on the command line, I do. Does anyone know why that happens?

## I think I found a bug – is a string like `'src/'` filtered out anywhere in the code?
When compiling in the command line, if I specify `src/` as the `filename`, it cannot find the files. If I specify `src/src/` as the directory, it finds the files in the appropriate place. I don't understand, because there's only a `src/`, there is no `src/src/`.

I know this seems crazy. If you can't reproduce or nothing comes to mind, I'll try harder to reproduce under my conditions. Thanks for your time and effort!

**Comment by RyanZim** [comment]
include can be confusing.

1. My guess is that you're using `render()` on the CLI while express uses `renderFile()`
2. `filename` is the name of the file that contains the `include` (eg. `src/about-page.ejs`). EJS ignores the filename part (`about-page.ejs`). You could specify the `filename` as `src/asdf.ejs` (or any random string) and it will still work! When you only specify `src/`, the entire string is ignored, but when you use `src/src/`, EJS ignores the second `src`.

What CLI tool are you using?

**Comment by RyanZim** [comment]
There is little documentation for `renderFile()` #135. I'm working on fixing that.

**Comment by RyanZim** [comment]
@nchase ping?

**Comment by nchase** [comment]
hey @RyanZim, sorry for the delay. yeah, I am using `render()` on the CLI.

**Comment by nchase** [comment]
also, thanks for the awesome feedback and giving me some insight into what might be happening here! when time allows, I will confirm.

**Comment by RyanZim** [comment]
@nchase ping?

Real curious what CLI you're using.

**Comment by RyanZim** [comment]
@nchase ping?

**Comment by nchase** [comment]
hey @RyanZim, really appreciate you following up. Sorry I've been so unresponsive, just lacking in time lately.

Here's the script that I wrote that uses EJS's `render` method: https://github.com/nchase/memetica/blob/2626853933181c4a1730002340810d6fa51c84a6/ejs-cli.js

There's a lot to parse through and it isn't particularly well-documented because I didn't think anyone would be reading it at this point in time 😅 . down at the bottom you can see my call to `render` where I print whatever is produced to stdout. I don't want you to have to spend too much effort on this – no need to be digging through my code, it's entirely possible that the problem is on my end :)

**Comment by RyanZim** [comment]
> I don't want you to have to spend too much effort on this – no need to be digging through my code

Well, I did anyhow! :grinning: 

To fix your problem, you should delete [Line 25](https://github.com/nchase/memetica/blob/2626853933181c4a1730002340810d6fa51c84a6/ejs-cli.js#L25), and edit [Lines 53-72](https://github.com/nchase/memetica/blob/2626853933181c4a1730002340810d6fa51c84a6/ejs-cli.js#L53-72) to read:
```
ejs.renderFile(layoutPath, {
    data: {
      styles: data.styles
    },
    frameContent: content,
    index: contentPath.match('index.md') ? true : undefined,
    header: header,
    footer: footer,
    title: title,
    prefix: process.env.prefix || 'src/',
    requestStyle: '',
    bodyClass: data.bodyClass({
      frame: frame,
      singleColumn: matchers.singleColumn(content)
    }),
    hasCode: matchers.hasCode(content),
    notrack: false,
    published: true
  }, function(err, res){
    if (err) {
      // handle it
    } else {
      process.stdout.write(res);
    }
  });
```
Note that you'll need to add error handling.

---

EJS does have JSDoc annotations. To view the API docs, clone the repo and run:
```
npm i
npm run doc
```
Open `out/index.html` in your browser, and there you are!

If I missed something, you can comment below and I'll reopen.

**Comment by RyanZim** [comment]
Also wanted to say: It's best to pass a separate option for the data and EJS options; see https://github.com/mde/ejs#usage

**Comment by nchase** [comment]
awesome, thanks for the heads up. I created an issue in my repo (nchase/memetica#31) to remind me to fix this.
