### ISSUE TITLE
adding underscore no longer works

### ISSUE THREAD

**Issue by artofspeed** [mde/ejs#131]
In **ejs v1**, I could do

```
var _ = require('underscore')
app.locals._ = _;
```

Then underscore would be available in ejs template. However after I moved to **ejs v2**, it keeps saying `_ is not defined`. Why?

**Comment by mde** [comment]
I am assuming you're talking about an Express app with EJS. I cannot reproduce this problem with Express v4.13.4, EJS v2.4.1, and Underscore v1.8.3.

I do `app.locals._ = require('underscore');` and my template looks like this:

```javascript
<%= typeof locals._.each %>
```
The page renders the word "function."

**Comment by RyanZim** [comment]
@artofspeed, can you explain how to reproduce this?

**Comment by RyanZim** [comment]
@artofspeed, I'm giving you 7 more days to respond or I will close this.

**Comment by RyanZim** [comment]
No Response; Closing.
