### ISSUE TITLE
<%_ if gives me SyntaxError: Unexpected token if 

### ISSUE THREAD

**Issue by yokas** [mde/ejs#132]
I was using v2.3.2 which does not contain <%_, but after I I updated to ejs v2.4.1, I still get this error.
my test code is 

`
  <%_ if (user) { _%>`
                         `   ok`
   `    <%_ } else { _%>`
`no`
    `  <%_ } _%>`

@mde @andidev

**Comment by mde** [comment]
Can't repro with v2.4.1:

```javascript
> var ejs = require('../ejs/lib/ejs.js');
undefined
> ejs.VERSION;
'2.4.1'
> var fs = require('fs');
undefined
> var templ = fs.readFileSync('./test.ejs').toString();
undefined
> templ;
'<%_ if (user) { _%>\nok\n<%_ } else { _%>\nno\n<%_ } _%>\n'
> ejs.render(templ, {user: false});
'no\n'
> ejs.render(templ, {user: true});
'ok\n'
```

**Comment by RyanZim** [comment]
@yokas, can you explain how to reproduce this?

**Comment by RyanZim** [comment]
@yokas, I'm giving you 7 more days to respond or I will close this.

**Comment by yokas** [comment]
@RyanZim @mde sorry for late reply, I fount out that despite that I installed v2.4.1,  i'm still using ejs1.0.0 which is used by ejs-mate..
