### ISSUE TITLE
Documentation for renderFile

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#135]
I can't find any documentation for `ejs.renderFile`. I figured out how to use it from looking at the source code, but it should be documented someplace.

Also, it should be noted that the `filename` option is not required for `include` if you are rendering via `ejs.renderFile`.

Can submit a PR.

**Comment by mde** [comment]
@RyanZim I've added you as a collaborator. We should probably still work via PRs, but you do have the merge bit. :)

**Comment by RyanZim** [comment]
Thanks @mde!

I think I'll be submitting a bigger PR that updates the docs and fixes #124 and other bugs.

**Comment by RyanZim** [comment]
@mde what are all the branches in the repo used for? (development, cli, deps, etc.)
