### ISSUE TITLE
Add API Reference

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#137]
[syntax.md](https://github.com/mde/ejs/blob/master/docs/syntax.md) mentions an api.md file that does not exist.
EJS should have a good function reference.

**Comment by RyanZim** [comment]
On the task list for #138.

**Comment by RyanZim** [comment]
On second thought, is this unnecessary redundancy with the jsdocs?

Perhaps we should document `npm run doc` in the README instead.

**Comment by mde** [comment]
Docs are hard. In my mind, there are two types of doc: API docs, and how-to docs. This is essentially the difference between a reference and a guide.

I seem to remember that the API ref was something @TimothyGu was working on. Was that in a branch, Timothy?

**Comment by RyanZim** [comment]
I totally agree with the part about two types of docs. Sadly, ejs is short on both IMO.

Firstly, I think we should document the (wonderful) `npm run doc` script in the README. Also perhaps we could consider adding the jsdoc reference as a folder on the website. (ejs.co/api perhaps?) It would be good not to force users to clone the repo just to get the api refs.

---

Regarding "guide" docs: how much guides/tutorials/how-to's do we want in the `docs/` folder and how much should be stored elsewhere?

**Comment by mde** [comment]
I think we could defer a lot of stuff to the Web site, or to the docs folder, as long as the stuff is readable in a browser. I have also used processes that generate what's in the Web site out of data that's available in the main repo. That can be helpful keeping stuff in sync.

**Comment by TimothyGu** [comment]
Can't find it, sorry.

**Comment by RyanZim** [comment]
Thanks for the info @TimothyGu.

@mde: what is your opinion? Are the jsdocs understandable enough or do we need a separate human-written api reference?

**Comment by RyanZim** [comment]
@mde @TimothyGu: I'm stuck over at #138 because we don't have online documentation for ClientFunction and IncludeCallback.

I tend to favor the JSDocs, at least for now.

**I've decided: here's what I want:**

- A subdomain on the website (docs.ejs.co) that directs to a separate repo that contans the output of  `npm run doc`
- This repo should contain a npm or shell script that: 
   - clones the ejs repo
   - runs `npm run doc`
   - copies the contents of the `out/` folder into the root of the repo
   - deletes the folder ejs was cloned into.
   - This would make updating the repo easy: clone the repo, run the script, commit, and create a PR.
- I would be willing to set up and help maintain this.

How does that sound to you?

**Comment by TimothyGu** [comment]
JSDocs is fine. For the record I prefer running such a task on a bot (like travis) so that no human interaction is needed.

**Comment by RyanZim** [comment]
@TimothyGu That would be great; problem is: I don't know how to set something like that up.

**Comment by TimothyGu** [comment]
It's not difficult. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd should help. Beware that you shouldn't run the deployment process for every Node.js release: only run it with, say, the latest Node.js version.

https://github.com/mxe/mxe/blob/master/tools/travis-push.sh is the script I wrote for another project doing the same thing (also check out https://github.com/mxe/mxe/blob/master/.travis.yml#L4-L6).

**Comment by RyanZim** [comment]
@TimothyGu I removed my assignment to this issue. I do think it's a great idea, but I don't trust myself to set it up. Perhaps you or @mde could run with this.

For the time being, I have a gh-pages site at http://ryanzim.github.io/ejs-api that is manually updated. Please note that this contains the private API as well (I ran `npm run devdoc` to generate it).

**Comment by RyanZim** [comment]
@TimothyGu What do you think of https://github.com/X1011/git-directory-deploy?

**Comment by RyanZim** [comment]
@TimothyGu ping?

**Comment by RyanZim** [comment]
@TimothyGu ping?

**Comment by RyanZim** [comment]
@mde What are your thoughts here?

**Comment by RyanZim** [comment]
@TimothyGu Thinking about this a bit more, perhaps we should keep the hosted docs in sync with the latest release instead of `master`. This might help avoid Issues relating to features that haven't been shipped in a release yet.

If we do that, we wouldn't want to use Travis for updating.

**Comment by mde** [comment]
It's okay for the README in GH to reflect current master, but the published/hosted docs should definitely be for the latest release.

**Comment by RyanZim** [comment]
@mde @TimothyGu I might take a shot at implementing this. One question: how do you set a "`postpublish`" task in jake?

**Comment by mde** [comment]
Could you give me a better idea of what you're trying to do? Tasks are all event emitters, and you can listen for the "complete" event on them, but there might be a better way to accomplish what you're wanting to do.

**Comment by RyanZim** [comment]
@mde I was wanting to run a task to push the JSDocs to gh-pages after the `publishtask` was successfully completed.

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
Jake tasks are all event emitters, and the `publishTask` is just a wrapper that auto-creates a series of callable tasks. (`jake -T` will show you the tasks, including this programatically created `jake publish`.)

All these tasks can be accessed as properties on the `jake.Task` constructor -- you could add a listener for the `complete` event on the `publish` task, like so:

```javascript
jake.Task.publish.on('complete', function () {
  // Do my stuff
});
```

Let me know if that works for you.

**Comment by RyanZim** [comment]
Fixed in https://github.com/mde/ejs/pull/201.
