### ISSUE TITLE
v2.4.1 Release

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#139]
Attn: @mde 

https://github.com/mde/ejs/releases lists the [v2.4.1 tag](https://github.com/mde/ejs/releases/tag/v2.4.1), but still marks [v2.3.4](https://github.com/mde/ejs/releases/tag/v2.3.4) as the latest release.

This affects https://github.com/mde/ejs#client-side-support as the link to the latest release links to v2.3.4.

v2.4.1 doesn't seem to have client-side-support files (ejs.min.js, etc.).

Is this a bug or is there some reason for this?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
Looks like NPM uses GitHub's Release API to know what is the latest (https://github.com/mde/ejs/releases) I haven't updated the `jake publish` to plug into that API yet, so I have been manually creating each new release after publishing to NPM. Manual processes are always error-prone (as you can see), and I was in a huge rush when I pushed the last update, so I just forgot. :) It's updated now.
