### ISSUE TITLE
Compile file on server and send to client for later usage ?

### ISSUE THREAD

**Issue by daslicht** [mde/ejs#140]
Hi,
Is there somewhere an example how to compile a template  on the server (express) and send it to the client for later usage , please ?

**Comment by RyanZim** [comment]
All of the examples are contained in the `examples` directory. There currently is no examples for using ejs with express (though it is commonly done).

Personally, I don't have any experience with express; but I hope the following will be of help:

`compile()` takes two parameters: the EJS-parsable string and the (optional) [options](https://github.com/mde/ejs#options). It returns a function that take a single parameter: `data`, a JavaScript object containing your variables.

For example:
```
var str = "Hello <%= name %>!";
var template = ejs.compile(str, options);
var data = {name: "John Doe"};
template(data); // Outputs "Hello John Doe!"
```

For your example, you would want to compile the string on the server and send the resulting function to the client. You could then set your `data` object and call the function on the client.

Again, I don't have a good enough knowledge of express to give you actual examples, but I hope this helps you.

If you get it working, I'd welcome a PR that adds an example for this.

**Comment by daslicht** [comment]
Thank you !
