### ISSUE TITLE
Read over html comments in EJS files

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [mde/ejs#141]
Was working on a node web project and my .ejs files have html comment blocks. Imagine my surprise when my node server crashed with a 500. We know `<%# THIS WORKS %>` for comments, but it would be convenient if EJS also overlooked it's own syntax inside of html comments:

**edit:** I can implement this and make a pull request if the authors are interested. Let me know. I'd love to contribute!
   
    

    <div id="nav">

    

    <p>Mr. Placeholder</p>

     ...
`

**Comment by RyanZim** [comment]
EJS doesn't parse HTML at all; rather, it only looks for its tags (similar to PHP). This allows things like:
`<p class="btn btn-<%= type %>">Lorum</p>` etc.

I don't think this would be quite so simple as it looks; you would have to accommodate all of the following scenarios (and more):
```
<!--<%= name %>-->
<!--<p class="btn btn-<%= type %>">Lorum</p>-->
<!--<p class="btn" <%= att %>>Lorum</p>-->
```

Just a few things I thought of: What about `<%` tags? Do we ignore the logic inside of them if they're enclosed in `<!--`? What about the following scenarios?
```
<% if(bool){ %>
<!--<p>Hello World!</p>
<% } %>-->

<!--<% if(bool){ %>
<p>Hello World!</p>-->
<% } %>
```
I'm personally not in favor of it; but CC: @mde for the final decision.

**Comment by mde** [comment]
I don't think this really makes sense when considering what EJS is supposed to do. It's just suppose to parse its own tags, and output the correct HTML. (And comment tags are obviously valid HTML.) I can definitely imagine scenarios where someone wanted to write out some HTML comments dynamically, and you could not do that if EJS also ignored those in the template source.
