### ISSUE TITLE
Add more explaination for Client-Side Support.

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#142]
I think we should give better examples of Client-Side Usage in the README. See #106. Also, perhaps we should refine and expand the examples in [examples/](https://github.com/mde/ejs/tree/master/examples).

[client-compilation.html](https://github.com/mde/ejs/blob/master/examples/client-compilation.html) is a bit exhaustive (though useful); [client-injection.html](https://github.com/mde/ejs/blob/master/examples/client-injection.html) is good; however, both of them use `compile()`, not `render()` (which is recommended in the README). There should be some example of using `render()` on the client side.

Also, we should add a note about using `ejs.compile(str, {client: true})` and the resulting:
```
 * @callback ClientFunction
 * @param {Object}          [locals={}]
 * an object of data to be passed into the template. The name of this variable
 * is adjustable through {@link module:ejs.localsName}.
 *
 * @param {EscapeCallback}  [escape={@link Options}.escape]
 * callback used to escape variables
 *
 * @param {IncludeCallback} [include]
 * callback used to include files at runtime with `include()`
 *
 * @param {RethrowCallback} [rethrow={@link module:ejs-internal.rethrow}]
 * callback used to handle and rethrow errors
```

@mde: where do you think these things should be noted?

**Comment by mde** [comment]
The first place people look is the README. As long as it doesn't become unreadably large, these things could go in there. For more details, you could link directly to the examples from there.

We also want the Web site to be a good resource -- a Google search for "EJS" still has the two (different) older implementations coming up first.

**Comment by RyanZim** [comment]
@mde OK. Will add to #138.

I'll fall to updating the website later. See #137.

**Comment by RyanZim** [comment]
PR #112 tests and documents the `escape` option, so that's partially fixed.

**Comment by RyanZim** [comment]
@mde I think that [docs/jsdoc/options.jsdoc#L27](https://github.com/mde/ejs/blob/master/docs/jsdoc/options.jsdoc#L27) needs fixing.

```
* @property {Boolean} [client=false]
* Whether or not to compile functions that are to be included in the browser.
```

Very ambiguous IMO. How about something like:

```
 * Whether or not to compile a {@link ClientFunction} that can be included in the browser 
 * without depending on ejs.js.
```
