### ISSUE TITLE
mad/ejs compile time vs underscore template ?

### ISSUE THREAD

**Issue by honwsn** [mde/ejs#149]
mad/ejs compile time vs underscore template ?

did have some test data about this?

**Comment by honwsn** [comment]
i've test it for no cache enviroments 
ejs: 211.600ms
underscore: 123.976ms

underscore template  is better.  :+1:

**Comment by honwsn** [comment]
It's too bad 。。

**Comment by RyanZim** [comment]
EJS can be a bit slow. If you have ideas how to make it faster, please share them. As @mde said once:

> Give us a PR...I'll be happy to merge it. This is how open source works, folks.

BTW, #49 is @TimothyGu's issue for making EJS faster. You are welcome to volunteer to contribute there.

**Comment by TimothyGu** [comment]
> underscore template is better.

Underscore and EJS are different things, created for different purposes. Just because one is _faster_ than the other in _one_ benchmark doesn't mean one is better than the other.

Just wanted to make this clear.
