### ISSUE TITLE
Add warning for ejs.render(dataAndOptions)

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#152]
https://github.com/mde/ejs#usage says:

> You can also use the shortcut `ejs.render(dataAndOptions);` where you pass everything in a single object. In that case, you'll end up with local variables for all the passed options.

Shouldn't we add a warning that this could result in collisions with users data if we add another option?

For example, if someone would have been passing a data variable named `rmWhitespace` before v2.3.4, npm would auto-update and ejs would throw an error (assuming rmWhitespace was being passed as a non-boolean type).

I can do a PR.

**Comment by RyanZim** [comment]
CC: @TimothyGu, @mde

**Comment by mde** [comment]
Definitely adding a warning here makes sense. IIRC, that single-obj API is the older one, really more for backward compatibility. The preferred API is the more explicit one. It might make more sense to describe it that way instead of calling it a shortcut.

**Comment by RyanZim** [comment]
OK, Will Do.
