### ISSUE TITLE
Output literal `%>` with `%%>`

### ISSUE THREAD

**Issue by roymiloh** [mde/ejs#153]
The same as `<%%` that outputs literal `<%`, but at the opposite direction. I haven't found it in the lexer, so I guess it doesn't seem to work in any way.

**Comment by TimothyGu** [comment]
Can you provide a test case?

**Comment by roymiloh** [comment]
Sure, but I found something weird (maybe related to another issue) -

the following test passes (somehow?):
```js
assert.equal(ejs.render('<%% %>'),
  '<% %>');
```

however, when doing something nested, it fails:

```js
assert.equal(ejs.render('<%% <%% %> %>'),
  '<% <% %> %>');
// output: '<% <% %> '
```

in any case, I would expect that I had an escaping tag for `%>` as well:

```js
assert.equal(ejs.render('%%>'),
  '%>');
// output: '%'
```

**Comment by RyanZim** [comment]
@roymiloh Here's the behavior of the literal tag; all of these tests pass:
```
// Opening tag:
assert.equal(ejs.render('<%%'),
  '<%');
// Unescaped closing tags are ignored,
// That's why your last example renders the way it does
assert.equal(ejs.render('%>'),
  '');
// Output both opening and closing tags:
assert.equal(ejs.render('<%% %>'),
  '<% %>');
// Text between the tags has no effect:
assert.equal(ejs.render('<%% somevar %>'),
  '<% somevar %>');
```

In short, you can't just output `%>`, you have to output `<% %>` by doing `ejs.render('<%% %>')`.

As for the nested example, EJS does not support nested tags in any way.

**Comment by roymiloh** [comment]
@RyanZim, That the whole point, why can't I just output `%>`? as I said, I know it shouldn't work and I think it's a nice (required?) enhancement (why preventing to make this output?). 

In addition, why `<%% %>` outputs `<% %>`? I would expect that it outputs just `<%`, as `%>` alone translated to empty string.

Anyway, `%%>` to literal `%>` could be really useful.

**Comment by RyanZim** [comment]
@roymiloh:

> why <%% %> outputs <% %>?

Because at this time, that's the only way to output `%>`.

I'm not sure exactly why it was built that way, but it does make writing examples easier.

For example:
`<%% for(i=0;i<10;i++){ %>Hello World!<%% } %>`
Would render to:
`<% for(i=0;i<10;i++){ %>Hello World!<% } %>`

If we had to use `%%>` every time, we would have to type
`<%% for(i=0;i<10;i++){ %%>Hello World!<%% } %%>`
to achieve the same result.

To be clear, I'm not terribly opposed to adding a `%%>` literal tag, however, I think we should keep the `<%% %>` = `<% %>` behavior. (Besides, removing it would break backwards compatibility.)

CC: @mde & @TimothyGu for a decision regarding `%%>`.

**Comment by zen-mde** [comment]
I can imagine the use for a literal closing tag. And yes, we wouldn't want to break existing functionality.

Let's leave this open and implement if possible.

**Comment by mde** [comment]
(Sorry, initially replied with my work account.)

I can imagine the use for a literal closing tag. And yes, we wouldn't want to break existing functionality. 

Let's leave this open and implement if possible.

**Comment by RyanZim** [comment]
@roymiloh Is this something you would be interested in doing?

**Comment by roymiloh** [comment]
@RyanZim Sure. I'm on it.

**Comment by RyanZim** [comment]
I said earlier:
> I'm not sure exactly why it was built that way

https://github.com/mde/ejs/issues/153#issuecomment-211401363

I just came across #27; at one time, you had to output both tags (`<% %>`) by typing `<%% %>` to output `<%`.
