### ISSUE TITLE
Client sided support for loading templates

### ISSUE THREAD

**Issue by JtotheM** [mde/ejs#154]
Is there a reason that there's no support for loading a template on the client side? I mean, there currently is the option to give a template string and parse that, but I want EJS to load the template from the server (from a public folder). If there is no reason I will simply add the function to EJS and commit it.

**Comment by RyanZim** [comment]
@JtotheM Currently, you would need to do an AJAX request for the file and then pass the file's contents to `ejs.render()`. I'm not sure how performant that would be, though.

We do have a function, `ejs.renderFile()` for use on the server-side that loads a file (using the nodejs `fs` module), so perhaps it would be a good idea to add a similar function for the client side (that performs an AJAX request).

What do you think, @mde and @TimothyGu?

**Comment by JtotheM** [comment]
Well I already have it ready for you guys:

`exports.renderUrl = function(url, options, fn) {
  var key = url + ':string';

  if ('function' == typeof options) {
    fn = options, options = {};
  }

  options.filename = url;

  var str;
  try {
    if(options.cache && typeof(cache[key]) != 'undefined') {
      str = cache[key];
      fn(null, exports.render(str, options));
      return;
    }

    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", url, true);
	xmlHttp.onreadystatechange = function() {
      if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
        str = xmlHttp.responseText;
        if(options.cache) {
          cache[key] = str;
        }
		
        fn(null, exports.render(str, options));
      }
	};
	
    xmlHttp.send();
  } catch (err) {
    fn(err);
  }
}`

**Comment by RyanZim** [comment]
@JtotheM Good start!

It would probably be best to wait until one of the other collaborators gives approval before making a PR.

Also, the function should take four arguments: `url, data, options, fn`. Some of this should probably be reworked to be more similar to `ejs.renderFile()`.

**Comment by mde** [comment]
Might actually make sense to have the `renderFile` functionality work similarly on both client and server. Then you could install an extension to get the client-side functionality if you really wanted it.

Although honestly, fetching templates via HTTP from a server would perform pretty badly. I can't imagine wanting to use something like this in production.

**Comment by RyanZim** [comment]
@JtotheM What's your opinion?

**Comment by JtotheM** [comment]
I am using this currently in production with zero negative effects. I am using this to render items that are retrieved from an API. Each item has HTML worth of 408 bytes.

Previously I sent the HTML from within the first request so that my javascript could pick it up and use it. Since a few days I switched to my renderUrl function. The original request is 408 bytes smaller and instead the browser makes a second request for those 408 bytes. Of course there is overhead by the HTTP protocol but this is neglectable. Please remember that Keep-Alive will definitely help in providing the template by keeping the connection open. Secondly, the template will return a 304 (not modified) a second time and is rendered from the browser's cache. Thirdly, using the optional "cache" option, you only load the template once into memory so that the remaining items that use this template load from memory just like a "normal" template would.

Honestly, I think a second function would be needed to "preload" the template. If you do a lot of requests at the same time before any of those is done, the caching will not be applied since the cache array is not yet filled. Preloading and rendering in it's callback fixes this problem (this problem is also apparent with your renderFile function).

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde @TimothyGu What are your thoughts on this?

**Comment by RyanZim** [comment]
@mde @TimothyGu ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
I actually think a plugin/extension would be the right approach for this. It doesn't seem like a function most mainstream users would want, and XHR code-loading is not really within the purview of EJS itself. If we could get control of the "ejs" namespace here on GH, that plugin could even go there. Let's close this issue for now.

**Comment by RyanZim** [comment]
I agree with @mde. I have often though someone should create a module meant for client side use only.

It could include a function like this (`renderAJAX()`), a function to render the contents of an id (`<template>` or `<script type='text/ejs'>`), a function to use as an IncludeCallback that would use AJAX for loading an `include()`, etc.

@JtotheM if you would build such a module, I would consider adding a link to it from the README.

Closing.

**Comment by S2-** [comment]
Sorry if I comment on this old closed issue, but I don't feel like opening a new issue for this, and if someone finds this because she is looking for it he may find this useful:
I made a script `ejs.rr` that does exactly what the parent submitter needed: https://github.com/S2-/ejs-render-remote

Hope it can be useful for someone.
