### ISSUE TITLE
Add JSDocs before releasing v2.5.1

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#156]
Attn: @mde 

Be aware that the changes in 958c80d9c5b286ed2f88b81329b3eb8956cb6618 (export escape function) do not have JSDocs for them. These should be added before releasing the next version. This would be a minor version bump (correct?)

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
Yes, it's additive, so it would be a minor revision.
