### ISSUE TITLE
client side Ajax

### ISSUE THREAD

**Issue by EasonWang01** [mde/ejs#158]
I want to load data,then using ejs to render it,but below will says res not define,how to solve it?

thanks for reply.

```javascript

<script>
var xhttp = new XMLHttpRequest();
xhttp.open('POST', '/articleData');
xhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
xhttp.onreadystatechange = function() {
if (xhttp.readyState == 4 && xhttp.status == 200) {
	console.log(xhttp.responseText);
	res = JSON.parse(xhttp.responseText);
	
}}
xhttp.send();
</script>

<ul>
<% for(var i=0; i<res.length; i++) {%>
   <li><%= res[i] %></li>
<% } %>
</ul>

```

**Comment by RyanZim** [comment]
If I understand the problem correctly, here's how:
```
<script>
var res;
var xhttp = new XMLHttpRequest();
xhttp.open('POST', '/articleData');
xhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
xhttp.onreadystatechange = function() {
if (xhttp.readyState == 4 && xhttp.status == 200) {
    console.log(xhttp.responseText);
    res = JSON.parse(xhttp.responseText);

}}
xhttp.send();
// Render
var rendered=ejs.render('<ul><% for(var i=0; i<res.length; i++) {%><li><%= res[i] %></li><% } %></ul>', res);
// Output `rendered` via DOM manipulation
</script>
```
If this answered your question, please close this.

**Comment by EasonWang01** [comment]
thanks,but should I include any client side ejs for `ejs.render`?

I was using http://www.embeddedjs.com/ now.

**Comment by RyanZim** [comment]
@EasonWang01 `app.set('view engine', 'ejs');` and `res` is only for use in express (server-side). 

In the example I gave you would need to download and include ejs; see https://github.com/mde/ejs#client-side-support. My example won't work with embeddedjs.com.

Regarding the differences, there are quite a few. mde/ejs is written as a CommonJS Node Module and ported to the client side via browserify. Embeddedjs.com only works on the client side and has AJAX built in. mde/ejs requires you to provide AJAX yourself.

Study the documentation for both and see what you prefer. (You may want to look at PR #138 for better documentation.)

**Comment by EasonWang01** [comment]
thanks,is there a document that tell about the mde/ejs client api?

**Comment by RyanZim** [comment]
There isn't in the master branch. PR #138 adds documentation. You can look at that branch here: https://github.com/mde/ejs/tree/update-docs#client-side-support.

**Comment by RyanZim** [comment]
Hope that helped! Closing.
