### ISSUE TITLE
scoping issues with const in a loop

### ISSUE THREAD

**Issue by rlemon** [mde/ejs#161]
I'm not sure if const is actually supported, but it does not error (however results are not expected). 

when using const in a for..of loop in ejs the first value is all that is used for the rest of the iterations. 

sample code: 

test.js - 
```
var ejs = require('ejs');

console.log(ejs.render(require('fs').readFileSync('test.ejs', 'utf8'), {
  arr: [{
    name: 'apples',
    color: 'red'
  }, {
    name: 'apples',
    color: 'green'
  }, {
    name: 'banana',
    color: 'yellow'
  }]
}));
```

test.ejs - 
```
<% for( var foo of arr ) { %>
	<div><%= foo.name %> - <%= foo.color %></div>
<% } %>

<% for( const bar of arr ) { %>
	<div><%= bar.name %> - <%= bar.color %></div>
<% } %>
```

result - 

> 	<div>apples - red</div>
> 
> 	<div>apples - green</div>
> 
> 	<div>banana - yellow</div>
> 
> 	<div>apples - red</div>
> 
> 	<div>apples - red</div>
> 
> 	<div>apples - red</div>
> 

If this is expected behavior (or const is outright not supported and I missed that note) I apologize for wasting everyones time. I haven't tried let because node doesn't like it outside of strict yet (actually throws an error). 

using ejs 2.4.1

**Comment by RyanZim** [comment]
I'm not real familiar with ES6; can you try running this in node?
```
var arr = [{
    name: 'apples',
    color: 'red'
  }, {
    name: 'apples',
    color: 'green'
  }, {
    name: 'banana',
    color: 'yellow'
  }];
for( const bar of arr ) {
    console.log(bar.name+' - '+bar.color);
}
```
What is the terminal output? I just want to make sure this is not an issue with node.

**Comment by ssube** [comment]
Running

```
ssube@ops-vm ~/scratch $  > cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)               
ssube@ops-vm ~/scratch $  > node -v
v4.4.3      
```

with `const` produces:

```
ssube@ops-vm ~/scratch $  > node apples.js
apples - red                              
apples - red                              
apples - red                              
```

with `var` produces:

```
ssube@ops-vm ~/scratch $  > node apples.js
apples - red                              
apples - green                            
banana - yellow                           
```

and with `let` produces:

```
ssube@ops-vm ~/scratch $  > node apples.js                                                                
/home/ssube/scratch/apples.js:11                                                                          
for( let bar of arr ) {                                                                                   
     ^^^                                                                                                  
                                                                                                          
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by ralt** [comment]
Running:

```
$ node --version
v6.0.0
```

With `const`, `let` and `var`:

```
$ node apples.js
apples - red
apples - green
banana - yellow
```

Clearly, there's some node issue there.

**Comment by rlemon** [comment]
yes it seems to be a node issue. My apologies. v5.2.0 also suffers from it, v6.0.0 is working as expected. 

My bad.

**Comment by langri-sha** [comment]
http://hastebin.com/asazixewec.js

**Comment by RyanZim** [comment]
@rlemon No Problem.

**Comment by RyanZim** [comment]
@rlemon FWIW, EJS uses `new Function()` internally, so any JS that runs in node should run in EJS. Here it is in the source code: https://github.com/mde/ejs/blob/master/lib/ejs.js#L485

**Comment by rlemon** [comment]
good to know, this was a kick in the butt to stop being lazy and upgrade my node version.
