### ISSUE TITLE
LICENSE file doesn't ship on npm install

### ISSUE THREAD

**Issue by jorgevgut** [mde/ejs#164]
Hello, please could the LICENSE file be included on the ejs package found on npm repository?
when performing "npm install ejs"
these are the files i get:
    ejs.js  ejs.min.js  Jakefile  lib  package.json  README.md  test

Even when Apache 2 License is mentioned on the readme and package files, I don't think it complies with the redistribution term on the license.
http://www.apache.org/licenses/LICENSE-2.0

Cheers,
Jorge

**Comment by RyanZim** [comment]
Confirmed. Beyond me why it isn't included; from https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package:

> The following paths and files are never ignored, so adding them to .npmignore is pointless:
- package.json
- README (and its variants)
- CHANGELOG (and its variants)
- LICENSE / LICENCE

@mde or @TimothyGu have any ideas?

**Comment by RyanZim** [comment]
I opened an issue on npm: https://github.com/npm/npm/issues/12823.

**Comment by RyanZim** [comment]
@mde ping?

**Comment by zen-mde** [comment]
This is not an NPM issue. It's ours. I am fixing it right now.

**Comment by mde** [comment]
This is not an NPM issue. It's ours. I am fixing it right now. (Sorry, previously posted from my work account -- I keep doing that. :))

**Comment by RyanZim** [comment]
I closed the npm issue.

**Comment by mde** [comment]
Fixed here: https://github.com/mde/ejs/commit/459d35ffa95f49f9c0186c62ea99f1a7829c101e Creating a release now.

**Comment by RyanZim** [comment]
Why didn't I think of looking in the Jakefile?

**Comment by RyanZim** [comment]
What about https://github.com/mde/ejs/issues/156?

**Comment by mde** [comment]
I don't think it should be a blocker for a release. I'll hold off on pushing the release until later tonight, if you'd like to go ahead and add the docs.

**Comment by RyanZim** [comment]
@mde If you don't mind publishing a patch release within a few days, then just release it :shipit:. I'm not sure if I can get a PR together tonight or not.

**Comment by RyanZim** [comment]
BTW, don't forget the CHANGELOG & client-side files. :wink:

**Comment by RyanZim** [comment]
@jorgevgut OK, fixed in v2.4.2. Thanks for reporting!

@mde I added the changelog content to the GitHub release. Closing.

**Comment by jorgevgut** [comment]
You guys are awesome, thank you :)
