### ISSUE TITLE
Type checking for all input

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#168]
In light of #166, I was thinking that perhaps we should add type checking to all input values. This would prevent such breaking changes in implicit behavior.

Exactly how this should be done, I'm not sure, but it is something to consider.

**Comment by mde** [comment]
Checking all input might be overkill, and isn't really the JavaScript way of doing things. (We would be using TypeScript or similar if that were the case.) 

I think it's our responsibility to make it clear in the docs what type of input should be used, but checking everywhere seems excessive.

**Comment by RyanZim** [comment]
> it is [just] something to consider

If you don't think so, you can close this.

**Comment by mde** [comment]
If we see people habitually passing the wrong type in particular instances, it's worth checking those, but doing it globally seems like overkill, yes. Another alternative is modifying those instances to support the incorrect type.

Anyhow, let's close this.
