### ISSUE TITLE
Next release: EJS 2.0.9/2.1.0

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#17]
This issue is basically a question of the version and contents that will be in the next release. In our [changelog](https://github.com/mde/ejs/blob/master/CHANGELOG.md), I have separated out two commits that might be better if we put it in another minor release (i.e. 2.1.0). So the question now is, should we just release a 2.1.0 with all changes since 2.0.8, or a 2.0.9 with bugfixes then 2.1.0?

**Comment by mde** [comment]
I think a minor version bump is fine at this point. There are a fair number of changes, but it's all backward compatible. I'll update the changelog, and push a release out to NPM.

**Comment by TimothyGu** [comment]
Cool

**Comment by mde** [comment]
https://github.com/mde/ejs/releases/tag/v2.1.1
