### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#173]
Just opening an issue to let everyone know I'll be working on this in the `deps` branch. (**Don't merge it**, I want to rebase first.) Don't know when I'll get done, just working on it when I get time.

Here is the Checklist:

- [x] uglify-js
- [x] istanbul
- [x] jsdoc
- [x] lru-cache
- [x] browserify

**Comment by RyanZim** [comment]
@mde @TimothyGu In updating browserify, I was wondering what browsers we support.

Also, perhaps we should update our .travis.yml to test on 4, 5, and 6 (or perhaps the nvm `node` keyword). Also, is there a reason to actively test for iojs? Browserify is not tested on iojs.

**Comment by TimothyGu** [comment]
> Also, perhaps we should update our .travis.yml to test on 4, 5, and 6 (or perhaps the nvm `node` keyword).

Yes, though not 5 as it is not actively maintained anymore.

> Also, is there a reason to actively test for iojs? Browserify is not tested on iojs.

No. We just haven't updated the configuration.

**Comment by mde** [comment]
If possible we ought to take a look at releasing a UMD version. I just used Browserify because it was the most expedient.

**Comment by RyanZim** [comment]
@mde See https://github.com/mde/ejs/issues/146#issuecomment-206418722 & https://github.com/mde/ejs/issues/146#issuecomment-207432566. If you want to take a shot at UMD, you can; I don't have the time or patience.

**Comment by RyanZim** [comment]
Regarding testing, I'll try to make a PR for updating .travis.yml as soon as I can. Should I test for `6` or `node`?

The basic question with browser support is: do we support IE8 or not? If so, we cannot upgrade to browserify v12 or later.

**Comment by TimothyGu** [comment]
> Should I test for `6` or `node`?

V6. V6 will be an LTS we'll have to `6` eventually anyway.

> Is dropping tests for iojs a breaking change?

No. io.js is right in between 0.12 and 4 anyway.

> The basic question with browser support is: do we support IE8 or not? If so, we cannot upgrade to browserify v12 or later.

We do, and we can upgrade. See https://github.com/substack/node-browserify/blob/master/changelog.markdown#1200, it says the module that provides `require('http')` support stopped supporting IE8, but we don't use that module.

> Also, do our browser files conform to SemVer?

Yes.

**Comment by RyanZim** [comment]
@TimothyGu I know, but since browserify has dropped IE8 support for `http`, will they do a major version bump when they drop support in another area?

Random sidenote: we use `.forEach` in our code; does browserify handle this for IE8 support?

**Comment by TimothyGu** [comment]
@RyanZim said,
> I know, but since browserify has dropped IE8 support for `http`, will they do a major version bump when they drop support in another area?

Probably, but good point.

> Random sidenote: we use `.forEach` in our code; does browserify handle this for IE8 support?

No, and that's another good point. I guess after all we don't really support IE8. Since we haven't received reports of EJS not working on IE8, it also means that nobody who cares enough about EJS's development to file an issue uses EJS on IE8.

@mde, what do you think?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
I think we can say we don't care about IE8. Also, if someone really wanted to use it with a browser without `forEach` they could certainly just polyfill it.

**Comment by RyanZim** [comment]
OK, will be moving forward with browserify. PR forthcoming.

**Comment by RyanZim** [comment]
PR is at #177.
