### ISSUE TITLE
Can't resolve 'fs' with WebPack

### ISSUE THREAD

**Issue by FezVrasta** [mde/ejs#174]
When I try to load `ejs` within a WebPack project with `import ejs from 'ejs'` I get:

```
Module not found: Error: Can't resolve 'fs' in 'node_modules/ejs/lib'
```

Is there something I need to do to make it work client-side or what?
Thanks.

**Comment by FezVrasta** [comment]
sorry, had to use ejs-compiled-loader

**Comment by airblade** [comment]
Please could you spell out your solution?  I have just run into this error trying to get started with ejs (on Rails via webpack) and I can't figure out how to make it work.

**Comment by FezVrasta** [comment]
I don't remember this problem but I think it's

https://www.npmjs.com/package/ejs-compiled-loader

**Comment by airblade** [comment]
Thanks.  That's the one I'm trying to use without success.

**Comment by mde** [comment]
The built-and-minified JS file in every release is now compiled with the Browserify `--standalone` flag, which should provide AMD support and ought to work with WebPack. If you're using it client-side, that might be easier than trying to finagle the build yourself.

**Comment by airblade** [comment]
@mde Thanks to your comment I was able to get it working, actually in two ways.

First way: drop the built-and-minified JS file into my project and `require('ejs')` just before I want to use it.  Then I can do `ejs.render(string, data)` etc.  The only downside is I couldn't figure out how to load up separate template files; but instead I can put templates in my html within `<script type="x-template"></script>` tags.

Second way: configure webpack with ejs-compiled-loader as a loader for `*.ejs` files, and then simply `const template = require('some_template.ejs')` where I want to use it.  I don't need a separate `require('ejs')`.

Thanks for the help!
