### ISSUE TITLE
Override the include method

### ISSUE THREAD

**Issue by IonicaBizau** [mde/ejs#178]
Is it possible to override the `include` method so I can make some checks and potentially return another path to be loaded if I want?

Or is there anything similar?

**Comment by RyanZim** [comment]
@IonicaBizau You can override `include('filename', {data: 'value'})` (dynamic include), (but not the static include `<% include file.ejs %>`) by using the `client` option and setting the `IncludeCallback`. You can see an example at https://github.com/mde/ejs#caveats.

If this answers your question, please close.

**Comment by IonicaBizau** [comment]
@RyanZim Cool! Is is possible to add callback support to the `include` method?

**Comment by RyanZim** [comment]
I'm not sure what you mean. Could you give an example?

**Comment by IonicaBizau** [comment]
@RyanZim Something like this:

```js
var str = "Hello <%= include('file', {person: 'John'}); %>",
    fn = ejs.compile(str, {client: true});

fn(data, null, function(path, d){ // IncludeCallback
  // path -> 'file'
  // d -> {person: 'John'}
  // Put your code here 
  // Return the contents of file as a string IN THE CALLBACK
  //                                         ^^^^^^^^^^^^^^^
  readFile(path, function (err, fileContent) {
     cb(err, fileContent);
  });
}); 
```

So instead of return `fileContent`, I want to `callback(null, fileContent)`.

**Comment by RyanZim** [comment]
This might be something to consider; I'll let @mde decide.

CC: @TimothyGu thoughts?

**Comment by TimothyGu** [comment]
See #179. @IonicaBizau, the short answer is "no."

**Comment by TimothyGu** [comment]
Back to the original question of replacing `include()`, the answer is yes. Just pass in an `include` in the locals, although it must return a value like the original `include` function does.

**Comment by RyanZim** [comment]
Does this answer your question?

**Comment by IonicaBizau** [comment]
@RyanZim @TimothyGu Well, it makes sense and I understand this since it's by design. Tho, this is still a limitation for my use-case.

Thanks for your responses and keep up the good work! 👍
