### ISSUE TITLE
Use Asynchronous functions in EJS templates?

### ISSUE THREAD

**Issue by IonicaBizau** [mde/ejs#179]
How to handle asynchronous function calls in the template?

I want to fetch some data (e.g. from GitHub API) and render them in the template.

Is it possible to do something like this?

```html
<%
 fetchData(..., function (err, data) { %>
   <%- err ? "Error" : data.title %>
<% }); %>
```

**Comment by RyanZim** [comment]
Not sure, I never tried it. Where are you using EJS? (Client-side, express, custom node.js, etc.)

You might be better off doing something like this:
```
fetchData(..., function (err, data) {
  var html=ejs.render('The title is <%= title %>', data);
});
```

**Comment by IonicaBizau** [comment]
@RyanZim Pretty much custom node.js + express (but I take care about redering).

Obviously, that works, but I'd really like to have async functionality in the template itself.

Another use-case is when using [`blah`](https://github.com/IonicaBizau/blah). I want to render custom stuff rendered by async methods. [Here](https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs) you can find the template I'm using to create the `README.md` files in my GitHub repositories.

I used `deasync` to make the async functions synchronous ([here](https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs#L30-L41) you can see an example), but I don't really want to do that in my Express app. Instead I want to run async stuff in parallel, grabbing different data and render the template.

Related to this is what happens if I have two `include` calls? Are they synchronous? I hope no. :thought_balloon:

**Comment by RyanZim** [comment]
Thinking about this a bit more, `foreach` works, so asynchronous functions should work. What might be more of an issue is how you're going to get `fetchData` working. You can't `require('http')` out-of-the-box.

`include` currently uses `fs.readFileSync`, however if you turn on the `cache` option, EJS will read the file and store it in the cache. The next request will be read from the cache instead of the filesystem.

**Comment by TimothyGu** [comment]
Nope, EJS doesn't support async. To do something like that, you'd have to get the data before hand and pass it in as a local.

@RyanZim, `forEach` uses callbacks, but is completely synchronous in its operation.

@IonicaBizau, as @RyanZim said, yes, `include()` is synchronous, but if you are using it in production the compiled template is cached anyway so there will be no impact on performance (except for the first rendering).

That being said, if your inclusion calls are dynamic and uncacheable (e.g. `include(myDoc + '.ejs')` with `myDoc` having a different content every time you render the EJS template), your performance **will** suffer. EJS was designed to be completely synchronous.

**Comment by IonicaBizau** [comment]
@TimothyGu @RyanZim To have an `ejs` like syntax but with async support, what should I do? Is it possible to build it on top of `ejs` or should I parse everything from scratch again, like in [`ajs`](https://github.com/kainosnoema/ajs)?

**Comment by SystemDisc** [comment]
I think in almost all cases, you should do any asynchronous stuff before you render your EJS string.

Something similar to this:
```javascript
doAsyncStuff().then((data) => {
    let rendered = ejs.render(templateString, data);
});
```
