### ISSUE TITLE
how to render html text as it is by ejs.renderFile?

### ISSUE THREAD

**Issue by himanshuoodles** [mde/ejs#180]
I am running this code inside node
```
ejs.renderFile(templateDir, locals, {}, function(err, str) {
            console.log("error", err, "str", str)
            res.send(str);
            // str => Rendered HTML string
        });
```

templateDir has a file with code 

 
                <div class="banner-text text-center">
                    <%=HomeFeature %>
                   <button type="button" class="btn-custom" ng-click="startAssessment()">Start Assessment</button>
                </div>
          

locals contains 
 `var locals = { HomeFeature: "<p>hello</p>",    };`

when i excute the code i get this..

 ```
  <div class="banner-text text-center">
             &lt;p&gt;hello&lt;/p&gt;
           <button type="button" class="btn-custom" ng-click="start Assessment()">StartAssessment</button>
        </div>
```
   

and what i want is this

        <div class="banner-text text-center">
                    <p>hello</p>
            <button type="button" class="btn-custom" ng-click="startAssessment()">Start Assessment</button>
        </div>
 
can anybody help

**Comment by RyanZim** [comment]
The `<%=` tag html/xml escapes the output. What you want is the `<%-` tag; like this:
```
<div class="banner-text text-center">
    <%- HomeFeature %>
    <button type="button" class="btn-custom" ng-click="startAssessment()">Start Assessment</button>
</div>
```

**Warning:** _**Never** output user-generated content with `<%-`; this **will** allow XXS attacts._

The full syntax docs are at https://github.com/mde/ejs/blob/master/docs/syntax.md. You may want to read these sections:
https://github.com/mde/ejs/blob/master/docs/syntax.md#-escaped-output
https://github.com/mde/ejs/blob/master/docs/syntax.md#--unescaped-output

**Comment by himanshuoodles** [comment]
Thanks man you did my work
