### ISSUE TITLE
rmWhitespace option is ignored in preprocessed include

### ISSUE THREAD

**Issue by mmis1000** [mde/ejs#183]
The `rmWhitespace` basically do his work in the `compile` method.
https://github.com/mde/ejs/blob/master/lib/ejs.js#L436-L441

However, preprocess include call `generateSource` directly without touch the `compile` method.
https://github.com/mde/ejs/blob/master/lib/ejs.js#L198-L199

Result in `rmWhitespace` completely ignored in sub templetes

**Comment by RyanZim** [comment]
Good catch, thanks for reporting! I don't have time to work on this myself, so I'm assigning this to @TimothyGu.

**Comment by TimothyGu** [comment]
Okay, this means that the whitespace slurping tags don't work either.

Unfortunately, I won't have time to work on it for a while, so I'm removing assignment to myself. It shouldnt be difficult to fox it however.

**Comment by mde** [comment]
@mmis1000 Since you have identified the problem, would you care to put together a PR that fixes this?

**Comment by mmis1000** [comment]
Has opened pull request  #184.

**Comment by RyanZim** [comment]
Fixed in  6b17878.
