### ISSUE TITLE
Can ejs support literal block feature like smarty's `{literal}{/literal}`

### ISSUE THREAD

**Issue by miusuncle** [mde/ejs#185]

**Comment by RyanZim** [comment]
No, it currently doesn't. What is your use-case that causes the conflict?

**Comment by RyanZim** [comment]
If I don't get a reply from @miusuncle within ~3 days, I will close this.

**Comment by miusuncle** [comment]
A common use-case is: I want to include a script block like `<script>xxx</script>` where `xxx` contains `<%=` like characters(_.template source code, for example), but I don't want it have parsed.

**Comment by RyanZim** [comment]
Probably the best way to resolve this is to use a different delimiter with either EJS or `_`. For example, you could use `<$=` for EJS and `<%=` for `_` (or vise-versa).
