### ISSUE TITLE
Jquery GET request and variable

### ISSUE THREAD

**Issue by flexbrane** [mde/ejs#186]
Hi!

I have a function which get an **ejs** page (from my ExpressJS server), and this works. But when I want to get the argument, I can't.

Here is what I have tried :

**routes.js**
```javascript
router.get('/', function(req, res, next) {
    req.session.lastPage = '/index';
    res.render('index', { lastPage: req.session.lastPage } );
});
```

**index.ejs**
```html
<html>
...
<div id="ajax-page"></div>
...
<!-- javascript imports -->
</html>
```

**navigation.js**
```javascript
$.get('/'+page)
        .done(function(data){

                var template = ejs.compile(data);

                $('#ajax-page').html( template(data) );     // Add to div

                var lastPage = ejs.render('<% if (typeof lastPage !== "undefined") { %> <%= lastPage %> <% } else { %> lastPage <% } %>', data);
                // var lastPage = ejs.render('<% if (typeof lastPage !== "undefined") { %> <%= lastPage %> <% } else { %> lastPage <% } %>', {data:lastPage});
                console.log(lastPage);

        })

        .fail(function(){
            document.location.href="/";
        });
}
```

**Result**
`lastPage`. If it works, I should have '/index'.

**Comment by RyanZim** [comment]
I'm not quite understanding how navigation.js is related to the other files. Perhaps you could explain a bit more?

**Comment by flexbrane** [comment]
**navigation.js** is include in my ejs template. When an user click on an `<a href="my_page"></a>`, it call my fonction in **navigation.js** who get the page, and put it into the template.

**Comment by RyanZim** [comment]
OK, **how** are you including navigation.js (and jquery)? With a `<script>` tag or EJS `include()`?

**Comment by flexbrane** [comment]
That is the problem, indeed!

I just try to put my whole code in the bottom of my ejs template, and It is working .. I have used `<script src="../XXX"></script>`.

How can I include them ?

**Comment by RyanZim** [comment]
Scripts included with EJS `include()` do not have access to the DOM, since they are run server-side. Scripts included with `<script>` are run client(browser)-side, so they do not have direct access to EJS locals.

I'm not sure exactly what you are trying to accomplish. Are you trying to load the contents of your page with ajax on the client-side? I think I can help you if I understand what you're trying to do.

**Comment by flexbrane** [comment]
Yes, sorry I have not explain correctly.

First, `index.ejs` is my template page. I have include all my css (`<link href="../css/toast.css" type="text/css" rel="stylesheet" media="screen,projection"/>`) and my javascript (`<script src="../js/ejs.min.js"></script>`) files.
In it, there is a div used to append html code.
In one javascript file, a function get my home page (`home.ejs`) as AJAX request and append all html compiled to the div from `index.ejs`.

That's all.

When the user click on my sidenav, the same function is called, with the requested page as argument. The function get this new page, and replace the html content previously added, by this new html content. Etc, etc.

When this function is getting a response from my expressJS server, it get also an argument sending by ExpressJS. This argument is stored in a javascript variable (client side) in order to print messages for exemple.

If I paste my javascript (client side) code in `index.ejs`, the function can get the variable `lastPage` sended by ExpressJS with the html content. But if I create a new javascript file, which I include in `index.ejs` with `<script src="../js/xxx.js`, it's doesn't working anymore.

**Comment by RyanZim** [comment]
OK, I think I understand. You are using EJS both client- and server-side. When you pass a variable via `res.render()`, that variable is available to any js inside the EJS tags (i.e. `<%`). When EJS finishes compiling your template, it sends it to the browser as text; without passing its variables along. Therefore, any js included with `<script>` tags cannot access your server-side declared variables.

If you need to access some variables from EJS in a client-side script you will have to pass them manually. Here is an example:

**index.ejs**
```
<html>
...
<div id="ajax-page"></div>
...
<script>
  var lastpage=<%= lastpage %>;
</script>

<script src="path/to/jquery.js"></script>
<script src="navigation.js"></script>
</html>
```

If you leave routes.js unchanged, the browser will receive this HTML:
```
<html>
...
<div id="ajax-page"></div>
...
<script>
  var lastpage='/index';
</script>

<script src="path/to/jquery.js"></script>
<script src="navigation.js"></script>
</html>
```
The browser can then execute this client-side code.

I hope this is clear enough for you.

**Comment by flexbrane** [comment]
# Problem
My template page is never refreshed:

**index.ejs** will be compiled one time only, never refreshed on the client's browser.
```html
<html>
...
<div id="ajax-page"></div>
...
<script>
  var lastpage=<%= lastpage %>; // The first time, no problem.
</script>

<script src="path/to/jquery.js"></script>
<script src="navigation.js"></script>
</html>
```

**navigation.js** will get all new page and put them into `#ajax-page`.
```javascript
$.get('/'+page)
done(function(data){
                // Will compile the html code
                var template = ejs.compile(data);

                // Add the ejs compiled code (in html) to the div
                $('#ajax-page').html( template(data) );

                // Now we have compiled the html content, we try to get the variable sended by the server (expressjs)
                var lastPage = ejs.render('<% if (typeof lastPage !== "undefined") { %> <%= lastPage %> <% } else { %><% } %>', data);
                
                // Print the arg.
                console.log("Last page is "+lastPage);
});
```

## So ?
With what you explain to me, I understand that I correctly get the variable (and it's working in certain case).

If my javascript code (just above) is in `navigation.js` and included into `index.ejs`, I cannot get the argument (it is no working). But if I paste the code from `navigation.js` into `index.ejs`, **the same** code is working.
So the problem might be the javascript include in `index.ejs`.

**Comment by flexbrane** [comment]
No, I am wrong, it's not working. Just one time indeed.

**Comment by flexbrane** [comment]
So, my var must be included in all new ejs content sending by my server to update it ?

**Comment by RyanZim** [comment]
> index.ejs will be compiled one time only, never refreshed on the client's browser.

That is correct.

> If my javascript code (just above) is in `navigation.js` and included into `index.ejs`

How are you including it?

Please post the **full contents** of index.ejs.

---

I'm not sure what you mean by:

> So, my var must be included in all new ejs content sending by my server to update it ?

**Comment by flexbrane** [comment]
> So, my var must be included in all new ejs content sending by my server to update it ?

I just don't understand how to update my variable in `navigation.js` with new values sending by expressJS..

## index.ejs

```html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Accueil</title>

    <!-- CSS  -->
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
    <link href="../css/material-icons.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/loader.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/sideNav.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/footer.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/styles.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="../css/toast.css" type="text/css" rel="stylesheet" media="screen,projection"/>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- <script>if (!window.jQuery) { document.write('<script src="../js/jquery-2.1.1.min.js"><\script>'); } -->
</head>

<body>
    <header>
        <% include includes/navbar.ejs %>
    </header>
    <% include includes/navbarTop.ejs %>

    <% include includes/loader.ejs %>

    <main>
        <div id="ajax-page"></div>
    </main>

        <% include includes/footer.ejs %>

        <!--  Scripts-->
        <script src="../js/materialize/bin/materialize.min.js"></script>
        <script src="../js/ejs.min.js"></script>
        <script src="../js/navigation.js"/></script>


        <script src="../js/init.js"></script>

</body>
</html>
```

## Navigation.js

```javascript

// Get html content
function getData(page) {

    $.get('/'+page)
        .done(function(data){

                var template = ejs.compile(data);

                $('#ajax-page').html( template(data) );     // Compilation du fichier ejs  et  Ajout à la page

                var lastPage = ejs.render('<% if (typeof lastPage !== "undefined") { %> <%= lastPage %> <% } else { %><% } %>', data);
 
                console.log("Last Page is "+lastPage);
        })

        .fail(function(){
            document.location.href="/";
        });
}



    //- Menu
    $('#accueil').click(function(){
        getData('accueil');
        document.title = "Accueil";
    });
    $('#clients').click(function(){
        getData('clients');
        document.title = "Clients";
    });
    $('#materiel').click(function(){
        getData('materiel');
        document.title = "Matériel";
    });
    $('#parametres').click(function(){
        getData('parametres');
        document.title = "Paramètres";
    });
});

```

## Routes.js (exemple)

```javascript
router.get('/', function(req, res, next) {
    req.session.lastPage = '/home';
    res.render('index', {
        lastPage: req.session.lastPage,
        message: req.session.message
    });
});

router.get('/clients', function(req, res, next) {
    req.session.lastPage = '/clients';
    res.render('clients', {
        lastPage: req.session.lastPage,
        message: req.session.message
    });
});

```

**Comment by RyanZim** [comment]
I'm not understanding exactly what you're doing. In routes.js, you are using `res.render`. This would compile the EJS template. However, you are doing `ejs.compile(data)` in navigation.js as well.

What is the contents of clients.ejs?

**Comment by flexbrane** [comment]
index.ejs is a full html page with `<html></html>` tags. Other ejs page are juste part of html content in order to be placed in `index.html` which is opened in the browser of the client.

It's almost like AngularJS, all ressources are gets by the client the first time he went to the site. After that, only html content is load with ajax requests.
I do the same thing here.

![fonctionnement_site](https://cloud.githubusercontent.com/assets/14235706/16384077/f52f3c02-3c87-11e6-9fa5-37eef436676d.jpg)

**Comment by RyanZim** [comment]
> Other ejs page are just part of html content

Do those pages contain EJS tags (`<%`) or just HTML?

**Comment by flexbrane** [comment]
Only the static menu (ejs included in ìndex.ejs`, the template.

**Comment by RyanZim** [comment]
OK, I'm not understanding why you're using EJS on the client-side. Are you just trying to pass variables from ExpressJS to navigation.js?

**Comment by flexbrane** [comment]
Mostly. Is there another way ? Ooh.. I think I can only use html page with express and `{{ var }}`? :_s

**Comment by flexbrane** [comment]
It was also to include html files that  I use ejs.

**Comment by RyanZim** [comment]
> Mostly

EJS won't help you much with that. It will be helpful for rendering `index.ejs`.

As far as passing variables from ExpressJS to navigation.js; I personally would do something like: 
```
router.get('/clients', function(req, res, next) {
    var response={};
    response.lastPage = '/clients';
    fs.readFile('NameOfFile', function(err, contents){
        // Error Handling
        response.content=contents;
        res.json(response);
    )};
});
```

And then parse the JSON on the client side and do `$('#ajax-page').html(response.contents);`.

Perhaps there is a better way, I never learned ExpressJS very well.

You might want to post a topic on http://stackoverflow.com for more ideas and help.
