### ISSUE TITLE
compile with opt {_with: false, ...}

### ISSUE THREAD

**Issue by chenzl25** [mde/ejs#187]
When we compile with opt {_with: false, ...}, I want to ask whether the only way can we pass the data to the compiled function is context? And variables in the .ejs file should use `<%= this.variable` %>?

**Comment by RyanZim** [comment]
@chenzl25 You can pass the data as usual, you will just have to access it as `<%= locals.variable %>`. You can change `locals` to something else using the `localsName` option.
