### ISSUE TITLE
include performances

### ISSUE THREAD

**Issue by fchengpc** [mde/ejs#193]
This is not an issue, but I want post here so I would get some advice from the people closest to the project. My  question >>> Will the large amount of include statement, impact the performance of the page rendering?

Here is my example:
   One of my team member are thinking abt breaking the page down to 'Lego level' and use many of include statement to compose the page. eg a button has its own template, a search icon has its own template... 

  One would assume there will be some impact since every include require the template engine to look up the file path and get the template. But can anyone tell me the impact by number?

**Comment by RyanZim** [comment]
I'm not sure of exact numbers, but if you use `cache: true` in the options it should perform pretty good.

**Comment by RyanZim** [comment]
Here are some figures for rendering a template with 6 include statements. I ran each test 50 times.

# Without cache:
```
1: 6.493ms
2: 2.858ms
3: 1.961ms
4: 7.240ms
5: 1.431ms
6: 1.236ms
7: 0.587ms
8: 0.822ms
9: 1.940ms
10: 13.716ms
11: 0.861ms
12: 0.570ms
13: 0.861ms
14: 0.706ms
15: 0.798ms
16: 0.676ms
17: 1.000ms
18: 1.295ms
19: 19.055ms
20: 8.611ms
21: 0.693ms
22: 7.593ms
23: 2.223ms
24: 0.840ms
25: 1.377ms
26: 11.929ms
27: 0.806ms
28: 3.115ms
29: 0.590ms
30: 0.508ms
31: 0.544ms
32: 0.523ms
33: 1.207ms
34: 1.405ms
35: 0.566ms
36: 0.500ms
37: 0.512ms
38: 0.520ms
39: 0.511ms
40: 0.600ms
41: 0.585ms
42: 0.535ms
43: 0.605ms
44: 18.425ms
45: 0.634ms
46: 0.622ms
47: 6.994ms
48: 1.469ms
49: 0.766ms
50: 2.467ms
```
# With Cache:
```
1: 14.958ms
2: 0.207ms
3: 0.146ms
4: 8.332ms
5: 0.113ms
6: 0.090ms
7: 0.112ms
8: 0.095ms
9: 0.432ms
10: 0.956ms
11: 0.170ms
12: 1.032ms
13: 0.116ms
14: 0.090ms
15: 0.074ms
16: 0.077ms
17: 0.073ms
18: 0.073ms
19: 1.392ms
20: 0.843ms
21: 0.089ms
22: 13.009ms
23: 1.282ms
24: 0.081ms
25: 0.092ms
26: 0.081ms
27: 0.078ms
28: 0.071ms
29: 0.083ms
30: 0.073ms
31: 0.149ms
32: 0.078ms
33: 0.834ms
34: 0.115ms
35: 0.088ms
36: 0.076ms
37: 0.238ms
38: 0.080ms
39: 0.086ms
40: 0.100ms
41: 0.091ms
42: 0.113ms
43: 0.082ms
44: 8.194ms
45: 0.130ms
46: 0.086ms
47: 0.097ms
48: 0.080ms
49: 0.178ms
50: 0.101ms
```
If you have more questions, feel free to ask them here, but closing this for now.

**Comment by fchengpc** [comment]
thxs @RyanZim. Can you pls run with abt 15 includes? and post the result here too?

**Comment by fchengpc** [comment]
But either way, performances is better if we can avoid include if possible right?

**Comment by RyanZim** [comment]
> But either way, performances is better if we can avoid include if possible right?

It would run a hair faster, but with the cache turned on, I wouldn't worry too much.

**Comment by RyanZim** [comment]
With cache:
```
1: 10.049ms
2: 2.500ms
3: 0.310ms
4: 1.111ms
5: 0.200ms
6: 0.184ms
7: 0.202ms
8: 0.196ms
9: 4.599ms
10: 0.734ms
11: 0.547ms
12: 0.219ms
13: 0.333ms
14: 0.417ms
15: 1.177ms
16: 0.367ms
17: 0.329ms
18: 2.927ms
19: 0.617ms
20: 0.274ms
21: 1.451ms
22: 0.253ms
23: 0.292ms
24: 0.266ms
25: 2.498ms
26: 0.324ms
27: 3.738ms
28: 0.321ms
29: 0.275ms
30: 0.318ms
31: 0.416ms
32: 0.347ms
33: 1.444ms
34: 0.338ms
35: 1.802ms
36: 1.492ms
37: 0.277ms
38: 0.240ms
39: 0.238ms
40: 0.287ms
41: 0.241ms
42: 0.276ms
43: 0.380ms
44: 3.792ms
45: 9.100ms
46: 0.235ms
47: 0.170ms
48: 0.180ms
49: 0.849ms
50: 0.180ms
```
Without:
```
1: 9.129ms
2: 8.396ms
3: 2.156ms
4: 7.504ms
5: 6.599ms
6: 2.240ms
7: 1.990ms
8: 7.661ms
9: 15.955ms
10: 6.192ms
11: 1.794ms
12: 1.182ms
13: 1.255ms
14: 1.129ms
15: 0.763ms
16: 0.881ms
17: 1.805ms
18: 13.462ms
19: 1.650ms
20: 1.880ms
21: 2.882ms
22: 1.753ms
23: 2.749ms
24: 1.081ms
25: 176.117ms
26: 2.995ms
27: 15.412ms
28: 12.090ms
29: 3.131ms
30: 1.295ms
31: 4.735ms
32: 4.957ms
33: 4.500ms
34: 1.231ms
35: 5.637ms
36: 2.733ms
37: 6.022ms
38: 1.164ms
39: 1.251ms
40: 2.801ms
41: 0.976ms
42: 4.191ms
43: 1.355ms
44: 13.694ms
45: 1.400ms
46: 1.130ms
47: 5.832ms
48: 1.599ms
49: 1.868ms
50: 1.482ms
```

**Comment by RyanZim** [comment]
Keep in mind, benchmarks are not :100: accurate, rerunning these tests could sometimes result in different figures.

**Comment by fchengpc** [comment]
yes i know. this also doesnt account for data which need to be parse and render as well. Thank you very much @RyanZim

**Comment by fchengpc** [comment]
sry 1 last fav to ask, can you also post the some base line data without using include?

**Comment by RyanZim** [comment]
> can you also post the some base line data without using include

That would be quite variable, depending on the size and amount of scripting in the template.

**Comment by fchengpc** [comment]
got you. thank you very much for the help.

**Comment by Edwardzyc** [comment]
If caching gives better performance in general - shouldn't caching always be turned on?(Or make it a flag?)

**Comment by RyanZim** [comment]
@Edwardzyc Caching by default would be: 1. a breaking change and 2. is unexpected behavior IMO. When I call `renderFile`, I expect EJS to actually render the file, not render the cached (and possibly outdated) version of the file.

Just locking this to prevent further noise.
