### ISSUE TITLE
include API force EJS template path as a root path

### ISSUE THREAD

**Issue by m-pawelczyk** [mde/ejs#196]
I have discovered problem with EJS API. It looks like EJS API changed between versions 2.4.1 and 2.5.1. In version 2.5.1 function include always add EJS template path to given path value. In version 2.4.1 behavior was diffferent.

I use `express` and `views` path is set as a argument:

`var express = require('express');`

`app = express();`

`app.set('views', path.join(__dirname, '/../views'));`
`app.set('view engine', 'ejs');`

Then I use function render:

`var renderObj = var renderObj = {`
`        mytemplate: relative path OR absolute path // examples of this values is shown below` 
`        // (...)`
`};`
`res.render('layout-main', renderObj);`

Let's look hot it works now (2.5.1):

1) relative path - WORKS

`// mytemplate = 1/template.ejs`

2) absolute path - DOESN'T WORK

`// mytemplate = /2/template.ejs`
`error: Error: /opt/myapp/frontend/lib/views/layout-main.ejs:129`
	
` >> 129|                     <%- include(mytemplate) %> `

`ENOENT: no such file or directory, open '/opt/myapp/frontend/lib/views/2/template.ejs'`

**Comment by RyanZim** [comment]
I suspect this has something to do with https://github.com/mde/ejs/pull/169.

A few questions:

1. How did it work in 2.4.1 when you passed an absolute path to `include()`?
1. Where is `/2/template.ejs` located?

**Comment by m-pawelczyk** [comment]
1) `include()` doesn't add additional value to absolute path. It works like:
 `include("/2/template.ejs")` -> include template `/2/template.ejs`

2) I have made this path shorter for easier reading. `/2/template.ejs` is used as normal template path.  

Another example is `/opt/myapp/frontend/lib/views/2/template.ejs` and then error on 2.5.1 will be: `ENOENT: no such file or directory, open '/opt/myapp/frontend/lib/views/opt/myapp/frontend/lib/views/2/template.ejs'`

**Comment by RyanZim** [comment]
OK, thanks, will investigate.

**Comment by RyanZim** [comment]
I think this bug is caused by https://github.com/mde/ejs/blob/master/lib/ejs.js#L362-L365. This should have been removed https://github.com/mde/ejs/pull/169#discussion_r65226942, but wasn't. My bad, should have noticed this.

Will try to make a patch, am currently halfway through migrating computers :frowning:.

CC: @mde @TimothyGu

**Comment by RyanZim** [comment]
@m-pawelczyk Try using the fix-196 branch: https://github.com/mde/ejs/tree/fix-196. Uninstall EJS and reinstall it using this branch by running: `npm install mde/ejs#fix-196`. See if that fixes your issue and report back. Thanks!

**Comment by cnwhy** [comment]
@m-pawelczyk 
2.4.1 to 2.5.1 intermediate versions;
You should pay attention to this update:  
> Allow setting project root for includes  

In express, if only views a directory, 
For ease of use, it will automatically set the project root path:
ejs `root` = express ` views`

So, I do not think this is a bug. 
You should remove special treatment for doing the absolute path, using the version v2.5.1.

**Comment by RyanZim** [comment]
> I do not think this is a bug.

@cnwhy This is a bug. EJS adheres to semver, but this is a breaking change and was not versioned as such.

**Comment by m-pawelczyk** [comment]
@RyanZim thank you very much for fast investigate. Your fix (https://github.com/mde/ejs/tree/fix-196) works OK for me. Thanks.

@cnwhy Fortunately, I have found it on my CD environment.

**Comment by RyanZim** [comment]
@m-pawelczyk I merged the fix, just need to wait for @mde to push a release; I don't have npm publish rights.

You will need to run `npm uninstall mde/ejs#fix-196 && npm install ejs` after this fix is included in a release.

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde Can you push a release?
