### ISSUE TITLE
What is [ client and context ] function in options?

### ISSUE THREAD

**Issue by code1031** [mde/ejs#197]

**Comment by RyanZim** [comment]
With `context` you can pass an object that will be used as `this` in the EJS template.

Example:
```js
var cntxt={person: 'John'};
ejs.render('Hello <%= this.person %>', data, {context: cntxt});
// => Hello John
```

---

`client` only applies to `compile()`. When used, the function returned by `compile()` does not depend on EJS to render. In most cases you would `.toString()` this function and write it to a JS file. You could then include the JS file on your page and render the template without including EJS. The function also has a little different API, you can read the JSDocs here: https://ryanzim.github.io/ejs-api/global.html#ClientFunction.

(BTW, I don't always keep those hosted JSDocs updated like I should, for the full public API documentation, clone the repository and run `npm run doc`. This will run JSDoc with the proper options and output the documentation to `out/`.)

**Comment by rauschma** [comment]
Thanks for the explanation, @RyanZim!

Currently `context` is described in [the docs](https://ejs.co/#docs) as:

> Function execution context

Given that “execution context” has a specific meaning (that doesn’t apply here), it may make sense to change the docs – e.g. to:

> Value for `this` that is passed to the EJS template function.

As an aside: In the ECMAScript spec, such parameters are called `thisArg` – which I like better than `context` (but renaming the option isn’t worth the trouble).

**Comment by mde** [comment]
Yes, unfortunate wording, esp. since the MDN docs for `this` literally start with the sentence, "The this keyword refers to the context where a piece of code, such as a function's body, is supposed to run." I'd happily merge a PR that improves the docs, and would even be willing to update the name of the parameter, as long as we leave a shim for backward compat.
