### ISSUE TITLE
Module adds a global "includeSource"

### ISSUE THREAD

**Issue by dougwilson** [mde/ejs#2]
Regression from commit https://github.com/mde/ejs/commit/63146d0b6371595d1b235980436425f98abee071 causes `includeSource` property to be added to the global object.

**Comment by mde** [comment]
Fixed in cb7629b07ac7d94f9befb3df3e386df4715f6a0b and pushed to NPM, v2.0.4.

**Comment by dougwilson** [comment]
Thanks!

**Comment by mde** [comment]
No, thank you!
