### ISSUE TITLE
Different syntax for <% %> ?

### ISSUE THREAD

**Issue by rauschma** [mde/ejs#200]
I absolutely love the simplicity of EJS. But the `<% %>` delimiters are too verbose for my taste:

```
<ul>
<% for(var i=0; i<supplies.length; i++) {%>
   <li><%= supplies[i] %></li>
<% } %>
</ul>
```

Can EJS be configured so that a single character at the beginning of a line triggers the `<% %>` mode? For example:

```
<ul>
# for(var i=0; i<supplies.length; i++) {
   <li><%= supplies[i] %></li>
# }
</ul>
```

Additionally, I’d want every line that starts with a `#` to be in whitespace trim mode (`<%_ _%>`).

**Comment by RyanZim** [comment]
> Can EJS be configured so that a single character at the beginning of a line triggers the <% %> mode? 

No, EJS only supports custom delimiters like `<?` & `?>`: https://github.com/mde/ejs#custom-delimiters

There is an open feature request for substituting `<` and `>` with something else https://github.com/mde/ejs/issues/115. PR welcome!

Implementing what you are describing would be impossible with the current tokenizer IIRC.

**Comment by rauschma** [comment]
Wouldn’t a solution have to be more radical than that, though? It wouldn’t just be a different way of bracketing, it’s a completely new approach.

I think I’ll use a work-around for now:

```
template = template.replace(/^#(.*)$/mg, '<%_$1_%>');
```

**Comment by RyanZim** [comment]
> Wouldn’t a solution have to be more radical than that, though?

Yeah:

> Implementing what you are describing would be impossible with the current tokenizer IIRC.
