### ISSUE TITLE
Mocha v3.1.0 finding global leak

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#206]
Attn: @mde @TimothyGu 

This morning I merged https://github.com/mde/ejs/pull/203. The build PR build was passing. This should not have affected anything. Changeset: https://github.com/mde/ejs/compare/5355a2cf4fbe...6c2663e347dd.

I received an email notifying me that the Travis Build had failed on master https://travis-ci.org/mde/ejs/builds/163080741. The log says:

```
87 passing (185ms)

  1 failing

  1) -%> stack traces work:

     Error: global leak detected: data
```

I cannot reproduce locally. I tried restarting the build just in case, it did not make a difference. The previous build worked fine: https://travis-ci.org/mde/ejs/builds/161735725.

I created a new branch `test` off of master and ran `git reset --hard HEAD~` and pushed it to `origin` to see if that Travis build will pass. It doesn't: https://travis-ci.org/mde/ejs/builds/163120705. This is the exact same commit as the passing https://travis-ci.org/mde/ejs/builds/161735725!

~~This seems to be a Travis bug.~~ Advice?

**Comment by RyanZim** [comment]
This isn't a Travis bug, Travis is pulling in the latest version of everything, I had a stale `node_modules` folder. I suspect this is a bug in mocha or upstream, will try to check.

**Comment by RyanZim** [comment]
Found the change: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#bug-bug-fix

> Fix case in which variables beginning with lowercase "D" may not have been reported properly as global leaks

Our bug, apparently.

I don't have time to track this leak down today, sorry.

**Comment by mde** [comment]
Oh, charming. Looks like it's time for an npm-shrinkwrap.json. Let's just pin this to a working version of Mocha.

**Comment by RyanZim** [comment]
> Looks like it's time for an npm-shrinkwrap.json

It's just a devDependency, I would sooner use greenkeeper.io to alert us of stuff like this.

I'll pin back the mocha version until I find the root of the issue.

**Comment by RyanZim** [comment]
Pinned https://github.com/mde/ejs/commit/e36b7595edd6a54f2b3f8b4fa5e8ee199c0564e9

**Comment by mde** [comment]
Excellent, thank you for doing this!

**Comment by RyanZim** [comment]
@mde @TimothyGu I've gone through all the code, looking at every instance of `data`, and I can't find where the global leak is coming from. HELP! :scream_cat:

**Comment by RyanZim** [comment]
@mde @TimothyGu Did a little more debugging, started sticking `console.log(global.data)` in the code and I finally found it!

The test causing the issue is https://github.com/mde/ejs/blob/master/test/ejs.js#L544-L555:
```
test('stack traces work', function () {
    try {
      ejs.render(fixture('no.newlines.error.ejs'));
    }
    catch (e) {
      if (e.message.indexOf('>> 4| <%= qdata %>') > -1) {
        return;
      }
      throw e;
    }
    throw new Error('Expected ReferenceError');
});
```

This test renders https://github.com/mde/ejs/blob/master/test/fixtures/no.newlines.error.ejs:
```
AAA
<% data = "test"; -%>
BBB
<%= qdata %>
CCC
```

That line: `<% data = "test"; -%>`, leaks `data` into the global scope (no `var` declaration).

@TimothyGu, the `blame` indicates you wrote that test. What was the intended purpose of this code? Can it be refactored to avoid polluting the global scope? How about this:
```
AAA
<% var data = "test"; -%>
BBB
<%= qdata %>
CCC
```
Would this break the intended functionality of the test? It seems the point was to test if EJS can keep accurate line numbers when the `SyntaxError` is encountered on line 4

---

Another conversation for another day: Is there any way that EJS can throw an error when a template creates such a global?

**Comment by mde** [comment]
No, EJS can't throw an error on globals. Globals are a bad practice, but they are valid JavaScript.

**Comment by RyanZim** [comment]
That's what I thought.

**Comment by TimothyGu** [comment]
@RyanZim I think so. The test came straight from tj/ejs#196.

**Comment by RyanZim** [comment]
OK, I will make a PR editing the ejs file.

**Comment by gaastonsr** [comment]
@RyanZim 

> Did a little more debugging, started sticking console.log(global.data) in the code and I finally found it!

This is genius! thank you!
