### ISSUE TITLE
Remove html comments and unnecessary whitespaces when rendering in express

### ISSUE THREAD

**Issue by lel1234** [mde/ejs#209]
Everything is in the title, how do I minify the resulting template, so I can keep the comments and indentation when I'm developing ?

I use EJS with NodeJS/Express like this : 

res.render('myEJSpage.ejs', {someParams: theParams});

Thanks !

**Comment by RyanZim** [comment]
The `rmWhitespace` option will remove leading and trailing whitespace (https://github.com/mde/ejs#options).

If you want more minification, you will have to hook up a minifier after EJS; however, I encourage you to see if this is really beneficial. Some minifiers are quite slow, and the reduced file size and transfer time might be offset by a slow minifier.

If you decide to add a minifier, I can't tell you how to do that, I don't use express. @TimothyGu or @mde would most likely know.

**Comment by lel1234** [comment]
I guess I will just change html comments with EJS ones

**Comment by RyanZim** [comment]
Yeah, if your comments relate to EJS, that is a good idea.
