### ISSUE TITLE
Can't render template client-side

### ISSUE THREAD

**Issue by MaximeArbisa** [mde/ejs#210]
Hey guys;

I'm facing a problem when rendering a template client-side on an AJAX call.
On my route, I render a normal view 'artists.ejs', and a template 'artist.ejs' that will be filled afterwards on client-side on AJAX call (when a user is clicking on a button).

I want the template to be compiled on the server-side, through:
```
router.get('/artists', function (req, res) { // On my route
       fs.readFile('path/to/file', 'utf-8', function(err, file) { // Convert file to string
              var template = ejs.compile(file); // Compile file
              res.render('artists.ejs', {template: template}); // Render normal page + compiled template
      });
});
```
template returns a function as expected, and when I fill it with data on the server template(data), it works perfectly. It's not working on the client-side though.
So in the ejs, I'm retrieving the function 'template' in a script:

```
<script>
       var template = <%= template %>
`</script>
```
On on the client, I'm making an AJAX call to get the data:
```
$.get('artists/name_artist', function(data) {
          var html = template(data); // This was working on server-side
          $('#`artist-page').html(html);
}
```

The template should be compiled so that we just have to feed it with the data, but when calling template(data). It says: 'Uncaught ReferenceError: fn is not defined'. After changing 'template' to 'fn' (in case it is hard coded), I've got a new error: 'Uncaught ReferenceError: opts is not defined.'. I'm trying to give null to fn(data) as a second input but it is still not working. Do you know what could be those options ? I've seen everywhere and nothing talks about this, everybody seem to use template(data) just fine.
If you could give me a hand, it would be awesome, it's been three days that I'm fully on it, and can't get away with it :/

Thanks !

**Comment by RyanZim** [comment]
@MaximeArbisa You need to use the `client` option during server-side compilation.

> - `client` When `true`, compiles a function that can be rendered in the browser without needing to load the EJS Runtime 

https://github.com/mde/ejs#options

You will need to do something like this:
```
var template = ejs.compile(file, {client: true}).toString();
```
- The `{client: true}` compiles it in a way that it does not require EJS to render it.
- When compiling for the client, EJS returns an actual function, not a string, so you need to `.toString()` it manually. This is sort of weird behavior, we plan on returning a string in the next major release.

**Comment by webdiscus** [comment]
@RyanZim @mde,

> `var template = ejs.compile(file, {client: true}).toString();`
> we plan on returning a string function in the next major release.

7 years later...

Is this still planned? When will it be implemented? 
It is very very needed feature.
For example, on server side the EJS template can be compiled into the template function as a string and saved as a file for usage on client side. 
Currently I need to use the `.toString()` function, but it is not optimal. The source code of the template function is already generated in [`src` variable](https://github.com/mde/ejs/blob/29b076cdbbf3eb1b4323b33299ab6d79391b2c33/lib/ejs.js#L650) and [evaluated](https://github.com/mde/ejs/blob/29b076cdbbf3eb1b4323b33299ab6d79391b2c33/lib/ejs.js#L673C71-L673C74)  into callable function.

It would be nice to have a new method to generate source code of the template function, e.g. `compileSource()`.

Thank you!
