### ISSUE TITLE
Syntax error when <%- %> or <%= %> includes Javascript comment on last line

### ISSUE THREAD

**Issue by sgress454** [mde/ejs#211]
To reproduce, try the following:

```
ejs.render('<%-\n// a comment\nname\n// another comment %>', {name: '&nbsp;<script>'})
```

or, in a template:

```
<%-
// a comment
name
// another comment
%>
```

The code will be wrapped up in `__append()`, but the closing parentheses will be placed at the end of the final comment (thus commenting it out), e.g.:

```
__append(
// a comment
name
// another comment)
```

**Comment by mde** [comment]
Fixed in 7eaba6ade1b11e0bb275f1eb63ba49071aca24dd, release to follow.
