### ISSUE TITLE
Does not support stringified script tags

### ISSUE THREAD

**Issue by terencechow** [mde/ejs#213]
I have this in my ejs file:

`<script> window.__data__ = <%- payload %> </script>`

And my payload is a valid json (validated with a json linter) similar to this form:

`{ "html": "...some stuff....<script src='//someurl.com/file.js'></script>"}`

Hence I expect `window.__data__` to equal some json. However it does not. And the produced index.html is malformed.

**Comment by RyanZim** [comment]
You can't have `</script>` inside a string anywhere in an inline script tag. This is invalid HTML:
```
<script>
  var myVar = {
    someKey: "<script src='//someurl.com/file.js'></script>",
  };
</script>
```

The HTML parser sees `</script>` and terminates the script right there.

The standard way to get around this limitation is to do something like this:
```html
<script>
  var myVar = {
    someKey: "<script src='//someurl.com/file.js'></sc" + "ript>",
  };
</script>
```

Of course, this is hard to do in your case. If you don't care about IE, you could use the `<template>` tag (http://caniuse.com/#feat=template) for this:

```
<template id="myTemplate"><%- payload %></template>
<script> window.__data__ = document.getElementById('myTemplate').innerHTML; </script>
```

That should get your payload attached to `window.__data__`. Hope this helps!
