### ISSUE TITLE
using css, background url wont showing.

### ISSUE THREAD

**Issue by arduino731** [mde/ejs#214]
The code was <div style="background:url("<%= state.image.image_state%>");">. When I running the broswer, I have decided to open the element insecpt on Google Chrome. 

```html
It said <div style="background:url(" http:="" imgur.com="" 81am2ux.jpg" ); ">
``` 
It seems do not friendly in CSS but it worked in html such as <img src="<%= here code %>" 

I m expected output is http://i.imgur.com/81AM2UX.jpg in CSS. 

noticed that the url is case sensitive.
 
Has anyone had the idea?

**Comment by RyanZim** [comment]
@arduino731 Try `<div style="background:url("<%- state.image.image_state%>");">`.

Can you verify the value of `state.image.image_state`?

**Comment by arduino731** [comment]
@RyanZim double quotes won't work, but the single quote and without the quote will work. hmm? thanks ! 
what i did is 

```
<div style="background:url('<%- state.image.image_state%>');">
```
like you did 💯
