### ISSUE TITLE
How to use ejs for ES2016

### ISSUE THREAD

**Issue by NoahDragon** [mde/ejs#215]
I'm using `new Set()` in ejs template, but got error said the Set is not defined. The Set is supported in ES6, is there a way to use it in ejs?

**Comment by RyanZim** [comment]
It works fine for me: https://runkit.com/57ebc041d4a27f140028fd78/582ddbef9cde3d0013427998.

If you're using hexo, I don't know if it works or not, hexo-renderer-ejs uses the old EJS v1.

**Comment by NoahDragon** [comment]
@RyanZim Thanks.
