### ISSUE TITLE
Caching views for a limited time only

### ISSUE THREAD

**Issue by mitomm** [mde/ejs#217]
As far as I understand, I can use `res.render(fileName, {"cache": true, "data" : data});` to cache a view, right?

However, since data may change on my views regularly, it doesn't make sense for me to cache the view for a long period of time. However, I guess that caching it for short periods of time could still improve the performance of my application (if I have a lot concurrent request). 

Is there any way I could make EJS cache the template/view for say 5 sec. and then render it once an cache it again for 5 seconds?

**Comment by RyanZim** [comment]
You will need to install https://www.npmjs.com/package/lru-cache for this.

    npm install --save lru-cache

Then in your code do:
```js
var LRU = require("lru-cache");
var ejs = require('ejs')
ejs.cache = new LRU({maxAge: 5 * 1000})
```
Not sure how this translates to express; @mde?

**Comment by mde** [comment]
Not too sure about caching directly in Express. In any case, iI wouldn't do this inside my app. I'd do caching with Squid, Haproxy, or even just Nginx.

**Comment by RyanZim** [comment]
OK, wasn't sure about that.

**Comment by RyanZim** [comment]
@mitomm Does this answer your question? If so, please close.

**Comment by mitomm** [comment]
yup, since I'm already using an NGINX reverse proxy, I guess caching with NGINX is the way to go.

Thanks for the quick help.
