### ISSUE TITLE
Automatic docs publishing

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#218]
@mde When you published the latest version, what happened with the automatic documentation push to gh-pages? I don't see the branch.

**Comment by mde** [comment]
I didn't have git-directory-deploy installed (and didn't notice it was a requirement). I will be doing another release soon, so it should update correctly then.

**Comment by RyanZim** [comment]
@mde It is listed in the devDeps, just run `npm i` and it should install automatically.

**Comment by RyanZim** [comment]
BTW, good catch on that `root` option.

**Comment by RyanZim** [comment]
@mde If you'd like, I can just run the `doc` task to update them now.

**Comment by mde** [comment]
Yes, I know how to install dependencies. :) I just hadn't noticed it had been added. I'll run the doc task now.

**Comment by mde** [comment]
Can you verify the gh-pages was correctly updated?

**Comment by RyanZim** [comment]
@mde Ain't seeing it; let me try.

BTW, is `gh-pages` listed when running `git branch`?

**Comment by mde** [comment]
No, it's not.

**Comment by RyanZim** [comment]
I ran `jake docPublish` manually, and it worked fine: http://mde.github.io/ejs/.

**Comment by RyanZim** [comment]
What was the output when you ran `jake publish`?

**Comment by mde** [comment]
It complained about git-directory-deploy not being installed.

**Comment by RyanZim** [comment]
Sorry, my comment above was incorrect, you need to run `jake docPublish` to update them on the server. `jake doc` just updates the local copy. `docPublish` runs `doc` first, that pushes to gh-pages.

**Comment by RyanZim** [comment]
Anyhow, it's working now; let me know if it chokes on the next release. If you're not sure if it worked; take a peek at https://github.com/mde/ejs/tree/gh-pages, and see when the latest commit was.

---

Do you want to hook up the gh-pages to `api.ejs.co` sometime? If we do that, we should link from ejs.co to there, and include a link to ejs.co from the JSDocs.

**Comment by mde** [comment]
Ah, I didn't look closely at the Jakefile to see what those tasks do. :)

Sure, let's hook up the API docs. How does GH Pages do domain aliasing?

**Comment by RyanZim** [comment]
Set `api.ejs.co` to CNAME `mde.github.io`.

I'll need to modify the Jakefile to insert a `CNAME` file just before publishing; PR coming.

The subdomain should then connect after the next release.

**Comment by RyanZim** [comment]
@mde BTW, **do not** set a wildcard record (`*.ejs.co`) pointing to gh-pages; that will allow anyone to publish a site on another subdomain.

**Comment by mde** [comment]
I only ever set a wildcard to the same as the www server, no worries. :)

**Comment by RyanZim** [comment]
@mde That's my point; never set a wildcard pointing to any of GitHub's servers.

> Danger: Do not use wildcard DNS records (e.g. *.example.com) with GitHub Pages! A wildcard DNS record will allow anyone to host a GitHub Pages site at one of your subdomains.

https://help.github.com/articles/setting-up-a-custom-subdomain/

**Comment by mde** [comment]
Yes, I was saying I'd never do that -- I would only ever make wildcard entry that points to the same IP address as the existing www or main web server.

**Comment by RyanZim** [comment]
Here's your PR, merge at will: #219.

**Comment by RyanZim** [comment]
@mde Can you set the CNAME record for `api.ejs.co`?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
I've set it up. Not sure how long it will take to propagate.

**Comment by mde** [comment]
<img width="982" alt="screen shot 2017-05-07 at 11 55 55 am" src="https://cloud.githubusercontent.com/assets/757/25784066/389573a4-331c-11e7-9ccf-826e812e2a40.png">

**Comment by RyanZim** [comment]
It works! http://api.ejs.co/

**Comment by mde** [comment]
Sweeeeeeeeet! Sorry this took so long.
