### ISSUE TITLE
custom localsName

### ISSUE THREAD

**Issue by izdesenko** [mde/ejs#225]
Hello, i'm working on my wrapper over ejs with some additional staff. It would be great if i could be able to redefine localsName variable. Is there any reason why it is not in _OPTS array (https://github.com/mde/ejs/blob/master/lib/ejs.js#L57)? Could you add it there?

if i pass custom localsName via 'view options' it being filtered out because of _OPTS.

**Comment by RyanZim** [comment]
Yep, that's a bug; someone just forgot to include it in the `_OPTS` array. PR welcome!

**Comment by mde** [comment]
No, this is not a bug. The `_OPTS` var is somewhat of a misnomer now. It's the list of property names that will be copied from the `data` param, in the legacy single-arg method signature. You can redefine `localsName` when you correctly pass `opts` separately from data. Allowing them to be passed directly along with data is a security hole that we had to close.

**Comment by RyanZim** [comment]
> Allowing them to be passed directly along with data is a security hole that we had to close.

I know passing data & opts is not recommended, but I'm not seeing what the security hole with `localsName` is.

**Comment by mde** [comment]
1. Using `localsName` can allow an attacker to cause errors and see debug messages.
2. Setting `localsName` to certain values (e.g., `try`) will cause EJS to crash.

**Comment by RyanZim** [comment]
@mde Gotcha, closing. @izdesenko You need to pass your data and options separately.

**Comment by izdesenko** [comment]
@mde, yep it works fine. Thank you.
