### ISSUE TITLE
Dynamic Include

### ISSUE THREAD

**Issue by pkumar01** [mde/ejs#227]
How can i have a dynamic include e.g.
<% include variable  %> should include index.ejs or about.ejs dynamically whatever got passed in variable.

**Comment by mde** [comment]
That syntax is the old (deprecated) preprocessor directive. Use the modern `include` function syntax for this:

```javascript
<% include(someFileName); %>
```

**Comment by pkumar01** [comment]
could you please share some example

**Comment by RyanZim** [comment]
**main.ejs:**
```
<%- include(variable); %>
```

Note that using `<%-` will not HTML-escape the contents of your included file. In most cases that is what you want, but use `<%=` to HTML-escape the contents if they are untrusted.

**about.ejs:**
```
Hello World!
```

**index.js:**
```js
var ejs = require('ejs');
ejs.renderFile('main.ejs', {
  variable: 'about.ejs',
}, function (err, txt) {
  if (err) console.error(err);
  console.log(txt);
  // -> Hello World!
});
```

---

@mde Small typo in your code, you need to use an output tag with the dynamic include, not just `<%`.

**Comment by pkumar01** [comment]
was doing everything right except spacing i had to do <%- include(variable); %> but was doing <%- include(variable); %> and that took my head off. but anyways thanks guy for support.

**Comment by snolflake** [comment]
@RyanZim Do you if it is this supported for "runtime" variables?

I'm trying to do the following:
```
<% for (var pageName in pages) { %>
    <div id="<%= pageName %>-container" class="page">
        <%- include('/src/templates/pages/' + pageName + '.ejs'); %>
    </div>
<% } %>
```

I tried a few other variations too but all I get is something like:
```
Module build failed: Error: ENOENT: no such file or directory, open '(template  );.ejs'
```
FYI this is being compiled from a webpack loader, but from [what I've seen](https://github.com/bazilio91/ejs-compiled-loader/blob/2.x/index.js) there's nothing on that layer that could cause this.

**Comment by RyanZim** [comment]
@snolflake Runtime variables should work fine

Try this to debug:
```
<% var template = '/src/templates/pages/' + pageName + '.ejs'; %>
<%= template %>
```
make sure the correct file name is printed.
