### ISSUE TITLE
ejs in a headless environment

### ISSUE THREAD

**Issue by CarbonMan** [mde/ejs#228]
I am using ejs in Jint a .Net JS environment. The following code does not load ejs although there is no error during the eval(..)
I have defined a window object. 
console.log is a mock replacement for the browser version.
host.getInputFileContents(..) returns a string of the file from the host.
After the eval ejs is undefined.

 if (typeof ejs === "undefined") {
    var js = host.getInputFileContents("wwwpub\\js\\ejs.js");
    eval(js);
    if (typeof ejs == "undefined"){
        console.log("ejs did not load");
    }
}

**Comment by RyanZim** [comment]
@CarbonMan Just to confirm, was the file `wwwpub\js\ejs.js` downloaded from the releases page (not from `lib/ejs.js` in the repository)? If you are unsure, you can download the correct file at https://github.com/mde/ejs/releases/download/v2.5.5/ejs.js.

Are there any error messages?

**Comment by CarbonMan** [comment]
@RyanZim Yes it was, but I'll try again to make sure.
There are no error messages.

**Comment by RyanZim** [comment]
@CarbonMan I don't have much of an idea then. Your code doesn't happen to be in strict mode?

**Comment by RyanZim** [comment]
Another thing, try this:
```js
if (typeof ejs === "undefined") {
  var js = host.getInputFileContents("wwwpub\js\ejs.js");
  console.log(js);
  eval(js);
  if (typeof ejs == "undefined"){
  console.log("ejs did not load");
  }
}
```
You should get a log of the contents of the file. Just trying to isolate the issue.

**Comment by CarbonMan** [comment]
Oh God, I've realized it would have to be referenced as window.ejs sorry for wasting your time.

**Comment by RyanZim** [comment]
No prob
