### ISSUE TITLE
Client mode virtually unusable in real world

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#23]
There are two big design mistakes (IMO) in the implementation of the client mode:

1. `.compile()` returns a function, not a string
   - I cannot think of any occasion that returning a client function in function form would ever be helpful. All tests for client mode uses a `.toString()`.
   - Jade returns a string.
2. The current API does not allow changing the function name of the output function, making it impossible to have more than one functions in a webpage without manual `var thisIsTheNameIWant = eval(str)`
   - This is extremely awkward for users who want to embed their function string in a HTML `data-` attribute.
   - Jade fixes this making `options.name` represent the name of the function.
   - Currently the output function is called `anonymous()`, which is plain stupid (Jade uses `template()`).

Both of these points cannot be done without breaking backward compat.

**Comment by mde** [comment]
I don't have strong feelings about the client mode -- I just ported it over as closely as I could. It is used in the "require templates directly" feature. I don't care if we break backward compat or not, but if we do, that will mean major version bump. I'm not keen on doing that right away.

**Comment by TimothyGu** [comment]
@mde said:
> I don't care if we break backward compat or not, but if we do, that will mean major version bump. I'm not keen on doing that right away.

Yes that's my main concern right now. I have added a 3.0 milestone, and if this idea is acceptable I'll go ahead and implement it in develop branch.

**Comment by mde** [comment]
Yes, let's do it in the development branch.

**Comment by TimothyGu** [comment]
I have committed d881cb8 which fixes these issues in development branch, and thus I'll close this.
