### ISSUE TITLE
Slurping previous new-lines 

### ISSUE THREAD

**Issue by Razzeee** [mde/ejs#230]
Is there a way to remove previous newlines?

My problem is creating xmls

```
    <requires>
        <import addon="xbmc.python" version="<%= props.kodiVersion %>"/>
<%_ if (props.type == 'Plugin') { -%>        <import addon="script.module.routing" version="0.2.0"/><% } %>
<%_ if (props.kodiVersion == '2.24.0' && (props.type == 'Plugin' || props.type == 'Script' || props.type == 'Service')) { -%>        <import addon="script.module.simplejson" version="3.3.0"/><% } %>
    </requires>
```

What I often end up with is this:
```
    <requires>
        <import addon="xbmc.python" version="2.24.0"/>

        <import addon="script.module.simplejson" version="3.3.0"/>
    </requires>
```

So I would need something instead of `<%_` I guess

**Comment by mde** [comment]
Extensive data reformatting features are really outside the scope of EJS's core functionality. Your best option is to run your output through some sort of prettify library, like `pretty-data`: https://www.npmjs.com/package/pretty-data.

**Comment by Razzeee** [comment]
Okay, thanks, not sure if I can configure yeoman to use that.

**Comment by mde** [comment]
I know people run into issues using EJS in constrained environments like Yeoman or Express. Sounds like what we need is an optional, plugin-style API for modifying the output. Does Yeoman give you any way to configure EJS?

**Comment by Razzeee** [comment]
Well seems like it's used because it's used in https://github.com/sboudrias/mem-fs-editor
See: https://github.com/yeoman/generator/blob/master/package.json#L50

Maybe @SBoudrias can chip in here :)

**Comment by SBoudrias** [comment]
You can read/format/write the content of a file. Or you can use the [`registerTransformStream` function](http://yeoman.io/authoring/file-system.html) to register write levels processing.

**Comment by mde** [comment]
Sorry, I don't have enough context here about mem-fs-editor to understand how this is related to Yeoman. Is it a lower-level dep or something?

**Comment by RyanZim** [comment]
> Is it a lower-level dep or something?

@mde Yeoman uses mem-fs-editor under the hood.

**Comment by mde** [comment]
We can't really invent special, different tags to accommodate all the various ways people might want to handle whitespace, or reformat the markup produced by EJS.  I'd be happy to have a longer discussion about a more generalized approach to solving this, but one-offing each individual desired formatting change with ad-hoc tags doesn't seem like the right approach. I'm going to close this issue, but interested parties can certainly feel free to open and issue to propose a better long-term solution for this type of problem.
