### ISSUE TITLE
EJS plugin for phpStorm

### ISSUE THREAD

**Issue by Ikhan** [mde/ejs#234]
Any ejs plugins for PhpStorm. I couldnt find any plugin that matching for my version. 

PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Thanks.

**Comment by RyanZim** [comment]
I don't use phpstorm, so I don't know.
