### ISSUE TITLE
ejs cannot be evaluated correctly, when r.js compile with shim config.

### ISSUE THREAD

**Issue by miraclelife** [mde/ejs#236]
config in gruntfile.js
requireConfig.paths = {
........
'ejs': '../libs/ejs/ejs',
'tpl': '../libs/requirejs-ejs-plugin/rejs'
}
requireConfig.shim = {
........
'ejs': { exports: 'ejs' }
}
requirejs: {
compile: {
options: {
dir: 'jsc',
wrap: true,
baseUrl: 'js',
preserveLicenseComments: false,
removeCombined: true,
findNestedDependencies: true,
useStrict: true,
optimize: 'uglify2',
generateSourceMaps: false,
inlineText: true,
wrapShim: true,
paths: requireConfig.paths,
shim: requireConfig.shim,
modules: [{
name: 'login'
}]
}
}
}

login.js
define([
'flight/lib/component',
'hbs!loginTpl',
'configuration/plugins/registry',
'util/withDataRequest',
'tpl!util/alert',
'util/requirejs/promise!util/service/propertiesPromise'
], function(
defineComponent,
template,
registry,
withDataRequest,
alertTemplate,
configProperties) {
'use strict';
............
});

the document structure:
js
-- login.js
libs
--ejs/ejs
--requirejs-ejs-plugin/rejs

when run 'requirejs:compile' task throw error:
[INFO] Running "requirejs:compile" (requirejs) task
[INFO] ReferenceError: ejs is not defined
[INFO] In module tree:
[INFO] login
[INFO] tpl
[INFO] ejs
[INFO]
[INFO] { Error: ReferenceError: ejs is not defined
[INFO] In module tree:
[INFO] login
[INFO] tpl
[INFO] ejs
[INFO]
[INFO] at eval (eval at (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25281:64), :1:1)
[INFO]
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25865:19
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:3056:39
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:2996:25
[INFO] at Function.prim.nextTick (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25616:9)
[INFO] at Object.errback (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:2995:26)
[INFO] at Object.callback (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:2981:23)
[INFO] at Object.then (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:3035:23)
[INFO] at build (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25822:12)
[INFO] at runBuild (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:27831:17)
[INFO] at Object.execCb (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:1943:33)
[INFO] originalError:
[INFO] { ReferenceError: ejs is not defined
[INFO] at eval (eval at (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25281:64), :1:1)
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25281:55
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:3038:37
[INFO] at F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:2986:25
[INFO] at Function.prim.nextTick (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25616:9)
[INFO] at Object.callback (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:2985:26)
[INFO] at Object.then (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:3035:23)
[INFO] at Object.context.load (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:25269:28)
[INFO] at Object.load (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:1082:29)
[INFO] at Object. (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\requirejs\bin\r.js:1068:70)
[INFO] moduleTree: [ 'ejs', 'tpl', 'login' ],
[INFO] fileName: 'F:/fusionminer/visallo/git-workspace/visallo-git/web/war/src/main/webapp/jsc/ejs.js' } }

<node.version>v4.2.1</node.version>
<npm.version>3.3.8</npm.version>
requirejs -v 2.1.20

**Comment by RyanZim** [comment]
@miraclelife Are you using the UMD build from the latest release?

**Comment by miraclelife** [comment]
@RyanZim   The problem was resovled, after i modified the 'ejs' definition in shim config:
'ejs': { exports: function () {
                return 'ejs';
            } },

but  run 'requirejs:compile' task failed also, 
when r.js compile ejs template file throw error:
[INFO] Running "requirejs:compile" (requirejs) task
[INFO] 
[INFO] Tracing dependencies for: visallo
[INFO] Cannot optimize network URL, skipping: //localhost:35729/livereload.js
[INFO] { [Error: Error: Loader plugin did not call the load callback in the build:
[INFO] tpl:
[INFO]   tpl!util/alert_unnormalized4: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!util/alert: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!appFullscreenDetails: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!appFullscreenDetailsError: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!app: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!menubar/menubar: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/form/shareRow: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/form/permissions: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!util/users/user: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/workspaces: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/item: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/overlay: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!workspaces/diff/diff: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO] http://requirejs.org/docs/errors.html#timeout
[INFO]   tpl!graph/graph
[INFO]   tpl!graph/loading
[INFO]   tpl!util/controls
[INFO]   tpl!util/rightBar
[INFO]   tpl!detail/dropdowns/propertyForm/justification
[INFO]   tpl!detail/dropdowns/propertyForm/justificationRef
[INFO]   tpl!detail/detail
[INFO]   tpl!map/template
[INFO]   tpl!map/instructions/regionCenter
[INFO]   tpl!map/instructions/regionRadius
[INFO]   tpl!map/instructions/regionLoading
[INFO]   tpl!help/help
[INFO]   tpl!help/sections
[INFO]   tpl!util/vertex/menu
[INFO]   tpl!util/edge/menu
[INFO] Module loading did not complete for: visallo, login, appFullscreenDetails, app, menubar/menubar, search/search, workspaces/workspaces, workspaces/form/form, util/users/userSelect, workspaces/overlay, workspaces/diff/diff, admin/admin, graph/graph, graph/withControlDrag, graph/popovers/findPathPopover, util/withFormFieldErrors, util/controls, util/rightBar, util/popovers/fileImport/fileImport, detail/dropdowns/propertyForm/justification, detail/detail, map/map, help/help, util/vertex/menu, util/edge/menu
[INFO]     at Function.build.checkForErrors (F:\fusionminer\visallo\git-workspace\visallo-git\web\war\src\main\webapp\node_modules\grunt-contrib-requirejs\node_modules\requirejs\bin\r.js:31556:19)
[INFO] ]
[INFO]   originalError: 
[INFO]    [Error: Loader plugin did not call the load callback in the build:
[INFO]    tpl:
[INFO]      tpl!util/alert_unnormalized4: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!util/alert: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!appFullscreenDetails: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!appFullscreenDetailsError: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!app: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!menubar/menubar: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/form/shareRow: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/form/permissions: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!util/users/user: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/workspaces: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/item: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/overlay: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!workspaces/diff/diff: Error: Load timeout for modules: tpl!util/alert_unnormalized4,tpl!util/alert,tpl!appFullscreenDetails,tpl!appFullscreenDetailsError,tpl!app,tpl!menubar/menubar,tpl!workspaces/form/shareRow,tpl!workspaces/form/permissions,tpl!util/users/user,tpl!workspaces/workspaces,tpl!workspaces/item,tpl!workspaces/overlay,tpl!workspaces/diff/diff
[INFO]    http://requirejs.org/docs/errors.html#timeout
[INFO]      tpl!graph/graph
[INFO]      tpl!graph/loading
[INFO]      tpl!util/controls
[INFO]      tpl!util/rightBar
[INFO]      tpl!detail/dropdowns/propertyForm/justification
[INFO]      tpl!detail/dropdowns/propertyForm/justificationRef
[INFO]      tpl!detail/detail
[INFO]      tpl!map/template
[INFO]      tpl!map/instructions/regionCenter
[INFO]      tpl!map/instructions/regionRadius
[INFO]      tpl!map/instructions/regionLoading
[INFO]      tpl!help/help
[INFO]      tpl!help/sections
[INFO]      tpl!util/vertex/menu
[INFO]      tpl!util/edge/menu
[INFO]    Module loading did not complete for: visallo, login, appFullscreenDetails, app, menubar/menubar, search/search, workspaces/workspaces, workspaces/form/form, util/users/userSelect, workspaces/overlay, workspaces/diff/diff, admin/admin, graph/graph, graph/withControlDrag, graph/popovers/findPathPopover, util/withFormFieldErrors, util/controls, util/rightBar, util/popovers/fileImport/fileImport, detail/dropdowns/propertyForm/justification, detail/detail, map/map, help/help, util/vertex/menu, util/edge/menu] }

**Comment by RyanZim** [comment]
Good to hear.

**Comment by miraclelife** [comment]
But r.js compiled the ejs template file failed also.
