### ISSUE TITLE
README broken on npm

### ISSUE THREAD

**Issue by stephenmathieson** [mde/ejs#237]
<img width="983" alt="screen shot 2017-02-16 at 12 21 08" src="https://cloud.githubusercontent.com/assets/571265/23039478/71d9000e-f442-11e6-8226-7ddf73173d3a.png">

**Comment by mde** [comment]
Thanks. The README.md is in the package -- maybe NPM's parser is less tolerant than GitHub's, and there's some sort of syntax issue. I'll take a look.

**Comment by mde** [comment]
Nope, looks like it was just a glitch in NPM publish, when pushing out the last version. It was about time for a release anyhow, and it's now showing up correctly since publishing v2.5.6. Thanks for flagging me on this!
