### ISSUE TITLE
if else condition in ejs 

### ISSUE THREAD

**Issue by fadeI** [mde/ejs#241]
Hi Guys, 

I am trying to get feedback from server status if it success or failed
on server side I do the following 
```
  // send mail with defined transport object
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      res.render('contact',{message: 'faild'});
    }else {
    console.log('Message %s sent: %s', info.messageId, info.response);
    res.render('contact',{message: 'success'});
    }
   
  });
``` 

**on client EJS side**
I am trying to check 
 ```
<% if(<% message == 'faild') { %>
    <div class = "alert alert-danger">You havsssse no to-dos.</div>
	<% } else if (message == 'success') { %>
    <div class= "alert alert-success">You have nosssssaassasfff to-dos.</div>
<% } %>
```

but I it doesn't work ? can you please help me with that?

**Comment by RyanZim** [comment]
When you call `res.render` on the server side, that renders the EJS template server-side. You cannot access your server-side EJS locals on the client-side.

Why don't you just run EJS only on the server-side? Your EJS would work if you put it in the `contact` EJS view.

**Comment by fadeI** [comment]
do you mean to create new views (success option and failure option ) and render the it according the status ?

**Comment by RyanZim** [comment]
No, just add the EJS logic you posted above to the contact view.

**Comment by fadeI** [comment]
acutally this is the contact ejs view , and I used  my code inside it .but it doesn't work ? 
marked part at the end doesn't wroks as expected to show the needed messages.

`<form method="post" action="contact">
<div class="contact-form">
	<div class="contact-to">
<input type="text"  name='name' class="text" value="Name..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name...';}">
<input type="text"  name='email' class="text" value="Email..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email...';}">
<input type="text" name='subject'class="text" value="Subject..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Subject...';}"></div>
<div class="text2">
   <textarea name= "message" value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message..</textarea> </div>
<span><input type="submit" class="" value="Submit"></span>
 </div>
  </form>
	**<% if(<% message == 'faild') { %>
    		<div class = "alert alert-danger">You havsssse no to-dos.</div>
			<% } else if (message == 'success') { %>
    	<div class= "alert alert-success">You have nosssssaassasfff to-dos.</div><% } %>`**

**Comment by RyanZim** [comment]
Sorry, not enough information to debug. You could try making a MCVE, and posting it on StackOverflow.com
