### ISSUE TITLE
Problem when using %> tag on comments

### ISSUE THREAD

**Issue by Nakomoto** [mde/ejs#242]
`<h1><%= title %></h1> <!-- test <%= -->`

Error: Could not find matching close tag for "<%=".

**Comment by RyanZim** [comment]
EJS doesn't know anything about HTML, or HTML comments. This means you that: 
`ejs.render('<!-- <%= title %> -->', {title: 'Hello World!'})` will output `<!-- Hello World! -->`

It also means that EJS will throw syntax errors if you have invalid EJS tags in your HTML comments.
