### ISSUE TITLE
&& in if statements?

### ISSUE THREAD

**Issue by chrisleyva** [mde/ejs#243]
Is it possible to have an && in an if statement?

Like:

<% if (x && x.something==='hi') {%>

Doesn't seem to work for me.
Can't find anything in documentation. 
Thank you!

**Comment by RyanZim** [comment]
@chrisleyva Any valid JS should work. (You just can't use asynchronous methods like `setTimeout`) `&&` should work fine.

> Doesn't seem to work for me.

Are there any error messages?

**Comment by RyanZim** [comment]
Closing for lack of response.
