### ISSUE TITLE
I just want to know which website is the official site of EJS?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [mde/ejs#249]
I just want to know which website is the official site of EJS?

it's very confused me!

+ http://www.embeddedjs.com/

or

+ http://ejs.co/

**Comment by mde** [comment]
There is no "official" EJS.  There are multiple implementations of EJS, starting from as early as the early 2000s (long before NodeJS existed). The Web site at http://www.embeddedjs.com/ is for a client-side only implementation that has existed for a very long time.

This repo is the for the version of EJS that you can install via NPM. Its Web site is http://ejs.co/.

I hope that answers your question.

**Comment by xgqfrms-GitHub** [comment]
Thanks for your time!

It's a very good explanation.
