### ISSUE TITLE
Can any possible EJS support 'slot' like Vue.js template?

### ISSUE THREAD

**Issue by rubyisapm** [mde/ejs#250]
I know these two are totally different. Like that:
the parent template 'page':
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="renderer" content="webkit"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <link href="http://static.tcy365.com/cdn/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <slot name='style'></slot>
</head>
<body>
<slot name='body'></slot>
<slot name='script'></slot>
</body>
</html>
```

Then I use it like that:
```
<page>
    <template name='style'>
        <link href='...'/>
    </template>
    <template name='style'>
        body things
    </template>
    <template name='style'>
        <script ...>
    </template>
</page>
```

I think it's better than 'include' because it 'slice' the structure.

**Comment by RyanZim** [comment]
Hi @rubyisapm. Basically what you're asking for is template inheritance. EJS has never supported this, and it doesn't look like we'll be adding support in the near future. Sorry.

**Comment by k1r0s** [comment]
btw you can achieve this:

```html
...
<!-- ejs -->
<body>
  <?= partial('nav')?>

</body>
```
ejs.render(template, { context: view})

view could have "partial" property which return tpl string

:\ hope might be useful
