### ISSUE TITLE
Ajax with include

### ISSUE THREAD

**Issue by navneetccna** [mde/ejs#253]
When i try to add include in my ejs file its working fine.
HTML
report.ejs
```
<tbody>                  
    <%- include('include/playersTable'); %>
</tbody>
```
Javascript
```js
$.get('/reports.ejs', function (template) {
	// Compile the EJS template.
	reportTemplate = ejs.compile(template);
});
```

But when i call it with ajax it says 
`include` use relative path requires the 'filename' option.

And when i try it with client site

Javascript
```js
$.get('/reports.ejs', function (template) {
	// Compile the EJS template.
	reportTemplate = ejs.compile(template, {client: true});
});
```

it says
```
include is not a function
    at eval (eval at compile (ejs.js:525), <anonymous>:103:17)
```

**Comment by RyanZim** [comment]
@navneetccna You can't easily use `include` on the client-side, since EJS doesn't know where to load the included file from.

Here's how to get it working:
```js
$.get('/reports.ejs', function (template) {
  var fn = ejs.compile(template, {client: true});

  // When you want to render your template, pass an IncludeCallback:
  fn(data, null, function(path, data){
    // this function gets the path of the file to include, and a copy of the data
    // Should return the contents of the included file
  });
});
```

**Comment by navneetccna** [comment]
Can you pleas give more detail about as i tried this code it give me same error 
TypeError: include is not a function

**Comment by Honatas** [comment]
Using the suggested approach, I'll have to create an ajax request for each included template. Also, the included templates will not be able to be precompiled.

Compile should find a way to make the result function call the respective precompiled function of the included template.
