### ISSUE TITLE
Prevent ejs files from being downloaded

### ISSUE THREAD

**Issue by sacharbit** [mde/ejs#254]
I realized halfway through my project that when I type http://urldomain.fr/nameejsfile.ejs it downloads the raw file which can have some security issues. I don't connect to a db in the file and I use data that the client would see anyway but I can imagine how that can turn out to be a problem for me later on. 

Is there any way to prevent someone from downloading the ejs files?

**Comment by RyanZim** [comment]
@sacharbit This all depends on how your webserver is configured. This isn't an issue with EJS, it's an issue with your server configuration. Closing.
