### ISSUE TITLE
Help: Handle the `<property> is not defined` error

### ISSUE THREAD

**Issue by antonyn** [mde/ejs#255]
Hello,

Is there a way i can handle the scenario of a template using a property which doesn't exist in the model?

When i say handle i mean:
 - ejs not throw an error on invokiing `ejs.render`
 - just display a blank value for the missing property
 - not have to add anything else to the template

Here is my example:

```
var model ={
  name: "chuck norris"
};
var template = '<%= name %><%= missingProperty %>';

var html = ejs.render(
    template,
    model);
```

Currently on `ejs.render` i get the following error:

```
ReferenceError: ejs:1
 >> 1| <h1><%= name %></h1>,<%= missingProperty %>

missingProperty is not defined
    at eval (eval at <anonymous> (/Users/antonyn/GitHub/node-pg/src/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:12:26)
    at returnedFn (/Users/antonyn/GitHub/node-pg/src/node_modules/ejs/lib/ejs.js:555:17)
    at Object.exports.render (/Users/antonyn/GitHub/node-pg/src/node_modules/ejs/lib/ejs.js:364:37)
    at Object.<anonymous> (/Users/antonyn/GitHub/node-pg/src/index.js:15:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

Any help would be appreciated, many thanks.

**Comment by antonyn** [comment]
I see someone raised a similar issue #79 

I'm guessing the same answer applies here

**Comment by RyanZim** [comment]
There are several workarounds for this.

You can set the `_with` option to false to access your properties from an object. However, this will require rewriting your templates.
```js
var model ={
  name: "chuck norris"
};
var template = '<%= locals.name %><%= locals.missingProperty %>';

var html = ejs.render(
    template,
    model,
    {
      _with: false
    }
);
```
This will simply omit printing any missing properties. I personally use this approach.

---

The other way is to peform a `typeof` check if you don't know if a variable is defined:
```js
var template = '<%= name %><%= typeof missingProperty !== 'undefined' ? missingProperty : '' %>';
```
Note that the template above would error if `name` wasn't set.

---

The other way to handle this is to make an object that contains null values of your data structure and use [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign):
```js
var struct = {
  name: '',
  missingProperty: ''
}
var model ={
  name: "chuck norris"
};
var template = '<%= name %><%= missingProperty %>';

var html = ejs.render(
    template,
    Object.assign({}, struct, model)
);
```

**Comment by antonyn** [comment]
Perfect - thanks for the quick response. I actually started going down the `typeof` route but i think the `_with` option seems nicer so i will have a play with that.

**Comment by DougTy** [comment]
I know this is an old issue, however I would like to share some other solutions I worked out. In case someone else stumbles upon this issue with the same problem, hopefully they may find these useful:

```javascript
const data =
{
  exists: function( name )
    {
      if ( this[name] )
        return true
      return false
    },
  getValue: function( name )
    {
      if ( this[name] )
        return this[name]
      return ''
    },
}

const template = "<% if ( exists( 'missing' ) ) { %> <%= missing %> <% } %>\
                  <%= getValue( 'missing' ) %>"

const output = ejs.render( template, data )
```
