### ISSUE TITLE
How to update data using EJS template on client side

### ISSUE THREAD

**Issue by prem911** [mde/ejs#257]
There is a update method on EJS template ( http://www.embeddedjs.com/getting_started.html )
new EJS({url: 'comments.ejs'}).update('element_id', '/comments.json')

I didnot find the same in this implementation. Is this missing?

**Comment by RyanZim** [comment]
@prem911 That is a different implementation, our website is http://ejs.co/. We don't attempt feature parity with embeddedjs.com

**Comment by prem911** [comment]
@RyanZim Any plans to have an update API or something similar?

**Comment by RyanZim** [comment]
>  Any plans to have an update API

Not sure what you mean.
