### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by YanetP88** [mde/ejs#259]
I can't find how to format a date coming from the database. In ejs view it shows: Mon May 15 2017 18:36:47 GMT-0400 (Hora estándar oeste, Sudamérica)

**Comment by RyanZim** [comment]
@YanetP88 It's just like JS, you have to use the JS date methods to format it in the manner you desire: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
