### ISSUE TITLE
Issue parsing '//' string literal

### ISSUE THREAD

**Issue by wjordan** [mde/ejs#26]
This line does not parse correctly with this library, instead it throws the error "Unexpected identifier":
```js
<% var root = location.protocol + '//' + location.host %>
```
Current workaround is to replace the '//' string constant with an escaped '\/\/' (or '/' + '/' also works). I suspect that the global double-slash search-and-replace comment stripping at [ejs.js#L471](https://github.com/mde/ejs/blob/master/lib/ejs.js#L471) is not considering this edge case properly.

**Comment by TimothyGu** [comment]
Seems like the case. I'll investigate this

**Comment by TimothyGu** [comment]
Fixed, thanks. A test case also added to make sure this bug will never appear again.
