### ISSUE TITLE
which version supports IE6-8?

### ISSUE THREAD

**Issue by pei-han** [mde/ejs#264]
The later ejs has used ES5 API and syntax ,e.g. forEach statement and so on.
I need back to IE8,can anyone help me,thank so much.

**Comment by RyanZim** [comment]
EJS dropped IE6-8 a long time ago; you'll have to transpile the source using something like http://babeljs.io/.

**Comment by pei-han** [comment]
Thank you @RyanZim

**Comment by pei-han** [comment]
I have used Babel,and it just transforms the syntax of es5 and/or above es5 to es5.
Moreover the ie8 only supports es3.Which plugin of Babel can i use to accomplish it?
Can you help me,please?Thanks a lot.
@RyanZim

**Comment by pei-han** [comment]
I have solved this question by myself.I have used es5-shim that is designed to patch the native Javascript engine.
I know the later ejs to use ES5 methods that can be faithfully emulated with a legacy JavaScript engine via the console of ie8 browser.Moreover the ie8 do not support these methods.

The es5-shim is just alive for this.
