### ISSUE TITLE
HOW-TO browse and study the source code of EJS?

### ISSUE THREAD

**Issue by pei-han** [mde/ejs#265]
I am freshman,i use the EJS and think it is awesome.So i wanner study the source code of EJS.By this way improve myself.
Can anyone help me please?Thanks a lot.

**Comment by RyanZim** [comment]
@pei-han It's all right here in the repository: https://github.com/mde/ejs/blob/master/lib/ejs.js

**Comment by pei-han** [comment]
Thanks @RyanZim  :)
