### ISSUE TITLE
renderFile synchronous API support?

### ISSUE THREAD

**Issue by kimown** [mde/ejs#267]
I want to use `ejs.renderFile` to render an ejs file, but renderFile is an asynchronous API, but for some reason, I want to use synchronous API like `renderFileSync`, or should I use render method like this?
```
ejs.render(fs.readFileSync(filename, 'utf-8'), data, options)
```

https://github.com/mde/ejs/issues/36#issuecomment-70885745

**Comment by RyanZim** [comment]
@kimown Yep, that should work. The only catch is that if you want `include`s to work, you must set the `filename` option as part of your options.
