### ISSUE TITLE
ejs client side

### ISSUE THREAD

**Issue by antonioaltamura** [mde/ejs#268]
Sadly I cannot find that much example of ejs clientside.
I see in docs that `renderFile` won't work, and that's it.
There is a way to use something embedded templates:

```<script type='text/ejs' id="myTmpl">
<h1><%= title %></h1>
</script>
```

In other words: there is a way to use EJS clientside more that inlining the templates?

**Comment by mde** [comment]
There is not a built-in facility for getting template strings to the browser. One way is including your template as `<script type="text/ejs">`, then access its `innerText`. Another way would be concating them all into a file where they're accessible by variable name, which you could include in your frontend build process. Hope this answers your question.
