### ISSUE TITLE
get the query string

### ISSUE THREAD

**Issue by antonioaltamura** [mde/ejs#269]
I'm on Nodejs/Express with EJS templating.
I'm trying to get the query params in a EJS template.
Here https://stackoverflow.com/questions/20130960/getting-the-url-parameters-in-an-ejs-template 
@mwielbut said all you need is `<%= req.query.paramName %>` but it doesn't work for me, there is another way (without an ad-hoc middleware)?

**Comment by RyanZim** [comment]
You need to pass it as a local to EJS, one way or another.

**Comment by antonioaltamura** [comment]
I notice `locals` works  or usual template params like
router`.get('/', function (req, res, next) {
		res.render('index', {uri: req.query.uri});
	})`

works too, I thought there is a plain simple&general way to get the query in its own page for EJS :)

**Comment by mde** [comment]
EJS is really just about rendering a template. Things like URLs and query strings are the purview of whatever Web framework (like Express) you are using EJS with. Whatever data you want to use in rendering your template, you need to pass to it.
