### ISSUE TITLE
Usage in Express - date values passed to getting converted to strings

### ISSUE THREAD

**Issue by robations** [mde/ejs#270]
I'm fairly new to Express and ejs, but I have a project where an array of objects is passed to `res.render()`, including a date property (represented as a JS Date object).

I can see in the debugger the date values are objects when passed in, but in the template they are converted into strings and in the original array/object dates are similarly mutated. Is it possible that ejs does this, or is it a hidden feature of Express?

```
// before
[{name: string, date: Date}, {name: string, date: Date}]

// after render
[{name: string, date: string}, {name: string, date: string}]
```

**Comment by RyanZim** [comment]
EJS is rendering a string, so it has to convert everything to strings (via `.toString()`).

**Comment by robations** [comment]
Obviously it outputs a string, but if I have this in a template:

```
<% console.log(typeof anyDate) %>
```

The output in the console is `string`.

**Comment by robations** [comment]
I'll try to isolate this (later when I have some spare time...), unless this is by design? I'll note that functions passed to the template remain as functions. I made a workaround by passing a function that simply returns the array that I need.

**Comment by RyanZim** [comment]
Seems to work fine for me: https://runkit.com/57ebc041d4a27f140028fd78/59676f2da1cf0700127e6616

Perhaps it's an issue with your code?

**Comment by robations** [comment]
Nice one-liner :) Okay, I will try to eliminate components one by one, seems like there is some "magic" somewhere. Thanks for your info.

**Comment by robations** [comment]
This turned out to be some middleware that had been installed (express-promise) mutating objects passed to the response object in express. Sorry about the extra noise.

**Comment by RyanZim** [comment]
Glad to hear you got this figured out.
