### ISSUE TITLE
`include` from multiple root paths

### ISSUE THREAD

**Issue by lgfa29** [mde/ejs#275]
Hi everyone,

I am experimenting with multi-package projects with Express and I hit an issue with EJS where `include`s are only searched in the local package, even though Express is configured to have multiple `view` paths.

I created a sample repo to illustrate the problem: https://github.com/lgfa29/express-multi-package-demo. Accessing http://localhost:3000/foo will throw the `include` error.

Looking around past issues and PRs I found #120 which seems to fix this issue, which was closed by @mde, but I don't think he understood what the problem was.

In the demo project I linked above I have multiple `view` paths configured:
```javascript
// view engine setup
var views = [
  path.join(__dirname, 'views'),
  path.join(path.dirname(require.resolve('foo')), 'views')
];
app.set('views', views);
```
So Express is able to find views in both packages properly without any changes to EJS (like @mde [described](https://github.com/mde/ejs/pull/120#issuecomment-264347463)), the problem is that the views lookup logic is not the same for `include`s, so it doesn't look in all possible paths.

**Comment by mde** [comment]
Ah, it was not clear that the issue was the difference between the initial render and subsequent calls to `include`. I'll have a look at that PR and see if it makes sense to resurrect it.

**Comment by mde** [comment]
@lgfa29 Can you check out the latest master and see if that fixes the issue for you?

**Comment by lgfa29** [comment]
Thanks @mde, just tested from `master` and the includes are working now! I will go ahead and close this issue.
