### ISSUE TITLE
ejs.renderFile can't find file if using relative pathing

### ISSUE THREAD

**Issue by c0debreaker** [mde/ejs#281]
This is failing
```
    ejs.renderFile('./templates/registration_confirmation.ejs', registrationData, (err, html) => {
    or this
    ejs.renderFile('templates/registration_confirmation.ejs', registrationData, (err, html) => {
```
but this works
```
    ejs.renderFile(path.join(__dirname, 'templates/registration_confirmation.ejs'), registrationData, (err, html) => {
```

What's wrong with the first code?

**Comment by RyanZim** [comment]
@c0debreaker By default, EJS is going to look for the file relative to `process.cwd()`, the directory where the Node.js process was started. `__dirname` is the directory that your JS file is in. If you don't want to join to `__dirname`, you need to make your paths relative to where the Node.js process is started.

**Comment by c0debreaker** [comment]
Got it. I got used to with the way I use import like in my ReactJS projects.
Good thing to know. Thanks!
