### ISSUE TITLE
`esc` is not a function  (please publish new version)

### ISSUE THREAD

**Issue by tswaters** [mde/ejs#283]
Looks like this error was  fixed back in February (64e55cc), but a new version was never published.

Any chance a new version of this module could be published to npm?  As it stands, it's quite difficult to debug problems when developing as any actual error is replaced with `esc is not a function`

There are even people asking about this specific error on SO:
https://stackoverflow.com/questions/42699580/nodejs-esc-is-not-a-function
https://stackoverflow.com/questions/43991490/nodejs-express-esc-is-not-a-function

Which of course is highly specific to each case.... if the module was updated these errors would be replaced with someone that makes sense for the case.

**Comment by RyanZim** [comment]
@mde ping for release.

**Comment by mde** [comment]
New release, v2.5.7: https://github.com/mde/ejs/releases/tag/v2.5.7
