### ISSUE TITLE
Can I use EJS to "template" static front-end .js files (the ones in the "public" folder)?

### ISSUE THREAD

**Issue by aguyinmontreal** [mde/ejs#286]
If no, what's the best way to do it (except AJAX)?

Thanks

**Comment by mde** [comment]
If you can get the template text into your JS runtime, then you can certainly use EJS to render it. There are various ways of getting template text --  using Ajax to grab it from a file, embedding it in your base HTML page (e.g. inside a script tag of type="text/ejs" or inside a textarea), or building it into a script file as a variable. I hope that answers your question.
