### ISSUE TITLE
Delimiter changes from % to ? if not set.

### ISSUE THREAD

**Issue by bertolo1988** [mde/ejs#292]
Hello,

I developed a private npm package where i used ejs to render some emails.
When i am developing the package i never had issues while running rendering tests, demoing etc.
In this case when i `var ejs = require('ejs')` the exported object comes without a defined delimiter.

As soon as i published my packaged and started using it inside a docker container, which runs an older version of node (i think its 5.X.X), the delimiter is set to ? after require.

This rendered all my templates useless and i took a while to discover.
I easily solved my problem by setting the delimiter but it thought my report could still be useful.
Is this a known problem? Do you want more details in order to track this problem down?
I think this should be investigated.

**Comment by RyanZim** [comment]
Super weird, but we really can't debug this without a reduced test case repo.

**Comment by bertolo1988** [comment]
Would you be interested in making a conv call maybe?

**Comment by mde** [comment]
If it's unset, it used the default:

https://github.com/mde/ejs/blob/master/lib/ejs.js#L463

Something is explicitly setting the `delimiter` property. (You can see it in the image.)

**Comment by bertolo1988** [comment]
As you can see in my image the export.delimiter is set to '?' after importing.

**Comment by User4martin** [comment]
Well yes. And No.

Some other package in your node_modules (or in your own code, or any code you use) has set it to "?"

If you do anywhere 

    var foo = require("ejs");
    foo.delimiter = '?';

and then later require ejs somewhere else, then the delimiter is set already.

**Comment by bertolo1988** [comment]
Oh my god, you are absolutely right.

In my defense... the project i am working on is huge and i don't know most of it. I am completely surprised that it was already being used and defined.
