### ISSUE TITLE
lines count of error [proposition]

### ISSUE THREAD

**Issue by dutchenkoOleg** [mde/ejs#294]
Hi!

Can you increase lines count of error?
[https://github.com/mde/ejs/blob/master/lib/ejs.js#L303](https://github.com/mde/ejs/blob/master/lib/ejs.js#L303)

for example:
```html
<%
    let someVar1 = 'test';

    // ... code
    // ... code
    // ... code

    console.log(someVar2);
%>
```

end error log is 
```js
 >> 1| <%
    2| 	let someVar1 = 'test';
    3| 
    4| 	// ... code

someVar2 is not defined
```

I guess it would be great to have an some property for this value in ejs options 
[https://github.com/mde/ejs#options](https://github.com/mde/ejs#options)

**Comment by mde** [comment]
This would add complexity, and doesn't seem to provide a ton of value. Closing this issue. Happy to reopen if people feel strongly about a need for this.
