### ISSUE TITLE
why dose it not work

### ISSUE THREAD

**Issue by Lyd9607** [mde/ejs#296]
<% const d2=new Date(Date.parse( <%= result[i].jobEndtime%> ));  %>

**Comment by mde** [comment]
You are using just the script-execution tag. It is running your code, and outputting nothing. You need to use output tags like this: `<%=  %>`.

**Comment by Lyd9607** [comment]
I have used output tags   <%= result[i].jobEndtime%>,  but it seems can't nest  ,like this :
<% ......<%=  ......  %>     %>

**Comment by RyanZim** [comment]
You can't nest tags. To assign your variable, you want: 
```js
<% const d2=new Date(Date.parse(result[i].jobEndtime)); %>
```
To print something, you want:
```js
<%= result[i].jobEndtime %>
```

**Comment by Lyd9607** [comment]
i think if it can nest yags, it can be better

**Comment by Lyd9607** [comment]
nest tags, sorry

**Comment by mde** [comment]
Nesting tags would be needlessly complex, and hard to reason about. The most straightforward approach is for templates to have two contexts: the markup context, and the programming language context. I cannot imagine a use-case compelling enough to justify the complexity of going beyond that.
