### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by jdalrymple** [mde/ejs#297]
Adding the ability to return promises if a callback is not supplied to the renderFile function

```javascript
var renderedString = await ejs.renderFile(filepath, {data:'data'}, {options:options})
```

**Comment by RyanZim** [comment]
@jdalrymple This would need to be in the next major release, as we currently support all the way back to Node 0.10. We're considering a major release, and if we did do such a release, we'd definitely consider this.

**Comment by jdalrymple** [comment]
Ah yes, this wouldn't be backwards compatible. Fair enough!

**Comment by frank-dspeed** [comment]
@jdalrymple https://canjs.com/doc/can-ejs.html we still support promises :) we use only promises and streams in our apps but we got some newer stuff with a lot of new futures and call it can-stache :) thats why we deprecated the original EJS

**Comment by niftylettuce** [comment]
Would love to see this, in the meanwhile you can use `util.promisify`:

```js
const { promisify } = require('util');
const ejs = require('ejs');

const renderFile = promisify(ejs.renderFile).bind(ejs);

(async () => {
  try {
    const str = await renderFile('test');
    console.log(str);
  } catch (err) {
    throw err;
  }
})();
```

Thoughts on adding this to the docs/README in the meanwhile @RyanZim?

Also I don't see `ejs.renderFile` mentioned in the docs on the website at all, maybe we should add that to the docs section and also a note about Promise support.

**Comment by kaminskypavel** [comment]
@niftylettuce +1 for using "utils" library.

**Comment by mde** [comment]
Just opened a PR for this: https://github.com/mde/ejs/pull/333 @jdalrymple @RyanZim could y'all take a look?

**Comment by mde** [comment]
This has been merged and pushed to NPM in the newest release.
