### ISSUE TITLE
it cannot work on my android

### ISSUE THREAD

**Issue by unuai** [mde/ejs#299]
It works ok on my pc,but on my android it doesn't work,please tell me how to make it work on android?Maybe it doesn't support android?(Browser support:ejs.js)

**Comment by mde** [comment]
What is going wrong on your Android browser? EJS supports pretty old versions of JS, but it's possible whatever version of JS is on your phone/tablet is just very crippled.

**Comment by unuai** [comment]
thank you,now it works well,the reason why my page not show is I use 'let'  in js, if I use 'var' then it will have no problem
