### ISSUE TITLE
Module adds a global "fn"

### ISSUE THREAD

**Issue by dougwilson** [mde/ejs#3]
Regression from commit f314d88a5c5ae6b3474293b789129b2334e933c9 causes `fn` property to be added to the global object.

**Comment by mde** [comment]
Fixed in d428a2fc21ef5bdb6ffeabaf5caefd293c00d4aa, pushed to NPM, v2.0.5.

**Comment by dougwilson** [comment]
Thanks!

**Comment by mde** [comment]
No, thank you. Much appreciated!

**Comment by knownasilya** [comment]
Seeing this again with 2.5.2

**Comment by RyanZim** [comment]
@knownasilya Thanks for reporting! Please open a new issue with a reduced test case so we can investigate this.

Locking since this is an old issue.

**Comment by mde** [comment]
Incidentally I can't repro this regression with v2.5.2 -- not with CommonJS in Node, not with the built file in the browser.
