### ISSUE TITLE
Add versioning constant on exports

### ISSUE THREAD

**Issue by mde** [mde/ejs#30]
Especially useful for in-browser use.

**Comment by mde** [comment]
Fixed as of 2b5e474db5251deccdc69aaf70a5724c9bdb7ba3 -- will be pushed to NPM in next release.

**Comment by TimothyGu** [comment]
Would it be cleaner if we used

```js
require('../package.json').version
```

?

**Comment by mde** [comment]
Ah, that should totally work -- I didn't think about the fact that I just used Browserify to package up the client-side code. :)  This code was just ported over from another project. :)
