### ISSUE TITLE
Cannot link stylesheet

### ISSUE THREAD

**Issue by ckc52403050** [mde/ejs#300]
I am using ejs v2.5.7. Stylesheet is linked to the ejs file as follow. 
No error is shown in the console log.
However, the styles are not showing up in the localhost index.ejs.
What could possibly be the reason?
Anything to do with the ejs version update?

**in app.js:**
`const path = require('path');`
`app.use(express.static(path.join(__dirname, 'public')));`

**in index.ejs:**
`<link href="/css/style.css" rel="stylesheet" type="text/css">`

**The folder structure:**
Views
　index.ejs
Public
 　css
　　style.css
app.js

**Comment by RyanZim** [comment]
This looks like a server issue, not an EJS issue.

**Comment by mhmo91** [comment]
Kinda funny but works
  <style>
    /*
    <%include ./index.css%>
    */
  </style>
