### ISSUE TITLE
ejs repeat include

### ISSUE THREAD

**Issue by incubux** [mde/ejs#302]
I have tabs bootstrap 4, it includes a partial in which a table is created dynamically, when I ready the table referring to the database and I go to another tab and then I return to the tab in which I consult and graph the table dynamically, partial, ie the partial clean in the first instance and the same partial with the result of the query to the database listed in the html table, what am I doing wrong?

**Comment by RyanZim** [comment]
@incubux I'm not sure I understand. Please post a minimal code example.

**Comment by incubux** [comment]
sorry, I found the error, was in bootstrap 4, does not disable and activates the active class in the nav-tabs correctly, then displays the contents of other tabs each one is selected a new one, thanks for your time
