### ISSUE TITLE
Could not find include include ...

### ISSUE THREAD

**Issue by vefanov** [mde/ejs#303]
<h3>Hello</h3>

* ejs/lib/ejs.js -  "version": "2.5.7", line 152
<pre>throw new Error('Could not find include include file.');</pre>

Maybe it will be better to replace that line to this one
 <pre>throw new Error('Could not find the include file - "' + filePath + '"');</pre>

Sometimes it could save time to understand what is wrong in a path to a file  :) 

VE

**Comment by RyanZim** [comment]
EJS already includes the snippet pointing to the place where the error occurred:
```
Error: ejs:1
 >> 1| <%= include('asdf') %>

Could not find include include file.
```
I'm not sure what other information you want included?

**Comment by vefanov** [comment]
I use this syntax
<% include partials/header %>
I get only message in browser that you can see below.

Your syntax will help to see a line in ejs-file with a wrong relative path.
I know this line without error message.
I have to know the full path to my file to understand the issue.

The below message does't help to know it.

<hr>
Error: Could not find include include file.
    at getIncludePath (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:152:13)
    at includeSource (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:277:17)
    at /home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:630:26
    at Array.forEach (native)
    at Object.generateSource (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:606:15)
    at Object.compile (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:510:12)
    at Object.compile (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:359:16)
    at handleCache (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:202:18)
    at tryHandleCache (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:224:14)
    at View.exports.renderFile [as engine] (/home/ubuntu/workspace/DemoApp/EJS-test/node_modules/ejs/lib/ejs.js:438:10)

**Comment by Tobsta** [comment]
It would help if it displayed all of the full file paths that it tried as opposed to just saying it failed. Getting a message saying the filename wasn't resolved doesn't help at all.

**Comment by vefanov** [comment]
this line
<pre>throw new Error('Could not find the include file - "' + filePath + '"');</pre>
will show the full path, so it will help

**Comment by RyanZim** [comment]
OK, PR welcome; make sure to include tests.

**Comment by mde** [comment]
Merged #306.

**Comment by ak-kuldeep** [comment]
- > 1. VS Code 
- > 2. Left Side File Explorer
- > 3. Right Click on the '.ejs' file
- > 4. Click on 'Copy Path'
- > 5. Then paste that path

 `<%- include('YOUR_PATH/GOES_HERE') %>`

In my Case,
OS Ubuntu, Path was like this 

`<%- include('/media/username/diskname/foldername/nodejsApp/views/body/header.ejs') %>`

**Comment by TheJordach** [comment]
Hello, 
I had same issues : my nav.ejs and footer.ejs in views/includes/couldn't be seen by ejs. 
after many check and search here is how I managed to solve the issue.

`<%- include("includes/nav.ejs.js") %> `

Notice that you simply have to specify the full extension of the file. esj.js - I made some test by either escaping the extension or just doing .ejs --> same error occured. 

```
Here is the error 
Error: C:\Dev\NodeJS_FS_Frontend\views\about.ejs:20
    18|     <body id="page-top">
    19|         <!-- Navigation-->
 >> 20|         <%- include('includes/nav') %>
    21|         <!-- Masthead-->
    22|         <header class="masthead">
    23|             <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">

Could not find the include file "includes/nav"
```

This is solve just by using the complete extension 

I'am using 
OS : Windows 10 
IDE : IntelliJ 
"ejs": "^3.1.9",
"express": "^4.19.2"

here is my listner

```
const express = require("express");
const cors = require("cors");
const router = require("../router/router");
//const path = require("path"); // dont" need this

const app = express();

// Cors middleware
app.use(cors());

// Middleware for parsing JSON bodies
app.use(express.json());

// Declare middleware for templating
app.set("view engine", "ejs"); // Set the view engine
//app.set("./views", path.join(__dirname, "views")); // don't need to use this
app.engine("ejs", require("ejs").__express); // Set the engine

// Declare the public folder as static for serving static files
app.use(express.static("public"));


// Use the router middleware
app.use("/", router);
```

module.exports = app;

then the router 
```

router.get("/", (request, response)=>{
    response.render("home", {pagename:"Home"})
})
```

All my templates are located 
```
project_dir/views (home.ejs location)
project_dir/views/includes/nav.esj.js (nav and footer location
```

hope this will help
