### ISSUE TITLE
How to resolve templates in multiple folders with renderFile?

### ISSUE THREAD

**Issue by chenxsan** [mde/ejs#307]
Hi all :)

I'm using `ejs` 2.5.7 without express.js to compile data with templates, the templates would be located at multiple folders, for example **A** and **B**, when I call

```js
ejs.renderFile('index.ejs', {}, callback)
```
How can I make `ejs` to search folder **A** for `index.ejs` template first, if none, then search folder **B**. I'm trying to do something like what Jekyll theme described in https://jekyllrb.com/docs/themes/#overriding-theme-defaults.

I have checked the test https://github.com/mde/ejs/blob/59ac83b6d9519df01545ac5bca58bc10f0507e44/test/ejs.js#L417, and here's what I tried in my code:

```js
ejs.renderFile(
    'index.ejs',
    Object.assign(
      {},
      data,
      {
        settings: {
          views: [
            path.join(require.resolve('abab'), '..'), // has an `index.ejs` file
            path.join(template, '..') // has an `index.ejs` file too
          ]
        }
      }
    ),
    function (err, str) {
      if (err) {
        console.log('Failed to render index.ejs')
        return callback(err)
      }
      callback(null)
    })
```
I just got error:

> Error: ENOENT: no such file or directory, open 'index.ejs'

Looks like I misunderstood something here. Any help? Thanks.

**Comment by mde** [comment]
That should indeed work the way you've described. Can you provide a minimal failing test we can look at?

**Comment by mde** [comment]
No minimal repro case provided. Closing this issue.
