### ISSUE TITLE
Includes with root path

### ISSUE THREAD

**Issue by johnnytn** [mde/ejs#309]
I just updated from 2.5.1 to 2.5.7.
I'm using expressJS 4.16
I was looking around and found that in the 2.5.1v there was a "bug" that sets the  `includes` path as root automatic.
 So my question is, is there a way to set globaly this "root" option ?

Another thing I'm still looking into is when:
1- I set `app.set('views', path.join(__dirname, '/views'));`  ;
2 - include something like `<% include /ui/./layout %>`
3- the includePath loses all the path ` 'F:\ui\layout.ejs'`

I really didn't want to pass a rootPath in every .render...

- Update : 
Can I still use `.` to include ejs files? (ex: `<% include /ui/./layout %>`, <% include ./x/layout %>

**Comment by RyanZim** [comment]
Just declare your options object near the top of your file, and set the root path there, then pass your options into each `.render` call. If you need to use different options some places, put your global options in an object, and then do `Object.assign({}, globalOpts, { /* your options here */ })` at the `.render` call.

**Comment by johnnytn** [comment]
Well I'll just return to the `2.5.1` for now.
 You guys should complement the documentation a little more, It's lacking some real good info.

**Comment by RyanZim** [comment]
PRs welcome to clarify the docs; sometimes things are self-evident to those who work with the project, but not to outsiders.
