### ISSUE TITLE
Remove template caching

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#31]
This whole file caching thing is lame. We already cache the compiled functions. Why cache the file content?

**Comment by TimothyGu** [comment]
We got rid of it in jade a while ago: jadejs/jade@781901a4cd08561df3fb7339a449121cb8f0b2dd

**Comment by mde** [comment]
Good call. Would make sense if there were two separate flags, but with just one it's pretty useless. I have tried and failed to imagine why you'd cache one and not the other.
