### ISSUE TITLE
Custom fileLoader via options

### ISSUE THREAD

**Issue by rogeriopvl** [mde/ejs#310]
For consistency the `fileLoader` should also be supported via `options`. What do you think?

**Comment by RyanZim** [comment]
`fileLoader` was put on the EJS object, since `cache` is done the same way. However, there is a case to be made for a `fileLoader` option.

@mde @TimothyGu @User4martin Thoughts on this?

**Comment by mde** [comment]
Seems to me there's a difference between rendering options, and template-loading options. The process of loading template files seems like a lower-level concern, that is more likely to be set once, or handled by the surrounding framework, than on a case-by-case basis by individual invocations of 'render' by an end-user.

I'm going to go ahead and close this issue. Happy to re-open if more discussion is warranted.
