### ISSUE TITLE
Dynamic include with local data error ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by neginbasiri** [mde/ejs#315]
Hi all,
When I use include without passing data it works:

        <% if(data.twoColumnContent[0]){ 
            var content = data.twoColumnContent[0]; %>
            <%- include ../../components/content.blocks/two.column.content.ejs %>
        <%}%>

I need to pass local data. as well so I tried 

        <% if(data.twoColumnContent[0]){ 
            var content = data.twoColumnContent[0]; %>
            <%- include("../../components/content.blocks/two.column.content.ejs", {content: content}); %>
        <%}%>

But getting error

    Module build failed: Error: ENOENT: no such file or directory, open 'C:\Projects\Nephele\src\UI\src\templates\layouts\avalon\("..\components\content.blocks\two.column.content.ejs", {content: content});'

Any clue?

**Comment by User4martin** [comment]
Are you sure there is no space between `include` and the following open bracket `(`?

`include<space>` is the syntax for the none function style include.

**Comment by RyanZim** [comment]
@neginbasiri how are you calling EJS? Are you using `renderFile`?

**Comment by neginbasiri** [comment]
@User4martin Yes I am sure there is no space in between. 
@RyanZim I am not using renderFile. All I have is

**page.templates.js**
const pages = [
    {
        title: 'Fleets',
        template: 'templates/pages/avalon/fleets.ejs',
        filename: 'fleets.html',
        inject: 'body',
        data: require('../templates/data/avalon/fleets.json')
    }
];

const pageTemplates = pages.map(page => new HtmlWebpackPlugin(page));

module.exports = pageTemplates;

**webpack.config.js**
const pageTemplates = require('./page.templates.avalon.js');
const webpack = require('webpack');
let config = require('../../webpack.config.js');

// Set entry point
config.entry.app = './scripts/brands/avalon.js';

// Load in page templates
config.plugins.push(...pageTemplates);

module.exports = config;

**fleets.ejs**
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

     
</head>

<body>
    <%- include src/templates/layouts/avalon/fleets.layout.ejs %>
</body>

</html>


**Fleet.layout.ejs**
<% 
var data = htmlWebpackPlugin.options.data;
if (data) {  %>

<%- include ../../components/avalon/header/header.ejs %>
    <div class="page-mask">
        <%- include ../../components/hero.image/hero.image.ejs %>
        <%- include ../../components/content.blocks/one.column.content.ejs %>
        <%- include ../../components/content.blocks/image.row.content.ejs %>
        <% if(data.twoColumnContent[0]){ 
            var content = data.twoColumnContent[0]; %>
            <%- include("../../components/content.blocks/two.column.content.ejs", {content: content}); %>
        <%}%>
       
        <%- include ../../components/content.blocks/title.button.content.ejs %>
        <%- include ../../components/footer/footer.ejs %>
    </div>
<%}%>

**Comment by neginbasiri** [comment]
I am using ejs-compiled-loader and webpack 2.0.0

**Comment by victorjsj** [comment]
Hi.

I have the same issue, ENOENT: no such file or directory, open '("/templates/elements/ul", {data: root.header.data})'

"expose-loader": "^0.7.3"
"webpack": "^2.6.1"

**Comment by mde** [comment]
Is there some reason you're using the deprecated preprocessor directive for `include`? I don't believe it works with passed data, and it certainly doesn't work with dynamic filenames. (It literally includes the text of that template file inline at that location.)

This should be fixed if you use the modern, function-call for `include`. See docs here:

http://ejs.co/

Closing this issue, as we should be discouraging the use of the deprecated preprocessor approach.
