### ISSUE TITLE
include fails when using brackets

### ISSUE THREAD

**Issue by meowthing** [mde/ejs#316]
I want to include a JS object for processing in templates. This is stored in a separate file "json-object.ejs"
```
<%
locals.json = { test: 
   { 
      a: "yes"
   } 
}
%>
```
This works
```
<%- include ../../assets/static/json_object.ejs %>
<div><%= json.test["a"] %></div>
```

This does not
```
<%- include('../../assets/static/json_object.ejs') %>
<div><%= json.test["a"] %></div>
```
When compiling it says "json is not defined".

Any ideas?

**Comment by RyanZim** [comment]
The "preprocesser" include (without brackets) shares scope between the files; `include()` doesn't include variables defined in the included file, it's simply a function that returns the compiled file as a string.

I'm wondering why you're keeping your data in an EJS file; why not just pass your data into the EJS function call?

**Comment by meowthing** [comment]
Thanks for replying! I'm using EJS as the templating language for a static site, with the JS obj housing translations (similar to a Resource file in ASP.NET). I wanted to include different translation files depending on the page being built e.g.

```
<%- include('../../assets/static/json_object' + page.slug + '.ejs') %>
```

But sadly that does not seem possible.

**Comment by RyanZim** [comment]
You need to read the JSON in your JavaScript, then pass the data into EJS, instead of simply passing the path to the JSON to EJS.

**Comment by User4martin** [comment]
Not tested, but if you use `include()`, the copy of `locals` is only a flat copy.

So the following might work

    <%
    locals.foo.json = { test: 
       {       a: "yes"   } 
    }
    %>

    <%- locals.foo = {};  include('../../assets/static/json_object.ejs') %>
    <div><%= foo.json.test["a"] %></div>

**Comment by RyanZim** [comment]
@User4martin That won't work, `include` is a function that returns a string; it does not modify the locals object.

**Comment by meowthing** [comment]
Thanks @User4martin , I went ahead and implemented @RyanZim 's suggestion to read the file from the Javascript instead of linking the file directly.

```
<%
function getTranslationFile() {
    return JSON.parse(fs.readFileSync('./assets/static/translation_' + entry.slug + '.json'));
}

locals.translations = getTranslationFile();
%>
```

**Comment by User4martin** [comment]
@RyanZim 
I tested it, it works.

include can have site effects.

The copy of locals passed to include is a flat copy. if `foo` already exists *and* is an object, then it works.
Objects are by reference, so in the copied locals, `foo` refers to the same foo as outside. Changes in foo are visible to the caller.
