### ISSUE TITLE
prism-ejs-language

### ISSUE THREAD

**Issue by dutchenkoOleg** [mde/ejs#317]
I wrote tiny extend for [Prism](http://prismjs.com/) for EJS highlighting  
maybe someone will handy

https://github.com/dutchenkoOleg/prism-ejs-language

Also, I noticed a Prism plugin is used on the site [ejs.co](http://ejs.co/)  
and `language-markup` is used to demonstrate the ejs code.

`prism-ejs-language` can helps with `language-ejs`

**Comment by mde** [comment]
That is awesome. Thank you so much for doing that. It looks very useful. I'll close this -- thanks for posting this here; people will be able to find it with Search.
