### ISSUE TITLE
nested includes on includes

### ISSUE THREAD

**Issue by victorjsj** [mde/ejs#318]
Hi all.

I have an issue trying to include a template from an included template. 
```
- templates/
    * tab.ejs
    - elements/
        * ul.ejs
        * li.ejs
```
From tab.ejs I include the ul.ejs and works fine `<%- include /templates/elements/ul %>` but when I try to include li.ejs from ul.ejs `<%- include /templates/elements/li %>` then...

ENOENT: no such file or directory, open 'templates/elements/templates/elements/li.ejs'

Trying with all routes I can imaging is always the same... for instance:

`<%- include /li %>` results in 
        ENOENT: no such file or directory, open 'li.ejs'
`<%- include li %>` results in 
        ENOENT: no such file or directory, open 'li.ejs'

`<%- include /elements/li %>` results in 
       ENOENT: no such file or directory, open 'templates/elements/elements/li.ejs'
       ENOENT: no such file or directory, open 'elements/li.ejs'

Ets, etc... Thanks.

**Comment by RyanZim** [comment]
Use relative paths instead, i.e. `include li` in `ul.ejs`.

**Comment by victorjsj** [comment]
Nope.

<%- include li %>
ENOENT: no such file or directory, open 'li.ejs'

**Comment by RyanZim** [comment]
Please post a minimal reproducible test case

**Comment by victorjsj** [comment]
Just starting the project, no tests yet, but it's really simple...

index.ts

let template = require("/templates/tab.ejs");
let html = template();

/templates/tabs.ejs

<%- include /templates/elements/ul %>

/templates/elements/ul.ejs

<%- include /templates/elements/li %>

/templates/elements/li.ejs

Hello

I hope it's enought.

**Comment by RyanZim** [comment]
The require hook is deprecated and not recommended.

Here's a working example: [ejs-include.zip](https://github.com/mde/ejs/files/1441338/ejs-include.zip)

**Comment by victorjsj** [comment]
Hi Ryan.

Thanks and sorry for the delay. You example works well but I have a problem when I try to translate it to typescript. 

Uncaught TypeError: this.templateText.replace is not a function
    at Template.compile (ejs.js:441)
