### ISSUE TITLE
Could not find include include file while trying to render html

### ISSUE THREAD

**Issue by chittasec** [mde/ejs#321]
Hello,

  I am trying ejs to output html to the console .
  In the same folder I have two files index.ejs and show.ejs 
 index.ejs uses 'include' to show.ejs file .

I try below code to combine the html from both and display in console .
```js
const fs = require('fs');
const ejs = require('ejs');
var fileName = './content/index.ejs';
console.log(fileName);
fs.readFile(fileName, function(err, data) {
    if (err) {
    } else {
      var html = ejs.render(data.toString());
      console.log(html);
    }
  });
```
However it fails with below error .

"Could not find include include file" .

What is going wrong here and how to fix it ?

**Comment by RyanZim** [comment]
You need to use `renderFile` or pass the `filename` option to be able to use `include`.
