### ISSUE TITLE
Why does include preprocessor directive require a filename?

### ISSUE THREAD

**Issue by zachleat** [mde/ejs#324]
If I use `render` on a `compile("<% include /included %>")`, it throws an error even when my `root` is set properly and the template is resolved correctly.

Looks like it has to do with `resolveInclude` and an undefined argument to `path.resolve`. If I make the following change it works ok:

```diff
- var includePath = resolve(isDir ? filename : dirname(filename), name);
+ var includePath = filename ? resolve(isDir ? filename : dirname(filename), name): resolve(name);
```

But then looking through the tests it looks like you might expect this behavior? Is that right?

**Comment by zachleat** [comment]
I guess you can just pass a directory as both root and filename options and it works fine 👍

**Comment by mde** [comment]
Also worth noting the preprocessor directive style of include is deprecated, and will be going away in a future release.
