### ISSUE TITLE
i think if ejs can nest tags like<% ......<%= ...... %>..... %>,it must be more powerful.

### ISSUE THREAD

**Issue by Lyd9607** [mde/ejs#326]

**Comment by RyanZim** [comment]
My initial impression is that this would be a nightmare to parse; could be wrong, but that's my thought.

**Comment by User4martin** [comment]
For reference #296
The use case in this issue is to add output to the page from within the javascript.

That will be archived by #248 `echo` (So that may need to be extended for escaping.

**Comment by mde** [comment]
Nesting tags would be needlessly complex, and hard to reason about. The most straightforward approach is for templates to have two contexts: the markup context, and the programming language context. I cannot imagine a use-case compelling enough to justify the complexity of going beyond that.

**Comment by JonasDoe** [comment]
A use case: I want to concat a `string` for a component's text, and I want to pass this text to an ejs partial which renders this component.

**Comment by mde** [comment]
There could be other ways to accomplish this: template literals, or even using `ejs.render` from inside an EJS template. Again, a very specific use-case that does not justify adding such complexity directly into EJS.
