### ISSUE TITLE
Ejs Rendering

### ISSUE THREAD

**Issue by jamalabo1** [mde/ejs#330]
When i write <% // code %>
can the client see it in some way? 

* who render the page? browser or server * 

(in php the server render the page and send it to the client, Ejs do the same? )

**Comment by RyanZim** [comment]
@jamalabo1 It depends whether you're using EJS on your server or in the browser.

**Comment by jamalabo1** [comment]
in the server ( nodejs )

**Comment by RyanZim** [comment]
Then it's rendered on the server.

**Comment by jamalabo1** [comment]
and its impossible to see my code?

**Comment by jamalabo1** [comment]
ok, how can I suggest a feature?

**Comment by RyanZim** [comment]
It shouldn't be possible.

**Comment by jamalabo1** [comment]
@Raindal  I want to suggest a new feature!
