### ISSUE TITLE
Is there a way to keep the file extension of ejs file as .js?

### ISSUE THREAD

**Issue by jfoclpf** [mde/ejs#332]
I'm using ejs npm package with expressjs to "render" JavaScript files. According to [this](https://stackoverflow.com/questions/27383222/is-there-a-way-to-keep-the-file-extension-of-ejs-file-as-html) SO answer it is possible to keep the file extension for html files through

```
app.engine('.html', require('ejs').__express);
app.set('view engine', 'ejs'); 
```
I tried

```
app.engine('.js', require('ejs').__express);
app.set('view engine', 'ejs'); 

app.get('/Globals.js', function(req, res) {                 
    res.set('Content-Type', 'application/javascript');
    res.render('Globals.js', { 
        CC : CC,
        LangCode : LangCode
    });
});
```

and it doesn't work (the variables are not parsed). The file Globals.js is already in the views/ folder. When I change to Globals.ejs it does work. Though code editors such as Notepadqq, do not recognise the file as being JavaScript. Any ideas?

**Comment by mde** [comment]
This is some sort of configuration issue with Express, not EJS. EJS itself doesn't care about file extensions. The rudimentary file-loading functionality EJS actually has for server-side use just loads whatever file path it's given. You'll probably have more luck getting help from the Express folks.
