### ISSUE TITLE
Global custom escape function

### ISSUE THREAD

**Issue by mguillau42** [mde/ejs#335]
I am currently trying to set a global custom escape function for ejs in express 4

I tried to do something similar as in https://github.com/mde/ejs/issues/224#issuecomment-274351412
```javascript
const app = express();
const custom_escape = require('./custom_escape');

app.engine('ejs', (path, data, cb) => {
  ejs.renderFile(path, data, {
    escape: custom_escape
  }, cb);
});
```

At the moment `custom_escape` is a copy paste of https://github.com/mde/ejs/blob/334c4e1815ae02b7c431c38e96562ab5431f843a/lib/utils.js#L94
the only difference is that I added a console.log in order to see when it is called.

Here is my problem:

in node:
```javascript
res.render('a');
```
a.ejs
```html
<%= escaped_with_custom_fn %>
<%- include('b') -%>
```
b.ejs
```html
<%= escaped_with_default_fn %>
```

It seems that my custom escape function does not propagate through includes this way, it only escapes
the top level file.
What am I missing and how can my goal be achieved ?

**Comment by mde** [comment]
This is apparently an Express-specific issue. I tried a minimal test with just EJS, and verified that the custom escape function propagates correctly down to multiple levels of include. I am not familiar with this specific syntax for `app.engine`, but maybe you could start there.

**Comment by handongw** [comment]
I tested ejs 2.6.1(from npmjs.org) with just ejs directly w/o. the issue still exist in included .ejs file.
