### ISSUE TITLE
A story, and some explaination...

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs#337]
To @mde and the EJS collaborators:

EJS was one of the first open-source projects I contributed to. I was fairly new to programming at the time, I had just signed up for GitHub, and I stumbled across EJS. At that time, I was doing web design, and I liked EJS as a template engine. I saw there was a lot of unanswered issues on the EJS repo, so I set to work answering them as best I could. I began opening issues for where the docs needed improvement. I hadn't actually made any PRs yet, but I was working on some, when all of a sudden @mde added me as a collaborator: https://github.com/mde/ejs/issues/135#issuecomment-200698041. I was floored. I had never held collaborator rights to any open source project before, and I had no open source projects of my own at the time; and suddenly, I was helping maintain a popular npm library!

That got me into open-source, and I'm now a maintainer of quite a few open source projects. It also got me seriously into Node.js (I had formerly done mostly browser-side JS). Less than a year later, I wound up co-maintaining a popular project with a man who later became my employer (@jprichardson, co-founder of @ExodusMovement). By March, I'll be working there 1 year; and I hope I can enjoy many more years working there as well.

I want to take this moment to personally thank @mde for being the catalyst that sent me down a twisting path that leads to where I am today. I've often thought back to that surprising day when you added me to EJS, and have tried to do the same to other young programmers when I can.

I also want to explain myself a bit. Probably some of y'all have noticed I'm not as active around here as I used to be. The fact is, I'm no longer doing web design, and I haven't actually used EJS for over a year. Overall, I'm quite busy, and so I'm no longer able to give EJS the attention I once did. I'm fine with staying a collaborator here; I'll be glad to answer an issue or two now and then, and offer advice occasionally on PRs; but I simply cannot devote myself to fully maintaining EJS. I don't like doing this, I've been pushing this off for awhile, but if I'm honest with myself, I simply don't have time.

My best wishes for the future of the project; it's been a fun ride!

**Comment by mde** [comment]
@RyanZim Thanks so much for the post. Your help has been invaluable here, and we all know that people work on open source on their own time, and usually without any compensation. This is community-supported software and we all do it when we can. Thanks again so much for all your help and contributions, and I wish you the best of fortune in your current endeavors. (Also know you are not disappearing into the ether -- I'll look forward to your still chiming in from time to time.) 😄
