### ISSUE TITLE
Get Ejs render options client side

### ISSUE THREAD

**Issue by SolmazKh** [mde/ejs#338]
Hello
How may I get the options sent with the render functions in client side?
I want to store them in a variable and use them in client script.

**Comment by carloslfu** [comment]
You can serialize them and get those client side as follows:
```ejs
<html>
<body>
  <script>
    var myOptions = <%= JSON.stringify(options) %>
    // Here you have your options
    console.log(myOptions)
  </script>
</body>
</html>
```

**Comment by RyanZim** [comment]
Closing as per @carloslfu; sorry I missed this originally.
