### ISSUE TITLE
Is there a `pretty` option for EJS-rendered HTML?

### ISSUE THREAD

**Issue by markhealey** [mde/ejs#339]
In Express apps, when using Jade/Pug, you can set `app.locals.pretty = false` to get compressed/minified/whitespace removed HTML. Is there such a thing with EJS? I've searched for over an hour with no luck. `rmWhitespace` either isn't working or not doing what I'm expecting. Thanks!

**Comment by RyanZim** [comment]
There is no such option; you'd have to run an HTML minifier after EJS.

**Comment by markhealey** [comment]
FWIW I ended up using [`express-minify-html`](https://github.com/melonmanchan/express-minify-html) for our Express app and it works like a charm. Config looks like this:

```
if (process.env.NODE_ENV !== "development") {
  app.use(minifyHTML({
    override: true,
    exception_url: [ 
      "/robots.txt"
    ],
    htmlMinifier: {
      removeComments: true,
      collapseWhitespace: true,
      collapseBooleanAttributes: true,
      removeAttributeQuotes: false,
      removeEmptyAttributes: false,
      minifyJS: true
    }
  }));
}
```

**Comment by mde** [comment]
Thanks for sharing!
