### ISSUE TITLE
${var} tags results in an exception 

### ISSUE THREAD

**Issue by eefret** [mde/ejs#340]
I have this problem in a file that templates a `gradle` file, basically it throws this exception:

<img width="442" alt="screen shot 2018-02-07 at 17 06 29" src="https://user-images.githubusercontent.com/863005/35941630-4c4f18be-0c29-11e8-8755-e6175e77b34b.png">

This is the chunk of code:

<img width="502" alt="screen shot 2018-02-07 at 17 04 51" src="https://user-images.githubusercontent.com/863005/35941637-552755a0-0c29-11e8-9308-62f12b5a9676.png">

**Comment by RyanZim** [comment]
Not sure how this is related to EJS?

**Comment by eefret** [comment]
I'm using Yeoman which uses EJS in the background to template the file, all other variables are fine but in that point I describe it breaks, the exception occurs in the line that runs the template, in the Yeoman repo they refer this project EJS as the template library it uses below, so I created the issue here.

**Comment by RyanZim** [comment]
This is either an issue with the generator or with yeoman itself. Closing.
