### ISSUE TITLE
Could not find include

### ISSUE THREAD

**Issue by HofmT** [mde/ejs#342]
Hello,

I have the following app structure:

project:
* partials
   * head.ejs
* views
  * wiki.ejs
  * community
                    * wiki.ejs

Inside my wiki.ejs I include the _partials/head_ with the following include command: `<% include ../partials/head  %>` which works fine.
But if I want to include the _partials/head_ from my _community/wiki.ejs_ with the following command: `<% include ../../partials/head  %>` It says **Could not find include file**. What am I doing wrong?

**Comment by mde** [comment]
I'm not sure what the particular issue is, but that's using the old, deprecated preprocessor directive for `include`. You should likely be using the modern function-call style: `include('path/to/file');` The old style is not supported anymore. I'm going to close this issue -- please feel free to reopen it if the function call doesn't work as you'd expect.

**Comment by mde** [comment]
Ah, could be that you need to set the `root` option so EJS knows where to look for partials.
