### ISSUE TITLE
Can't get basic example working

### ISSUE THREAD

**Issue by RecurrentJS** [mde/ejs#345]
I am just using the client side example from the README:

```
<div id="output"></div>
<script src="/js/ejs.min.js"></script>
<script>
html = ejs.render('<%= people %>', {people: 'hello'});
document.getElementById('output').innerHTML = html;
</script>
```

With just that basic code, I'm getting an error somehow,

> ReferenceError: /Users/owner/Dropbox/answered-client/views/pages/test.ejs:4
>     2| <script src="/js/ejs.min.js"></script>
>     3| <script>
>     4|   html = ejs.render('<%= people %>', {people: 'hello'});
>     5|   document.getElementById('output').innerHTML = html;
>     6| </script>
>     7| 
> 
> people is not defined
>     at eval (eval at compile (/Users/owner/Dropbox/answered-client/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:26)
>     at returnedFn (/Users/owner/Dropbox/answered-client/node_modules/ejs/lib/ejs.js:580:17)
>     at tryHandleCache (/Users/owner/Dropbox/answered-client/node_modules/ejs/lib/ejs.js:223:34)
>     at View.exports.renderFile [as engine] (/Users/owner/Dropbox/answered-client/node_modules/ejs/lib/ejs.js:437:10)
>     at View.render (/Users/owner/Dropbox/answered-client/node_modules/express/lib/view.js:135:8)
>     at tryRender (/Users/owner/Dropbox/answered-client/node_modules/express/lib/application.js:640:10)
>     at Function.render (/Users/owner/Dropbox/answered-client/node_modules/express/lib/application.js:592:3)
>     at ServerResponse.render (/Users/owner/Dropbox/answered-client/node_modules/express/lib/response.js:1008:7)
>     at app.get (/Users/owner/Dropbox/answered-client/index.js:36:7)
>     at Layer.handle [as handle_request] (/Users/owner/Dropbox/answered-client/node_modules/express/lib/router/layer.js:95:5)

Is there something obvious I'm missing?

**Comment by carloslfu** [comment]
Hi @RecurrentJS see [here](https://stackblitz.com/edit/ejs-working-example?file=index.html) for a live working example

**Comment by mde** [comment]
The example posted by @carloslfu works, and I cannot repro this problem on my local machine. I am going to chalk this up to pilot error, but happy to repoen if we can get some more specifics about how this is happening.
