### ISSUE TITLE
ejs website  not working 

### ISSUE THREAD

**Issue by medmin** [mde/ejs#346]
the website: http://ejs.co/

if you click the big button "Get Started"

Nothing happens.

I submitted this issue before([#oldIssue](https://github.com/mde/ejs/issues/322)), but you seem just don't care.

The info of my chrome:
The info of my Chrome is :
Google Chrome is up to date
Version 62.0.3202.94 (Official Build) (64-bit)

Works with Edge and IE. NOT chrome.

**Comment by mde** [comment]
Sincerest apologies for taking so long to get around to fixing this. This should now be fixed. I really appreciate the bug report.

**Comment by medmin** [comment]
@mde  it works now. Thanks.

**Comment by gregbown** [comment]
@mde The link at the top of readme will not load in browser.  If there is some redirect logic that normally handles this, it does not work in Google Chrome.
The link is:
```
https://ejs.co/
```
It only loads if it is:
```
https://www.ejs.co/
```

**Comment by mde** [comment]
I just moved hosting from Firebase to S3, which required the www for the SSL cert. I'll set up a redirect. Thanks for reporting this!
