### ISSUE TITLE
ejs  =>  for loop can't working 

### ISSUE THREAD

**Issue by tynorr** [mde/ejs#347]
It does not work when use the condition of the smaller than and bigger than .

I am listed variable with foreach loop : 
```
<% todos.forEach(function(todos) { %>
     < li >
        <%= todos.item %> -                              
   < /li >
  <% }); %>
```

I cannot list variable with for loop :
```
<% for( var i=0; i < todos.lenght; i++) { %>
     < li >
          <%= todos[i] %>
    < /li >
<% } %>

```
I uninstall and install nodejs and ejs many times. but it is not fix. Pleas help me about this problem. Thanks.

**Comment by RyanZim** [comment]
You have a typo `i < todos.lenght` should be `i < todos.length`

**Comment by tynorr** [comment]
:D Thanks.  can not see any little mistakes when I work for a long time.

**Comment by RyanZim** [comment]
No problem; sometimes we all need a second pair of eyes.

**Comment by anurag472** [comment]
Ryan zim I have been working on this since 2 hrs, thanx you saved me
