### ISSUE TITLE
Caching <%- include %>

### ISSUE THREAD

**Issue by BamItsPixel** [mde/ejs#348]
In my application, there are a couple of particular includes that are somewhat expensive to compute but always return the same HTML.

How would one cause certain calls, i.e. include("x") and include("y") to be cached?

**Comment by akshaygagal** [comment]
Try this:
    <%- include(index) %>

**Comment by BamItsPixel** [comment]
Yeah that’s what I’m using at the moment but my question is about caching. Say I have <%- include(“file-the-output-of-which-never-changes-or-not-very-often-anyway”), is it possible to cache the output of such a file in includes?

**Comment by mde** [comment]
If you use the `cache` option, EJS will cache the function object for compiled templates, so you're only left with the cost of running that function to render the template.

There's no built-in way to cache the rendered output, but you could easily pre-render those sections, save the HTML string in a variable, and pass those down for use in your templates.

This doesn't seem like a use-case that the majority of users would need, and saving rendered content in a local var seems like a reasonable workaround, so I'm going to close this issue.
