### ISSUE TITLE
deficient error message 

### ISSUE THREAD

**Issue by crafter999** [mde/ejs#353]
I was trying to include some template files on my application but suddenly I made a typo mistake while I was trying to include an invalid ejs file? First of all why the build files have major differences with  the source files and secondly wouldn't be better if we declare which file could not be included instead
of just throwing this confusing error "Could not find include include file."
~~~
{ Error: ./index.ejs:15
    13|   <body>
    14| 
 >> 15|     <%- include('headxer.ejs') %>
    16| 
    17|     <h1>
    18|         Hello <%= user %>!

Could not find include include file.
~~~
The dist files differ from the actual source files as you can see here
build
```
    if (!includePath) {
      throw new Error('Could not find include include file.');
    }
```
src
```
    if (!includePath) {
      throw new Error('Could not find the include file "' +
          options.escapeFunction(path) + '"');
    }
````

**Node Version 9.30
EJS Version 2.5.7
OS Linux/Windows**

**Comment by mde** [comment]
Yes, the master branch was ahead of the current release. I've published a new version to NPM (v2.5.8), which includes that fix for filenames in errors.
