### ISSUE TITLE
Does ejs support loading a file of different type?

### ISSUE THREAD

**Issue by klvenky** [mde/ejs#356]
I am using mjml and ejs to create some html email templates. So, I have a block of code where I am trying to include a mjml file from another.
-* All the files are in the same folder

Following is my code
`
// ... Some code
const file = // Reading using another module 
const mjml = ejs.render(file, { data }, 'strict');
// ... Some code

**home.mjml**

// ... some markup
	  <%= include('./table.mjml', { data } ) %>
// ... some markup

**table.mjml**

<% const currCol = data.cols %>
<% const colsLen = currCol.length %>
<% const currRows = data.rows %>
<% const rowsLen = currRows.length %>
<mj-table width="600px">
  <tr style="border-bottom:1px solid #ecedee;text-align:left;padding:15px 0;">
    <% for(j=0; j<colsLen; j++) { %>
      <th style="padding: 0 15px;">
        <%= currCol[j].name %>
      </th>
      <% } %>
  </tr>
  <% for(j=0; j<rowsLen; j++) { %>
    <tr>
      <% for(k=0; k<colsLen; k++) { %>
        <td style="padding: 0 15px;">
          <%= currRows[j][k] %>
        </td>
        <% } %>
    </tr>
    <% } %>
</mj-table>
`

I get an error saying as below :
`Could not find include include file. Error: ejs:32`

I am using `ejs@^2.5.7`. I would like to know if this is possible in current version of ejs.

**Comment by mde** [comment]
Not sure if this is the problem, but `ejs.render` takes a template string, not a filename, as its initial arg. You probably want `renderFile` for this. (Also, the final arg should be an options Object, not a string -- `{strict: true}`.)

Also, EJS does not care what file extension you use, as long as the contents are valid EJS. If you're loading include files using relative paths, you might need to set `options.root` to tell EJS where to look. The routine for looking them up isn't super sophisticated, but it will try to do the obvious right thing when it can:

https://github.com/mde/ejs/blob/master/lib/ejs.js#L134

**Comment by klvenky** [comment]
@mde thanks for the update. I figured out that it was not able to find the current directory to check the mentioned file for and I have used process.cwd() for the same.
It's working now. I would try using the options.root once.

Cheers
