### ISSUE TITLE
rmWhitespace option not getting passed to ejs with express 4.x

### ISSUE THREAD

**Issue by watanas** [mde/ejs#358]
I'm running ejs@2.5.8 with express@4.16.3. I tried setting the rmWhitespace option:
```
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.locals.rmWhitespace = true;
```
My generated html file does not have whitespace removed. However, if I edit lib/ejs.js around line 463 so that it runs `utils.shallowCopyFromList(opts, data, _OPTS_EXPRESS);` even for express 4.x, then I get the correct behavior. Is there a correct way to set the rmWhitespace option, or is this a bug?

**Comment by applefreak** [comment]
Also experiencing this, I used to do `app.set('view options', { rmWhitespace: true });` on `2.5.6` and it works. But with `2.5.8` this breaks.

**Comment by mde** [comment]
This should be fixed in master now. Can you please verify that it's working as expected? If so, I'll push out a new version to NPM.

**Comment by applefreak** [comment]
@mde Yup, just tried master, it works. Thanks!

**Comment by mde** [comment]
Excellent, I'll publish to NPM. Thanks so much for your patience.

**Comment by mde** [comment]
Pushed to NPM, v2.5.9.
