### ISSUE TITLE
options found in locals object. The option(s) is copied to the option object. This behavior is deprecated and will be removed in EJS 3

### ISSUE THREAD

**Issue by dgofman** [mde/ejs#36]
Why locals is deprecated, any workaround in the future?

```js
function cpOptsInData(data, opts) {
  _OPTS.forEach(function (p) {
    if (typeof data[p] != 'undefined') {
      if (!optInDataWarned) {
        console.warn('options found in locals object. The option(s) is '
                   + 'copied to the option object. This behavior is '
                   + 'deprecated and will be removed in EJS 3');
        optInDataWarned = true;
      }
      opts[p] = data[p];
    }
  });
}
```

**Comment by TimothyGu** [comment]
It is not deprecated, but you are putting locals in the options object. *That* is deprecated.

If you are using express, there is no workaroudn right now.

If you are calling ejs directly, split locals and options into two objects and call `render(str, locals, options)` or `renderFile(str, locals, options, fn)` or `compile(str, options)(locals)`.

**Comment by dgofman** [comment]
Now I have error

node_modules/ejs/lib/ejs.js:213
      cb(err);
      ^
TypeError: object is not a function
    at handleTemplate (/Users/dgofman/git/indigojs/node_modules/ejs/lib/ejs.js:213:7)
    at /Users/dgofman/git/indigojs/node_modules/ejs/lib/ejs.js:235:7
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)

**Comment by TimothyGu** [comment]
@dgofman How did you call `renderFile()`?

**Comment by dgofman** [comment]
before it was 
ejs.render(fs.readFileSync(filename, 'utf-8'), req.model);

now
ejs.render(fs.readFileSync(filename, 'utf-8'), null, req.model);

**Comment by TimothyGu** [comment]
@dgofman This is definitely not the error, but are you sure `req.model` contains options and not locals? Look for `renderFile` in your source. It should be the one causing the problem.

**Comment by dgofman** [comment]
I don't see renderFile working either

ejs.renderFile(req.model.filename, null, req.model);

Tell me please what is 'locales' parameter and why do we need it? Before it was only two

Plus my options using "locales" key

ejs.renderFile("foo.html", {locales: {"hello":"HELLO", "bye":"BYE"});

foo.html

<html>
<span><%= locales.hello%></span>
<span><%= locales.bye%></span>
</html>

It was working before now is giving me warning. How can I avoid warning?

**Comment by TimothyGu** [comment]
@dgofman No, I meant that it is probably `renderFile` that caused the problem. I am not asking you to use it.

The reason why you see the error is because `renderFile()` has a mandatory callback option, you you are not setting.

**Comment by dgofman** [comment]
But I need "Sync" version of "renderFile" or "ejs.render". I am using "Function->String"

I am calling function from HTML

Node sample:

app.locals.inject = function(req, url) {
        return ejs.render(fs.readFileSync(url, 'utf-8'), req.model);
};

Template sample:

<!DOCTYPE html>
<head>
<%- inject(req, 'templates/head.html') %>
<script>

**Comment by TimothyGu** [comment]
I am fairly sure your app is not crashing in `inject()`, but rather somewhere else.

**Comment by dgofman** [comment]
No, its was working fine but now you are killing this nice feature

https://github.com/dgofman/indigojs/blob/master/indigo.js#L191

**Comment by dgofman** [comment]
100% uinttests and code coverage

**Comment by TimothyGu** [comment]
@dgofman Seems to me that it's crashing here: https://github.com/dgofman/indigojs/blob/master/indigo.js#L265

**Comment by dgofman** [comment]
Its not crashing its giving me console output with latest updated of EJS but before today I didn't have that issue

options found in locals object. The option(s) is copied to the option object. This behavior is deprecated and will be removed in EJS 3

**Comment by dgofman** [comment]
https://github.com/dgofman/indigojs/commit/8cf7d2f648018ac7d628d1fbb5d31dbee08d7b1c

I updated today only one package

-    "ejs": "~2.1.4",
+    "ejs": "~2.2.1",

**Comment by dgofman-equinix** [comment]
@TimothyGu any workarounds how can I get ejs.render or ejs.renderFile synchronously. May be you can add additional functions (like fs library) ejs.syncRender or ejs.syncRenderFile that may help for all EJS developers.
Thanks,
David

**Comment by TimothyGu** [comment]
@dgofman-equinix `ejs.render` is synchronous, and `ejs.renderFile` is async. Just like fs.

**Comment by dgofman-equinix** [comment]
Do in this case why i need to pass callback? or additional attribute "locals" render(str, locals, options)

**Comment by TimothyGu** [comment]
@dgofman-equinix You don't pass cb to `render`, only to `renderFile`.

**Comment by dgofman-equinix** [comment]
that exactly how is my code looks like, but why I have deprecated warning in this case?

**Comment by TimothyGu** [comment]
If you are using express, then you are probably affected by #34 / #37.

**Comment by dgofman-equinix** [comment]
Yes I am using latest express module and didn't see that warning when used EJC version 2.1.4.
Should use this version ONLY in the future?

**Comment by dgofman-equinix** [comment]
@TimothyGu I have another question. Do you have an option to display a "key" if is undefined

Example: right now in my HTML Bind appName key 

<label>Hello <%= locales.common.user %></label>

Because I didn't defined value for this key on the browser I got 
"Hello undefined"
I would like to see what key is missing in that case I will prefer output like this
"Hello locales.common.user" OR "Hello <%locales.common.user%>"

Thanks

**Comment by TimothyGu** [comment]
The current version of EJS outputs `''` for undefined or null variables. You are using an old version. There is no way to change the behavior.

**Comment by dgofman-equinix** [comment]
Yes I have to pinned your old version "ejs": "2.1.4", https://david-dm.org/dgofman/indigojs
Actually "express" doing the same. I don't think replacing undefined by empty string is good workaround. Developers may defined many bind keys and if you will not provide information some key(s) are invalid it even worse than "undefined"

**Comment by mde** [comment]
Express generators should be using "~2.1.4", which will pick up the minor version bump that fixes this problem: https://github.com/expressjs/generator/commit/3a987d261c6531c79fae4515ab5fbbb1d33fc3f0 (Of course, apps generated with the generator prior to the fix might have the old version installed.)

It doesn't replace the undefined value. All it does is *output* an empty string (that is to say, it outputs nothing) for any expression in an output-tag (<%= or <%-) whose result is `null` or `undefined`. This is the same behavior as EJS 1.x.

**Comment by dgofman-equinix** [comment]
I am fine with "undefined" but still cannot use latest EJS because I am using "express.locales" and cannot find any alternate way to avoid warnings after your changes

function cpOptsInData(data, opts) {
  _OPTS.forEach(function (p) {
    if (typeof data[p] != 'undefined') {
      if (!optInDataWarned) {
        console.warn('options found in locals object. The option(s) is '
                   + 'copied to the option object. This behavior is '
                   + 'deprecated and will be removed in EJS 3');
        optInDataWarned = true;
      }
      opts[p] = data[p];
    }
  });
}

**Comment by dgofman-equinix** [comment]
and is not just me 

http://superbigtree.tumblr.com/post/62759231807/a-simple-example-application-using-express-ejs
http://stackoverflow.com/questions/16452123/how-to-create-global-variables-accessible-in-all-views-using-express-node-js
http://truongtx.me/2014/03/19/nodejs-with-express-more-advanced-stuff

**Comment by mde** [comment]
This is fixed in the latest version: https://github.com/mde/ejs/releases/tag/v2.2.2 Here is the commit: https://github.com/mde/ejs/commit/3134613044c4b11852dc250ff4d52705cf54ede5

It does not fix it for direct use of `renderFile`, but it does remove the deprecation notice when called via the `__express` export.

**Comment by dgofman-equinix** [comment]
I am not using renderFile (only ejs.render) and still getting the same waning using v2.2.2

options found in locals object. The option(s) is copied to the option object. This behavior is deprecated and will be re
moved in EJS 3

**Comment by mde** [comment]
Ugh, can you give me steps to repro?

**Comment by dgofman-equinix** [comment]
Just download latest version https://www.npmjs.com/package/indigojs
change package.json under.node_modules/indigojs
"ejs": "2.1.4"
to
"ejs": "~2.2.2"
run "npm install"
than "npm start"
open browser when go to url "localhost:8125" the funny part this warning showing ONLY ONCE!!!!

**Comment by mde** [comment]
Thanks for catching this. Looks like there are subsequent direct calls to `render` after it access the `__express` export. a3cd2c8508ef39cb998add20ec96a25141023328 handles this case. I've pushed an update to NPM, v2.2.3. Thanks for catching this!

**Comment by dgofman-equinix** [comment]
No problems, thanks for fixing that issue I would like to continue using latest EJS.
Good luck!

**Comment by mde** [comment]
:+1:
