### ISSUE TITLE
Complex EJS rendering

### ISSUE THREAD

**Issue by Rajan** [mde/ejs#364]
I'm using a home.ejs and it has a function which needs to be called on the client side. I've also included ejs.min.js as a script.

```
function renderPosts() {
	let people = ['geddy', 'neil', 'alex'],
    	html = ejs.render("<%= people.join(', '); %>", {people: people});
    	document.getElementById('output').innerHTML = html;
}
```

I want `<%= people.join(', '); %>` to be executed after fetching results on page load and not on the server side where people variable won't yet be defined. What is the best approach to do this?

**Comment by meesfrensel** [comment]
I believe you're looking to output literal tags. Though I haven't tested it, this should do the trick:
```javascript
function renderPosts() {
    let people = ['geddy', 'neil', 'alex'],
    html = ejs.render("<%%= people.join(', '); %%>", {people: people});
    document.getElementById('output').innerHTML = html;
}
```
When rendering on the server side, the tags will be 'reduced' to plain `<%=` and `%>`, which can be rendered client-side.

**Comment by mde** [comment]
Ah, so using EJS to generate EJS. The literal tag is one way to do it -- the other way is to use a custom delimiter on one side or the other.

I'm going to close this issue -- seems like it's resolved.
