### ISSUE TITLE
Render EJS partial client side after ajax call

### ISSUE THREAD

**Issue by richlewis14** [mde/ejs#369]
Hi

How can I render an EJS partial via the client (that will loop through the json array after data is returned from an ajax call).

At present I have this in my home.ejs file

    <script src="js/ejs.min.js"></script>

    $.ajax({
      url: '/league_fixtures',
      type: 'POST',
      dataType: "json",
      data: { league_name: league_name },
      success: function(fixtures){
        var fixtures = JSON.stringify(fixtures.fixtures);
        //[{"id":79,"home_team":"Persepolis","away_team":"Al Jazira SC","kick_off":"16:00","league_name":"AFC Champions League"},{"id":132,"home_team":"Al Ahli Jeddah","away_team":"Al-Sadd SC","kick_off":"18:40","league_name":"AFC Champions League"}]
        
        var html = ejs.render(`<%%- include /partials/fixtures %%>`, { fixtures: fixtures} );
        $('#panel_' + league_name.replace(/[\s.]/g,'')).html(html);

I notice i had to add `<%%` to get it to recognise that i had an include statement. But i keep getting `exports.fileLoader is not a function` . So it can find my fixtures file but i still get this error

Am i approaching this correctly or should i be doing this a different way?

Thanks guys

**Comment by mde** [comment]
Browsers do not have access to the filesystem, and cannot load files. If you are using EJS client-side, the `include` feature does not work. It's a server-side-only feature. (You could theoretically define a `fileLoader` for your own client-side use that fetches partials, but that would be horribly inefficient, and not really practical for production use.)

**Comment by richlewis14** [comment]
Thanks for responding so quick, so with what you have said (silly of me not to realise that), is there a way to just render a partial server side after an ajax call ?
