### ISSUE TITLE
Parse error (package.json must be actual JSON, not just JavaScript)

### ISSUE THREAD

**Issue by uluawebdev** [mde/ejs#381]
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v6.14.2/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v6.14.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   'ejs',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.14.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Finishing
10 silly install printInstalled
11 verbose stack Error: Failed to parse json
11 verbose stack Unexpected token 't' at 8:6
11 verbose stack     "test": "echo \"Error: no test specified\" && exit 1"
11 verbose stack      ^
11 verbose stack     at parseError (/home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
11 verbose stack     at parseJson (/home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
11 verbose stack     at /home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
11 verbose stack     at /home/ec2-user/.nvm/versions/node/v6.14.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
11 verbose stack     at tryToString (fs.js:457:3)
11 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
12 verbose cwd /home/ec2-user/environment
13 error Linux 4.14.33-51.37.amzn1.x86_64
14 error argv "/home/ec2-user/.nvm/versions/node/v6.14.2/bin/node" "/home/ec2-user/.nvm/versions/node/v6.14.2/bin/npm" "install" "ejs" "--save"
15 error node v6.14.2
16 error npm  v3.10.10
17 error file /home/ec2-user/environment/package.json
18 error code EJSONPARSE
19 error Failed to parse json
19 error Unexpected token 't' at 8:6
19 error     "test": "echo \"Error: no test specified\" && exit 1"
19 error      ^
20 error File: /home/ec2-user/environment/package.json
21 error Failed to parse package.json data.
21 error package.json must be actual JSON, not just JavaScript.
21 error
21 error This is not a bug in npm.
21 error Tell the package author to fix their package.json file. JSON.parse
22 verbose exit [ 1, true ]

**Comment by mde** [comment]
Looks like your error is in something called "environment," not EJS:

```
20 error File: /home/ec2-user/environment/package.json
```
