### ISSUE TITLE
Can I use es6 syntax inside code sections?

### ISSUE THREAD

**Issue by grofit** [mde/ejs#382]
I am trying to use ES6 syntax inside code sections i.e:

```
<%
   const something = `${a + b}`;
%>

<div><%=something%></div>
```

At the moment it blows up saying unexpected token const, this was working fine when I was using lodash template (which I believe is almost a 1-1 with EJS) so was wondering if this is allowed or not?

**Comment by mde** [comment]
Yes, EJS is just plain JavaScript, and will support whatever features your JS runtime does. When I try your above code, I get the (expected) error of `a is not defined`. (You haven't defined either `a` or `b`.) When I define `a` and `b` properly, the code runs correctly:

```javascript
> let templ = '<% let a = "x", b = "y"; const something = `${a + b}`; %><%= something;  %>';
'<% let a = "x", b = "y"; const something = `${a + b}`; %><%= something;  %>'
> ejs.render(templ);
'xy'
```
