### ISSUE TITLE
Embedding es6 template literals (like lodash template)

### ISSUE THREAD

**Issue by grofit** [mde/ejs#383]
I cannot find much info on it other than a slightly related template literal in functions thread which seemed to turn into a flame war or something.

So Lodash template (which I believe is almost 1-1 in terms of functionality) supports the usage of embeded literals as a shortcut for `<%=blah%>`, so for example if I had a template file like:

```
<%=name%> is the same as ${name}
```
In Lodash if I were to pass in "bob" I would get `bob is the same as bob` but here I get `bob is the same as ${name}`.

I am happy to just accept this functionality doesnt exist if there is a reason why, but it would be a nice addition as a shorthand for `<%= %>`.

**Comment by mde** [comment]
The main reason this functionality doesn't exist is that supporting completely different, non-EJS syntax adds complexity and makes it harder to maintain EJS. (Edge-cases and exceptions are things you always end up tripping over and having to code around.) I'm not sure why Lodash does this (maybe it has a smaller feature-set than EJS?), but you could also ask why Handlebars or Pug don't support EJS syntax. 😄 

It's also trivial to perform a global replace on your template yourself, as a pre-processing step, if you're really dead-set on using that type of variable-interpolation syntax:

```javascript
let templateText = '${foo} and ${bar} and ${baz}';
templateText = templateText.replace(/\$\{([^\}]+)\}/g, '<%= $1 %>');
```

**Comment by wstam88** [comment]
You could do: `<%= `${name} is the same as ${name}` %>`

**Comment by mylastore** [comment]
I have this can someone point me on a way to transpile this to javascript any plugins? I am using webpack with gulp.
 
`<%- `model.displayCity, model.displayState` %> `
