### ISSUE TITLE
Can error message include which field is undefined for easy debug?

### ISSUE THREAD

**Issue by yuwu9145** [mde/ejs#384]
When doing ejs template rendering, for example <% if (data.a.b) { %>, if a is undefined, then the render will fail, err object only returns which template failed, but not returning errors like 'cannot get b from an undefined object', which makes debug really hard when binding data is huge.

**Comment by joeskeen** [comment]
For my similar use case I wanted to never fail silently, but always blow up if the template is requesting a value that does not exist. I used a `Proxy` object to recursively check for the existence of a property and throw a descriptive error message if it's missing:

```js
import './style.css';
import { compile } from 'ejs';

function renderTemplate(template, context) {
  function createProxy(original) {
    return new Proxy(original, {
      get(target, name, receiver) {
        if (Reflect.has(target, name)) {
          let rv = Reflect.get(target, name, receiver);
          if (typeof rv === 'object') {
            return createProxy(rv);
          }
          return rv;
        }
        throw new Error(`Missing required property ${name}`);
      },
    });
  }

  const proxy = createProxy(context);
  const fn = compile(template);
  return fn(proxy);
}

const template = `
Hello <%= locals.name %> <%= locals.lastName %>
`;
const context = { name: 'bob' };
const output = renderTemplate(template, context);
```

The last line throws this error:

```
Uncaught Error: ejs:2
    1| 
 >> 2| Hello <%= locals.name %> <%= locals.lastName %>
    3| 

Missing required property lastName
    at Object.get (main.js:15:15)
    at eval (eval at compile (ejs.js?v=3873bcb3:563:16), <anonymous>:14:33)
    at anonymous (ejs.js?v=3873bcb3:587:21)
    at renderTemplate (main.js:22:10)
    at main.js:31:13
```

See it in action: <https://stackblitz.com/edit/vitejs-vite-v8gaq6?file=main.js>

Hope this is helpful for someone out there.

**Comment by mde** [comment]
@joeskeen, good way to handle this kind of issue. EJS is just ordinary JavaScript evaluation — that's the whole point. And JS gives you all kind of tools for checking data either before you render, or in your solution, as rendering is occurring.
