### ISSUE TITLE
File usage is broken (html vs. ejs)

### ISSUE THREAD

**Issue by Eta92** [mde/ejs#385]
Hello,

I lost half an hour searching why my index.ejs did not update, and I found that my server was using the index.html file instead.
I would agree that calling index "res.render('index');" catch the index.html but this is not the case. I told the server to take explicitly ejs file "res.render('index.ejs');".

I feel there is something odd there, why the library ignore the extension I am asking for ?

**Comment by mde** [comment]
Anything to do with `res.render` is an issue with Express. I'm not sure how Express decides what file extensions to look for -- maybe it bases this on what view engine you have set. I'm not really sure. You'll need to ask some people in the Express community. This is not an EJS issue.

**Comment by Eta92** [comment]
Thank you, I'll address them this issue.
