### ISSUE TITLE
Unicode escape issue

### ISSUE THREAD

**Issue by DandyBrandy** [mde/ejs#386]
Ejs is escaping emoji character twice which causes the resulting ampersand to also be escaped.

```
app.get('/', function (req, res){
    res.render("index.ejs", {testEmoji: "🐊"});
});
```

View:
```
<h1><%= testEmoji %></h1>
```
Inspecting it in the browser:
```
<h1>&amp;#x1F40A</h1>
```

I expect the resulting HTML to be `&#x1F40A;` but I got `&amp;#x1F40A`. It has escaped the ampersand and it doesn't end in a semi-colon.

**Comment by michaelwangbh** [comment]
You can use `<%- %>` for unescaped raw output so the ampersand is not escaped.

**Comment by mde** [comment]
Cannot repro with a minimal example:

```
let ejs = require('./lib/ejs');
> ejs.render('<%= emoj; %>', {emoj: '🐊'});
'🐊'
```
This looks like an Express is re-escaping, or possibly double-escaping. EJS on its own isn't escaping emoji at all.
