### ISSUE TITLE
Add support for compile-time `with()`

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#39]
One of the major bottlenecks in the execution of template functions is the use of `with () {}` construct, which is not even supported in JavaScript strict mode. To work around this, some (most of my performance-critical) projects use the `_with` option to disable the use of `with () {}` in template scripts and use `locals.variable` instead of `variable` in EJS files.

Recently, it has come to my attention that there is a module [`with`](https://github.com/ForbesLindesay/with) that scans the source for undeclared variables and adds a shim for it, all at compile-time. This has two major effects and one side effect:

1. compile speed is a **lot** slower
2. runtime speed is a **lot** faster
3. undeclared variables are not recognized as errors but instead resolve to `undefined`, which then resolve to the empty string

Compilation benchmark:

```
ejs v2 old x 28,709 ops/sec ±0.09% (101 runs sampled)
ejs v2 new x 1,343 ops/sec ±1.83% (96 runs sampled)
```

(21 x slower)

Template benchmark:

```
ejs v2 old x 160,036 ops/sec ±1.11% (100 runs sampled)
ejs v2 old !_with x 680,884 ops/sec ±0.43% (98 runs sampled)
ejs v2 new x 631,878 ops/sec ±0.40% (102 runs sampled)
ejs v2 new !_with x 675,687 ops/sec ±0.46% (100 runs sampled)
```

(395% old, 94% `!_with`)

I am certainly against enable this by default, as the performance regression caused by it is way too big. But do people think it's worth adding an option for? Also how about implicitly enabling this option when caching is enabled?

Note that the `with` module uses acorn, which might be undesirable for users using the browser to render EJS, but I can easily use a conditional to filter that out when `browserify`ing.

**Comment by mde** [comment]
The perf hit is pretty big, and I'm even more concerned about the big change to runtime behavior. EJS is literally embedded JavaScript, and transparently ignoring undeclareds in a template would be very surprising behavior. I don't have a problem with explicit opt-in, if the amount of added complexity to the code isn't huge, but implicitly enabling it in any case would frustrate a lot of people.

**Comment by TimothyGu** [comment]
> but implicitly enabling it in any case would frustrate a lot of people.

That I agree. I don't have a strong opinion on this anyway as I don't use `with`.

**Comment by TimothyGu** [comment]
After thinking about this a little bit more, I guess the tradeoff is not worth it, so closing.

**Comment by mde** [comment]
:+1:
