### ISSUE TITLE
Output string containing '\n' as plain text

### ISSUE THREAD

**Issue by pierreburton91** [mde/ejs#395]
Hi,
My server is sending me a string containing "\n" characters.
I'm trying to output that string in my template as **plain text** to use in my js file.
However, whatever I trie, the \n is parsed  and fails the js.

Here's an example:
``` Javascript
console.log("<%= myString %>");
// Should render "my string\nother string"

/* Actual render is :
"my string
other string"
*/
```

I tried <%= and <%- but nothing changes.
Is there any way to do this ?

**Comment by RyanZim** [comment]
`myString` needs to be `\\n` for literal `\n` IIRC

**Comment by pierreburton91** [comment]
Thank you @RyanZim !
Fixed it using replace method.

``` ejs
<%= myString.replace(/\n/g, '\\n') %>
```
