### ISSUE TITLE
<script src="/js/some_script.js"></script> are silently removed during rendering *.ejs

### ISSUE THREAD

**Issue by yarick123** [mde/ejs#399]
Hello,

I am new to ejs and cannot not found an explanation of this behavior.
All `<script src="/js/some_script.js"></script>` tags are silently removed from the rendered non-layout ejs templates. I have a project to support, where this problem is "solved" by using non HTML-conforming self closing script tag: `<script src="/js/some_script.js" />`.

How can be a script-reference included into a non-layout ejs template and be rendered?
Is the described behavior a bug or a feature?

Best regards
yarick123

**Comment by wstam88** [comment]
Do you have a code sample?

**Comment by yarick123** [comment]
I have just tried to create a dry sample. It has worked. So I think, there are some conditions causing this situation in the project I am working for. I will try to find the conditions and to create a "not working" sample  :)

**Comment by yarick123** [comment]
Sorry, I could not create a dry sample. If I extract this behavior from the project, I will reopen the issue.
