### ISSUE TITLE
EJS Rethrow Function Memory Leak

### ISSUE THREAD

**Issue by m-majetic** [mde/ejs#401]
I am testing this simple app on Ubuntu 18.04 with EJS version 2.6.1 and Express.js version 4.16.3 .

![memleakservercode](https://user-images.githubusercontent.com/36574853/45919649-e02aae00-be98-11e8-8c51-77acf7224c9f.jpeg)

The home.ejs file is in a folder called home which is located in the views directory.
Contents of the .ejs files are the following: 

![memleakejscode](https://user-images.githubusercontent.com/36574853/45919658-17995a80-be99-11e8-8f38-0f51df784470.jpeg)

I was investigating a memory leak in another app and decided to test it in the simplest manner possible.
Then, I made this app and the memory leak persists.
Testing for memory leakage was realized using node --inspect and expose GC flags.
User simulation was achieved using Siege.
The results: 

![memleak](https://user-images.githubusercontent.com/36574853/45919686-ae661700-be99-11e8-8cb8-80c48dff7ee9.jpeg)
 
Memory is constantly getting allocated to EJS strings, but the strings are never Garbage collected.

Am I missing something in my code, or is this ejs package related ?

**Comment by mde** [comment]
This looks like a much more helpful example than what we have previously gotten here: https://github.com/mde/ejs/issues/359#issuecomment-423811695 It might help us narrow things further, although it could very well involve the way that EJS is integrated into Express. We don't see this issue with a minimal script that does nothing but `require` EJS, and render.

**Comment by m-majetic** [comment]
Interesting...
I will test this same simple app, but with older versions of express to see if we can pinpoint the update that caused this.
After that I think we should contact Express developers to see how is the ejs view engine treated and why are the references still present.

**Comment by m-majetic** [comment]
Hey, I suspect the problem is not EJS related. This is something on the express side.
I did the same experiment with pug...and would you know:

![pugmemleakchrome2](https://user-images.githubusercontent.com/36574853/45964168-4fcda400-c025-11e8-98f3-ed4c0a54a066.jpeg)

This is the server configuration and the pug file itself.
![pugmemleakserver](https://user-images.githubusercontent.com/36574853/45964202-670c9180-c025-11e8-8f40-190a6fea0ecd.jpeg)
![memleakpugfile](https://user-images.githubusercontent.com/36574853/45964207-6d027280-c025-11e8-85fa-24baa3a4f04e.jpeg)

**Comment by m-majetic** [comment]
Looks like the problem was something under my nose the whole time...
Sorry to bother you.

https://github.com/expressjs/express/issues/3751#issuecomment-424077960
