### ISSUE TITLE
How does ejs.compile resolve the path of include?

### ISSUE THREAD

**Issue by baijunjie** [mde/ejs#402]
Files:
```
ejs/styles.ejs
ejs/template.ejs
```

template.ejs:
```ejs
<%- include('styles') %>
<h1>Hello ejs</h1>
```

Example
```js
const templatePath = path.resolve(__dirname, './ejs/template.ejs');
const templateStr = ejs.fileLoader(templatePath, 'utf8');
const template = ejs.compile(templateStr, { root: path.dirname(templatePath) });
template(data); // => Error
```

Error
```
Error: ejs:1
 >> 1| <%- include('styles') %>
    2| 
...
Could not find the include file "styles"
...
```

How does `ejs.compile` resolve the path of `include` ?

**Comment by baijunjie** [comment]
I know the solution, Use `filename` instead of `root`
```
const templatePath = path.resolve(__dirname, './ejs/template.ejs');
const templateStr = ejs.fileLoader(templatePath, 'utf8');
const template = ejs.compile(templateStr, { filename: templateStr });
template(data); // => successful
```
However, I feel this is a stupid way to write, why can't `ejs.compile` pass in the file path directly?

**Comment by baijunjie** [comment]
Example
```js
ejs.compileFile = function(filePath, options) {
    let templatePath = filePath;
    if (options && options.root) templatePath = path.resolve(options.root, templatePath);
    const templateStr = ejs.fileLoader(templatePath, 'utf8');
    options = Object.assign({ filename: templatePath }, options);
    return ejs.compile(templateStr, options);
}

const template = ejs.compileFile(templatePath);
```

**Comment by mde** [comment]
`compile` does pass a file path for the top-level template to use. And there are a bunch of different possible methods for looking up possible locations for includes within a template (relative to some root, relative to the location of the current template, somewhere up the current directory path all the way up to some root, etc.). The implementation of `resolveInclude` that EJS ships with is deliberately minimal, but you can override it to have whatever behavior you want. There are also security concerns with `include`, wanting to prevent people from accidentally allowing someone to execute arbitrary code that lives outside the Web app directory. Hope this explains the current implementation. If you have specific concerns, or want to suggest improvements that don't significantly increase the size of the code, please feel free to re-open this issue.
