### ISSUE TITLE
require.extensions is not supported by webpack

### ISSUE THREAD

**Issue by sylar-liutao** [mde/ejs#412]

**Comment by mde** [comment]
This was ported over from v1, and I've never liked that we implemented it. I knew it would eventually cause issues. We should really just remove it. Given that it's not a documented feature, we can deprecate it in one minor version, then remove it in the next.

**Comment by zhiquan-yu** [comment]
I made an ejs-loader for webpack，this warning is so noisy.

![screen shot 2018-12-11 at 15 32 13](https://user-images.githubusercontent.com/8205415/49785075-41587400-fd5a-11e8-8abf-f89d580c2516.png)

**Comment by trycontrolmymind** [comment]
Also waiting this issue to be done...

**Comment by mde** [comment]
Deprecation notice added in v2.7.1. I'll push yet another minor version with it removed, in just a couple of weeks. Thanks for the gentle nudge on this!

**Comment by gitTerebi** [comment]
Any update on this? Can you push an update to have the warnings removed?

**Comment by ExE-Boss** [comment]
This is a breaking change, so it should be done in v3.

**Comment by mde** [comment]
@ExE-Boss: This has always been an undocumented feature. The current semver spec states re. major version: "Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API." This has never been part of the public API.

**Comment by mde** [comment]
Ah, shit. It's not documented, but there was a test for it. I think I will remove the preprocessor include as well, and release a v3. It's time to get rid of some of this old baggage.

**Comment by mde** [comment]
I have pushed v3 to NPM, fielding a few complaints, as would be expected. Thanks very much for your patience with this.
