### ISSUE TITLE
can't stop caching

### ISSUE THREAD

**Issue by theonlygusti** [mde/ejs#417]
I want to disable ejs cache

I saw I can use

    ejs.clearCache()

but I have to have an instance of `ejs` for that, atm I am just using

    app.set('view engine', 'ejs');

so I don't know how to force clear the ejs cache ( ideally I will stop it caching altogether).

----

    app.disable('view cache');

didn't work

**Comment by mde** [comment]
Is that the documented way to disable the view cache in Express? What version of Express is this?

**Comment by theonlygusti** [comment]
@mde http://expressjs.com/en/api.html#app.settings.table

express 4.16.4

**Comment by mde** [comment]
There's no reference I can see there to `app.disable`. There is a reference to the `view cache` Boolean which you set to false to disable caching. EJS uses this:

https://github.com/mde/ejs/blob/master/lib/ejs.js#L463

Caching is disabled by default for local development, and enabled by default in production.

There's also the local var `cache` which you can pass in your data object, and EJS respects this as well:

https://github.com/mde/ejs/blob/master/lib/ejs.js#L476

**Comment by theonlygusti** [comment]
@mde `app.set('view cache', false)` also doesn't work

**Comment by mde** [comment]
I don't know what's going on with your app, but I just installed and built an app with Express 4 (v4.16.4), and this works as expected.

Here's the server.js:

```javascript
const express = require('express');
const app = express();
const port = 3000;

app.set('views', './views');
app.set('view engine', 'ejs');
app.set('view cache', false);

app.get('/', (req, res) => {
  res.render('index', {message: 'Hello there, '});
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}!`);
});
```

And the index.ejs

```html
<% let suffix = 'asdf'; %>
<%=
message + suffix;
%>
```

I am running the app in production mode with `NODE_ENV=production node server.js`. I verified that caching was working as expected, then added `app.set('view cache', false);` and verified that caching stopped working. Every time I changed `suffix`, the rendered message is changing.

Again, I'm not sure what's happening with your code, but it does not appear to be an EJS or Express problem. If you can reduce this down to a minimal test, I'm happy to try to help.
