### ISSUE TITLE
Cannot build version 2.6.1 with Jake on Linux - .bin/eslint not found

### ISSUE THREAD

**Issue by boompig** [mde/ejs#418]
Hi, I am new to this project so excuse my ignorance.

I am trying to build the minified file from source.

I am currently looking at version 2.6.1 (that tag in github), and `jake build`. I am seeing this error:

```
/bin/sh: 1: ./node_modules/.bin/eslint: not found
jake aborted.
Error: Command failed: ./node_modules/.bin/eslint "**/*.js" Jakefile
    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
(See full trace by running task with --trace)
```

Is this error expected?

**Comment by RyanZim** [comment]
Did you run `npm install` in the project directory?

**Comment by mde** [comment]
Def. requires Jake as a dev dep.
