### ISSUE TITLE
Smaller client functions

### ISSUE THREAD

**Issue by zensh** [mde/ejs#42]
I intend to precompile some simple templates to a javascript source file for browser.(https://github.com/teambition/gulp-ejs-template)

I test file `./test/fixtures/messed.ejs`:

`<ul><%users.forEach(function(user){%><li><%=user.name%></li><%})%></ul>`

use `{client:true, compileDebug:false}`, get a result, it is too fat. Any chance I pull request to improve it (remove `include`, move `escape` and `rethrow` out of function)?

```js
function template(locals, escape, include, rethrow) {
  escape = escape || function(markup) {
    // Handle stupid JS `undefined` and `null`
    // Yes, we want double-equal here to catch both
    // jshint eqnull: true
    if (markup == null) {
      return '';
    }
    return String(markup)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/'/g, '&#39;')
      .replace(/"/g, '&quot;');
  };
  rethrow = rethrow || function rethrow(err, str, filename, lineno) {
    var lines = str.split('\n'),
      start = Math.max(lineno - 3, 0),
      end = Math.min(lines.length, lineno + 3);

    // Error context
    var context = lines.slice(start, end).map(function(line, i) {
      var curr = i + start + 1;
      return (curr == lineno ? ' >> ' : '    ') + curr + '| ' + line;
    }).join('\n');

    // Alter exception message
    err.path = filename;
    err.message = (filename || 'ejs') + ':' + lineno + '\n' + context + '\n\n' + err.message;

    throw err;
  };
  var __output = "";
  with(locals || {}) {;
    __output += "<ul>";;
    users.forEach(function(user) {;
      __output += "<li>";;
      __output += escape(user.name);
      __output += "</li>";;
    });
    __output += "</ul>";
  };
  return __output.trim();
}
```

**Comment by TimothyGu** [comment]
First, note that the default `include` function is not included in the client function as you can't include a file in te browser.

Second, the main reason why we bundled the two functions is so that the client functions are standalone, without the need to depend on any other scripts.

What we can fix right now is not to bundle `rethrow` in scripts with `compileDebug == false`.

**Comment by TimothyGu** [comment]
> What we can fix right now is not to bundle `rethrow` in scripts with `compileDebug == false`.

Fixed in b51c680.

**Comment by mde** [comment]
Excellent.

**Comment by TimothyGu** [comment]
Now it looks like this (prettified)

```js
function anonymous(locals, filters, escape, rethrow) {
  escape = escape || function(html) {
    return String(html)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/'/g, '&#39;')
      .replace(/"/g, '&quot;');
  };
  var buf = [];
  with(locals || {}) {
    (function() {
      buf.push('<ul>');
      1;
      users.forEach(function(user) {;
        buf.push('<li>', escape((1, user.name)), '</li>');
        1;
      });
      buf.push('</ul>');
    })();
  }
  return buf.join('');
}
```

**Comment by TimothyGu** [comment]
The way jade does it is *requiring* the user to load a jade "runtime" file with necessary functions like `escape()`. I guess we could add an option for that.

**Comment by zensh** [comment]
standalone client functions is unnecessary. I would like to pecompile all client ejs templates into `templates.js`. `templates.js` return a object with all template function.

**Comment by TimothyGu** [comment]
@zensh I get what you mean. However, there are two issues I see here:

1. Not bundling the functions would break backwards compatibility.
2. Having to load an extra runtime file is, for a lack of a better word, a pain in the ass, especially in our case where we only need one or two functions.

**Comment by zensh** [comment]
I have implemented  https://github.com/teambition/gulp-ejs-template , precompile ejs templates to a js file, then run in browse, support `include`!

**Comment by TimothyGu** [comment]
To be honest, the output script on teambition/gulp-ejs-template does not look *any* smaller than vanilla output from EJS. And thus, closing this ticket.

**Comment by mde** [comment]
:+1:
