### ISSUE TITLE
how can i ignore html parse errors while working with ejs-lint. 

### ISSUE THREAD

**Issue by aadiwebdev** [mde/ejs#420]
I have written huge code integrating html and ejs and iam unable to sort out my errors.I hardly gone through installing ejs-lint for debugging errors but i am able to see parse error for html tags which i want in my project.Is there any way to ignore all html tags and get to know errors only regarding EJS syntax.I tried debugging but i only found html parse related errors which are not of my interest.I expect to get the webpage so that i dynamically change my content on my webpage as per the parameter passed at res.render('file.ejs',{obj:object});
    
    
    <body>
    
        <div class="main">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-img">
                        <img src="images/signup-img.jpg" alt="">
                    </div>
                    <div class="signup-form">
                        <form 
                        action="<%= user.type == 'faculty' ?/faculty-registration :user.type=='parent'?/parent-registration: user.type == 'student' ?/student-registration:/admin-registration%>"
                        method="POST" class="register-form" id="register-form">
                            <h2><%=user.type%> Registration Form</h2>
                            <div class="form-row">
                                <div class="form-group">
                                    <label for="name"><%=user.name %> :</label>
                                    <input type="text" name="name" id="name" required/>
                                </div>
                                
                                <div class="form-group">
                                    <label for=""><%=user.rollno%>:</label>
                                    <input type="text" name="rollno" id="rollno" required/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="<%=user.type=='parent'?user.role[0]:user.address[0]%>">Address :</label>
                                <input type="text" name="<%=user.type=='parent'?user.role[0]:user.address[0]%>" id="<%=user.type=='parent'?user.role[0]:user.address[0]%>" required/>
                            </div>
    
                            <div class="form-radio">
                                <label for="gender" class="radio-label">Gender :</label>
                                <div class="form-radio-item">
                                    <input type="radio" name="gender" id="male" checked>
                                    <label for="male"><%=user.gender[0]%></label>
                                    <span class="check"></span>
                                </div>
                                <div class="form-radio-item">
                                    <input type="radio" name="gender" id="female">
                                    <label for="female"><%=user.gender[1]%></label>
                                    <span class="check"></span>
                                </div>
                            </div>
    
                            <div class="form-row">
                                <div class="form-group">
                                    <label for="<%=user.branch.id%>"><%=user.branch.id%> :</label>
                                    <div class="form-select">
                                        <select name="<%=user.branch.id%>" id="<%=user.branch.id%>">
                                                <option value=""></option>
                                            <% for(const j=0 ; j < user.branch[0].length ;j++){%>
                                                <option value="<%=user.branch[0][j]%>"><%=user.branch[1][j]%></option>
                                            <%}%>
                                        </select>
                                        <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                                    </div>
                                </div>
                          
                            <div class="form-group">
                                    <label 
                                    for =
                                    "<%= (user.type=='student'||user.type=='parent')?user.year.id :user.designation.id%>">
                                    <%= (user.type==='student'|| user.type=='parent')?user.year.id :user.designation.id%> :</label>
                                    <div class="form-select">
                                        <select name="<%= (user.type=='student'||user.type=='parent')?user.year.id :user.designation.id
                                        %=user.year.id%>" id="<%= (user.type=='student'||user.type=='parent')?user.year.id :user.designation.id%>">
                                            <option value=""></option>
                                            <% for(const j=0 ; j < user.year[0].length ;j++){ %>
                                                <option value="<%= (user.type=='student'||user.type=='parent')?user.year[0][j] :user.designation[0][j]%>">
                                                    <%= (user.type=='student'||user.type=='parent')?user.year[0][j] :user.designation[1][j]%></option>
                                            <%}%>
                                        </select>
                                        <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                                    </div>
                                </div>
                            </div
    
                            <div class="form-group">
                                    <label 
                                    for ="
                                    <%= user.type == 'faculty' ? user.interests[0] :user.type=='parent'?user.sname: user.type == 'student' ?user.pname:user.test%>
                                    "><%= user.type == 'faculty' ? user.interests[1] :user.type=='parent'?user.sname: user.type == 'student' ?user.pname:user.test%>
                                    :</label>
                                    <input 
                                    type="test" 
                                    name="<%= user.type == 'faculty' ? user.interests[0] :user.type=='parent'?user.sname: user.type == 'student' ?user.pname:user.test%>"
                                     id="<%= user.type == 'faculty' ? user.interests[0] :user.type=='parent'?user.sname: user.type == 'student' ?user.pname:user.test%>">
                            </div>
    
    
                            <div class="form-group">
                                <label for="phone">user.phone :</label>
                                <input type="phone" name="phone" id="phone">
                            </div>
    
               <div class="form-group">
                                <label for="password">user.password :</label>
                                <input type="password" name="password" id="password">
                            </div>
    
        
                            <div class="form-group">
                                <label for="email">user.email :</label>
                                <input type="email" name="email" id="email" />
                            </div>
                            <div class="form-submit">
                                <input type="submit" value="Reset All" class="submit" name="reset" id="reset" />
                                <input type="submit" value="Submit Form" class="submit" name="submit" id="submit" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </body>
    </html>

**Comment by mde** [comment]
I can't necessarily debug your code for you, but I can offer some suggestions for how to proceed:

 - Use some partials, instead of having everything in one large file. That will help you break things down into smaller parts, so you can see what's going wrong where.
 - Don't do a lot of logic or computation in your template. EJS lets you do this, but it doesn't mean it's a good idea. Calculate all the values you want to use, *before* you render, and pass simpler values into the template. (All those ternaries and "or's" are pretty confusing.)

I am not super familiar with ejs-lint, and I'm not sure what you mean by HTML parse errors, but this is clearly not an issue with EJS itself, so unfortunately there's not a lot more I can do to help. I'm going to close this issue.
