### ISSUE TITLE
npm warn: request-promise@4.2.2 requires a peer of request@^2.34 but none is installed

### ISSUE THREAD

**Issue by airda2895** [mde/ejs#423]
Hi,

I have just installed EJS on my computer but after running npm install ejs I've got these messages:

![image](https://user-images.githubusercontent.com/45570407/52937829-74be0d00-3360-11e9-9436-6109aaf93926.png)

What should I do?

Thank you in advance

**Comment by mde** [comment]
EJS does not depend on request-promise. Possibly something else in your application does? (You can verify this by installing EJS in an empty directory.)
