### ISSUE TITLE
<%- and <%= ignore encodeURI

### ISSUE THREAD

**Issue by chernikovalexey** [mde/ejs#424]
I'm trying to print links which would contain unicode characters (such as German umlauts e.g.). For example, this link https://reji.me/en/conjugation/german/verbs-starting-with-ü

Where ü needs to be encodeURI'ed: https://reji.me/en/conjugation/german/verbs-starting-with-%C3%BC

Say, this letter is in variable `letter`, when I print if as follows:
<%- encodeURIComponent(letter) %> it doesn't print it like %C3%BC but as ü. So, there's basically no way to print an encoded string via ejs. The same with <%=.

**Comment by mde** [comment]
I cannot reproduce your problem in a Node REPL (v.10.13.0). Output is as follows:

```
$ node -v
v10.13.0
$ node
> let ejs = require('./lib/ejs');
undefined
> ejs.render('<%- encodeURIComponent(letter) %>', {letter: 'ü'});
'%C3%BC'
> ejs.render('<%= encodeURIComponent(letter) %>', {letter: 'ü'});
'%C3%BC'
```

Please let me know if I am missing something obvious. This does not appear to be a problem with EJS. Happy to re-open if you'll provide a minimum failing test.

**Comment by loic-10** [comment]
use encodeURIComponent(encodeURIComponent(letter))
