### ISSUE TITLE
conditions with DOM elements

### ISSUE THREAD

**Issue by KyleGas** [mde/ejs#425]
Hello!

I am trying to get info from a DOM element in order to make it a condition. 

I tried this here first, to be able to communicate with DOM elements in general, but it doesn't work, it tells me "document ist not defined". Is there a way to go about this?

`<p class="taskP" id="dayTaskText00">
          <%= tasks.length %> tasks
          <%= document.getElementById('soHeading').innerHTML = 'hello'%>
        </p>`

**Comment by RyanZim** [comment]
EJS is a preprocesser, it doesn't know anything about HTML, so you have no DOM.
