### ISSUE TITLE
How to compile and render files?

### ISSUE THREAD

**Issue by didaquis** [mde/ejs#429]
Hi. 
I'm trying to compile and render an EJS file on the browser (client side). I'm not understanding the documentation and need some clues.

This is my code:
```
// myScript.js
function renderTemplate(url, dataToSend) {
    let template = `<%- include('${url}', ${dataToSend}); %>`;
    let fn = ejs.compile(template, {client: true, async: false, filename: 'myTemplate'});

    return fn(null, null, function(path, d){
    });
}

let templatedCompiledWithData = renderTemplate('../templates/myTemplate.ejs', { data: 'some data' });
document.getElementById('target').innerHTML = templatedCompiledWithData;
```

**Comment by didaquis** [comment]
Suggestion: documentation could have more examples and suggest different approaches to use EJS

**Comment by mde** [comment]
I'm a bit confused by what you're trying to do, or what your expectations are for EJS. Browsers do not have access to files on the server (unless they're obtained through some mechanism like `fetch`), so you would need to send the template text to the browser somehow first before trying to render.

All EJS really does is take a template string and some variables, and render a string from them. The ability to read files off disk, and do `includes` are server-side only functions added for convenience.

**Comment by didaquis** [comment]
humm... I'm trying to update my old EJS dependency to the last release. But seems like my older EJS (0.8.x) works so different than newer versions. It seems like I'm going to have to do a much bigger refactor than I thought.  😓

Thanks for your help!
