### ISSUE TITLE
Multiple looping not working

### ISSUE THREAD

**Issue by iitsuraj** [mde/ejs#439]
ejs: 2.6.1,
    ejs-mate: 3.0.0,
    express: 4.16.4,

> dummy data for my logic

`doctors =[{
    "id": "1",
    "name": "suraj"
},{
    "id": "2",
    "name": "saini"
},{
    "id": "3",
    "name": "surajsaini"
},{
    "id": "4",
    "name": "banti"
},{
    "id": "5",
    "name": "bantisaini"
}]`
or 
`user = [{
    "id": "1",
    "name": "surajsaini"
},{
    "id": "2",
    "name": "rahul"
},{
    "id": "3",
    "name": "sachin"
}]`

> my logic => 

```
for(var i=0; i<doctors.length; i++){
    for(var z=0; z<user.length; z++){
        if(doctors[i].name===user[z].name){
            console.log(i);
            console.log(z);
           }
       }
    }
```

> in ejs=>

My router pass doctors array or bookmarks array.
```
<% for (var i=0; z<doctors.length; i++) {%>
<% for (var z=0; z<bookmarks.length; i++) {%>
    <% if(doctors[i]._id === bookmarks[z].doctor){%>
        <p>hi</p>
        <% } else {%>
                <p>hello</p>
        <%}%>
<%}%>
<%}%>
```
it throws an error _id not define. But when I access _id like this then it works fine
 ```
<% for (var i=0; z<doctors.length; i++) {%>
<%= doctors._id %>
<%}%>
```
In this case, my logic not works in ejs. Then please guide me to achieve my logic

**Comment by mde** [comment]
I'm a little confused. There seem to be multiple issues with your EJS code. It's different from your JS code.

 - Why are you trying to access `_id` property when you haven't defined that in any of the data objects? You only have `id` defined. Am I missing something here?
 - Why are you using a mixture of `i` and `z` for your array indices? You need to use one variable for the outer loop, and one for the inner loop, and not mix them together.
 - In your final block of code, you're accessing an `_id` property directly on the array, instead of an array item.

I'm pretty sure this isn't an issue with EJS. It's your code.

**Comment by iitsuraj** [comment]
for show my logic I used dummy data.

> my router send =>

```
doctors = [ { profile:
     { name: 'suraj saini',
       addresh: '',
       age: 1,
       gender: 'male'},
    activeToken: 'YRAk',
    active: false,
    _id: 5cfa880665e8455188b0f1b5,
    booking: [ [Object], [Object], [Object], [Object], [Object] ],
    email: 'email3@yopmail.com',
   bookmark: [] },  { profile:
     { name: 'banti saini',
       addresh: '',
       age: 1,
       gender: 'male'},
    activeToken: 'YRAk',
    active: false,
    _id: 5cfa880665e8455188b0f1c5,
    booking: [ [Object], [Object], [Object], [Object], [Object] ],
    email: 'email4@yopmail.com',
    bookmark: [] }, .....]
```
This bookmarks came from userModel(user Schema) my user Schma looks
```
user = {
profile: [object],
bookmark: [ [Object], [Object], [Object], [Object], [Object] ]
}
```
```
bookmarks = [{_id: 5cfbad9255384a3eac7176ff,
                       doctor: 5cfa880665e8455188b0f1b5,
                       date: 2019-06-08T12:44:02.893+00:00
}, {_id: 5cfbad9255384a3eacd176ff,
                       doctor: 5cfa8450665e8455188b0f1b5,
                       date: 2019-06-08T12:44:02.893+00:00
}]
```

**Comment by iitsuraj** [comment]
for show my logic I used dummy data.

> my router send =>

```
doctors = [ { profile:
     { name: 'suraj saini',
       addresh: '',
       age: 1,
       gender: 'male'},
    activeToken: 'YRAk',
    active: false,
    _id: 5cfa880665e8455188b0f1b5,
    booking: [ [Object], [Object], [Object], [Object], [Object] ],
    email: 'email3@yopmail.com',
   bookmark: [] },  { profile:
     { name: 'banti saini',
       addresh: '',
       age: 1,
       gender: 'male'},
    activeToken: 'YRAk',
    active: false,
    _id: 5cfa880665e8455188b0f1c5,
    booking: [ [Object], [Object], [Object], [Object], [Object] ],
    email: 'email4@yopmail.com',
    bookmark: [] }, .....]
```
This bookmarks came from userModel(user Schema) my user Schma looks
```
user = {
profile: [object],
bookmark: [ [Object], [Object], [Object], [Object], [Object] ]
}
```
```
bookmarks = [{_id: 5cfbad9255384a3eac7176ff,
                       doctor: 5cfa880665e8455188b0f1b5,
                       date: 2019-06-08T12:44:02.893+00:00
}, {_id: 5cfbad9255384a3eacd176ff,
                       doctor: 5cfa8450665e8455188b0f1b5,
                       date: 2019-06-08T12:44:02.893+00:00
}]
```

**Comment by mde** [comment]
Yes, my point is the looping logic in your code is incorrect. You are mixing `z` and `i` together:

```html
<% for (var i=0; z<doctors.length; i++) {%>
```

A minimal test verifies that multiple loops work fine in EJS:

```bash
$ node
> let ejs = require('./ejs');
undefined
> let arrA = [1, 2, 3, 4];
undefined
> let arrB = ['a', 'b', 'c', 'd'];
undefined
ejs.render('<% for (let i = 0; i < arrA.length; i++) { %><% for (let j = 0; j < arrB.length; j++) { %><%= arrA[i] + arrB[j] + ","; %><% } %><% } %>', {arrA, arrB});
'1a,1b,1c,1d,2a,2b,2c,2d,3a,3b,3c,3d,4a,4b,4c,4d,'
```

The problem is somewhere in your code.

**Comment by iitsuraj** [comment]
Thanks for your time!
My code worked fine there was a typo mistake.

**Comment by iitsuraj** [comment]
`var doctors =[
{
_id:5cfc124635af1754707d19c7,
name: suraj
},{
_id:5cfc124635af1752567d19c7,
name: banti
},{
_id:5cfc124635hgf754707d19c7,
name: saini
},
{
_id:5cfc12ytr5af1754707d19c7,
name: surajsaini
},
{
_id:5cfc12ytr5af1754o9rn19c7,
name: bantisaini
},
{
_id:5cfc12ytr5a0214o9rn19c7,
name: sainibanti
}
]`
`var bookmark =[
{
_id:5cfc1uiotr5a0214o9rn19c7,
doctor:5cfc12ytr5a0214o9rn19c7,
name: rahul
}
]`

> my ejs =>

```
<% for(var i=0; i<doctors.length; i++) {%>
		<% if(bookmark.length>0){%>
			<% for(var z=0; z<bookmark.length; z++){%>
				<% if(doctors[i]._id = bookmark[z].doctor){%>
					<%= bookmark[z].doctor%>
				<%} else{%>
					bookmark
				<%}%>
			<%}%>
		<%} else {%>
			bookmark
		<%}%>	
	<%}%>
```

> result
`5cfc12ytr5a0214o9rn19c7 5cfc12ytr5a0214o9rn19c7 5cfc12ytr5a0214o9rn19c7 5cfc12ytr5a0214o9rn19c7 5cfc12ytr5a0214o9rn19c7 5cfc12ytr5a0214o9rn19c7`

> expected result 
`bookmark bookmark bookmark bookmark bookmark 5cfc12ytr5a0214o9rn19c7`

where am I doing mistake

**Comment by iitsuraj** [comment]
`var doctors =[ { "_id":"5cfc124635af1754707d19c7", "name": "suraj" },{ "_id":"5cfc124635af1752567d19c7", "name": "banti" },{ "_id":"5cfc124635hgf754707d19c7", "name":" saini" }, { "_id":"5cfc12ytr5af1754707d19c7", "name": "surajsaini" }, { "_id":"5cfc12ytr5af1754o9rn19c7", "name": "bantisaini" }, { "_id":"5cfc12ytr5a0214o9rn19c7", "name": "sainibanti" } ];`
`var bookmark =[ { "_id":"5cfc1uiotr5a0214o9rn19c7", "doctor":"5cfc12ytr5a0214o9rn19c7", "name": "rahul" },{ "_id":"5cfc1uiotr5a0214025rn19c7", "doctor":"5cfc124635hgf754707d19c7", "name": "sachine" } ];`

```
for(var i=0; i<doctors.length; i++) {
		if(bookmark.length>0){
			for(var z=0; z<bookmark.length; z++){
            	if(doctors[i]._id === bookmark[z].doctor){
                   console.log('cong!')
                   } else {
                               console.log('bookmark')
                               }
            }
		} else {
			console.log("bookmark")
		}
	}
```
> result
```
> "bookmark"
> "bookmark"
> "bookmark"
> "bookmark"
> "bookmark"
> "cong!"
> "bookmark"
> "bookmark"
> "bookmark"
> "bookmark"
> "cong!"
> "bookmark" 
```
