### ISSUE TITLE
Make `resolveInclude()` overridable

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#44]
Migrated from tj/ejs#170, opened by @dresende.

> If this function could be exported (to be replaced), I (and others) could overwrite it to be able to dynamically accept other include paths and possibly other crazy stuff. I had to do this and to achieve it I had to replace exports.parse (without changing it) to then be able to create my own `resolveInclude`.
>
> This is just a tiny cool feature, not that I can't live without it..

**Comment by olivierkaisin** [comment]
:+1:

**Comment by olivierkaisin** [comment]
It's done https://github.com/mde/ejs/pull/54
