### ISSUE TITLE
Unable to display an array from mongoDB in ejs

### ISSUE THREAD

**Issue by Mallik813** [mde/ejs#440]
I am trying to display an array(sub Document) from mongoDB database in ejs.

I could insert the data from a form to mongoDB.

**this is what I did to add into the database from my users.js**
```

router.post('/task', (req, res)=>{
        const {_id, task}  = req.body;
        let errors = [];
        if (!task) 
        errors.push({ msg: ' Please enter a task ' });  
       User.updateOne({ _id:_id }, {$push:{tasks:{task}}}, { new: true }, (err, doc) => {
       if (!err) { res.redirect('../dashboard?Successfully+Updated',{tasks:[{task}]}); }
       else
           console.log('Error during record update : ' + err);    
      });
});

```
**and this is how I'm trying to display data in ejs**

```
<ul>
    <% for(var i=0; i<tasks.length;i++){%>
        <li><%= tasks[i].task %></li>
    <%}%>
</ul>
```

A screeshot of the database collection is also attached.
![Mongo](https://user-images.githubusercontent.com/43982083/59154394-2196d400-8a8f-11e9-943e-d13e660a96be.jpeg)

Please help me find my mistake and solve it.

Thankyou

**Comment by mde** [comment]
This is almost certainly not a problem in EJS. EJS is a well-tested library that does nothing but evaluate JavaScript and return a string. If you suspect a real problem in the library, please provide a minimal test that demonstrates the problem. I'm very sorry, but I can't help you debug your application code. Please feel free to reopen if you can identify a real problem in the EJS library.
