### ISSUE TITLE
npm package out of date

### ISSUE THREAD

**Issue by aroytman** [mde/ejs#441]
I see that the npm package is out of date: https://www.npmjs.com/package/ejs

The latest code on GitHub has ejs.Template exposed, but the npm package does not have this yet. We're using ejs.Template in our project.

Can we get the npm package updated with this change?

Thanks!

**Comment by mde** [comment]
Just published v2.6.2 to NPM. Thanks!

**Comment by aroytman** [comment]
Thank you!
