### ISSUE TITLE
 SyntaxError: Unexpected token ) while compiling ejs

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [mde/ejs#442]
I have implemented translation using i18next and am trying to use map function , getting the following error ` SyntaxError: Unexpected token ) while compiling ejs`
Please help

```
en.json
{
  "title": "List of Countries",
  "list":[{
     "name": "Singapore",
     "code": "SG"
  },{
    "name": "Thailand",
    "code": "TH"
 }]
}

<h1><%=(i18next.t("title")%></h1> //works  outputs "List of Countries"
<h2><%=(i18next.t("list",{returnObjects: true})).map(e=>{%>
<%=e.name%> //want to display name only (not working)
<%})%></h2>

```

**Comment by GProSoftware828** [comment]
this seems obvious, but you can always reformat if you're desperate and use: innerHTML.output += `${list.name}` in a get request rather than ejs... if it's a language library bug with ejs.

**Comment by mde** [comment]
This is not a library bug. This works as expected in EJS:

```bash
$ node
> let ejs = require('./ejs');
undefined
> ejs.render('<% arr.forEach(item => { %><%= item + "... "; %><% }); %>', {arr: ['A', 'B', 'C']});
'A... B... C... '
```
(Also not sure why you'd use `map` here — it returns a new array with altered values. `forEach` is for simple iteration.)

Very sorry, but I'm going to close this, as it's clearly not an issue with EJS. Please feel free to reopen if you can provide a minimal broken example.

**Comment by abuziyaadawajeeh** [comment]
hey guys, I am getting the same error. Can you please help what is wrong with the code`   <ul class="mytodos">
      <% data.arr.forEach(function(item) { %>
      <li><%= item =%></li>
      <% }); %>
    </ul>`

**Comment by swap2001** [comment]
Instead of using <%=  in second line in your code, try to use following in second line:
<li> <%- item %></li>

**Comment by asifDurran** [comment]
<% data['arr'].forEach(function(item) { %>

  <li><%= item =%></li>

  <% }); %>

try this code it might help you ...

**Comment by Imprasna** [comment]
Unexpected identifier in while compiling ejs If the above error is not helpful, you may want to try EJS-Lint: https://github.com/RyanZim/EJS-Lint Or, if you meant to create an async function, pass async: true as an option.


I'm getting this error . Please help me solve this error.
