### ISSUE TITLE
I cannot just use EJS.

### ISSUE THREAD

**Issue by dragonmenorka** [mde/ejs#445]
just shows the code. Here's mi file name:
index.ejs
and heres the code:
```js
<%- include head.ejs -%>
<%- include header.ejs -%>
    <p style="display:none;color:black;background:orange;" id="aviso"></p>
    <div class="padding">

    </div>
    <script src="../public/js/ejs.min.js">
</body>
</html>
```

**Comment by mde** [comment]
You cannot load the EJS library inside a template you are trying to render. If you are using EJS client-side, you have to (1) load the EJS library, (2) grab some template text (you have have saved it inside of a hidden text area, or loaded it via XHR), (3) render your template with some data, and (4) insert that rendered HTML into the DOM using `innerHTML` or similar.
