### ISSUE TITLE
Render variable with space in it

### ISSUE THREAD

**Issue by fabianTMC** [mde/ejs#449]
Hi all,

I have a user defined object that looks like this 

```json
const values = {
    "entity name": "Some name",
};
```

and a system generated template that is:
```javascript
const t = "<%= entity name %>";
```

It is getting passed to the render function like so:
```javascript
render(t, values);
```

Because of the space in the variable name, I am getting the following error:
```javascript
missing ) after argument list while compiling ejs
```

Is there any way I can have ejs render this variable name which has spaces in it? I am unable to update the name of the property in question as that will lead to a very painful system audit for me.

**Comment by mde** [comment]
Unfortunately this scenario doesn't work in ordinary JavaScript either. The conversion from object property names to local variables is accomplished using `with`. EJS is just JavaScript, and suffers from the same limitations.

A better bet might be to pass in the values with the problematic key names in a single object — or even use an explicit `locals` object, possibly with the `_with` option set to false to make sure you never rely on this feature.

**Comment by fabianTMC** [comment]
That solved the issue for me, thanks!
