### ISSUE TITLE
renderFile path issue

### ISSUE THREAD

**Issue by darrencarlin** [mde/ejs#453]
I am hoping someone can help me fix this very simple issue. 

I keep getting an ENOENT error for the path name for my template file. I have tried a bunch of different variants but still get the same error. 

Here is my folder structure.. creditEmail.js in the functions folder is compiled to lambda folder and thats where its run from netlify.

My .ejs template file is in the templates folder. 

![Screenshot 2019-08-28 at 13 46 03](https://user-images.githubusercontent.com/30006190/63880626-0f487a00-c99c-11e9-832a-1536aae4c22a.png)

The code i'm using with renderFile is as follows:

```
 ejs.renderFile(
      __dirname + "src/templates/credit.ejs",
      { name: "Darren", subject: "Test", message: "Test" },
      (err, data) => {
        if (err) {
          console.log(err)
        } else {
          const mainOptions = {
            from: `${name} <${CREDIT_EMAIL}>`,
            to: CREDIT_EMAIL,
            subject: subject,
            html: data,
          }
          console.log("html data ======================>", mainOptions.html)
          transporter.sendMail(mainOptions, (err, info) => {
            if (err) {
              console.log(err)
            } else {
              console.log("Message sent: " + info.response)
            }
          })
        }
      }
    )
```

Here is the error: 

```
{ Error: ENOENT: no such file or directory, open '/src/templates/credit.ejs'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync [as fileLoader] (fs.js:551:33)
    at v (/var/task/creditEmail.js:8:1260)
    at g (/var/task/creditEmail.js:8:916)
    at f (/var/task/creditEmail.js:8:1198)
    at Object.t.renderFile (/var/task/creditEmail.js:8:3298)
    at /var/task/creditEmail.js:1:198604
    at t.handler (/var/task/creditEmail.js:1:198927)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/src/templates/credit.ejs' }
```

**Comment by mde** [comment]
Looks like you're passing it an absolute path that does not exist. I have no idea why `__dirname` is not giving you something accurate.

**Comment by darrencarlin** [comment]
Yeah, I tried again today to figure it out, still no luck so I just used ejs.render() and passed the string along in the nodemailer html. Works fine. 

Weird.
