### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by ExE-Boss** [mde/ejs#461]
For **EJS v3**, I’d like to migrate the codebase to use **TypeScript.**

The main advantage will be the ability to have type checking.

It will also ensure that `@types/ejs` will no longer be necessary.

**Comment by mde** [comment]
"Have type checking" all by itself is not particularly compelling to me. What *specific* benefits does that bring us?

**Comment by ExE-Boss** [comment]
It also allows us to write **ESNext** code, which will be transpiled to **ES5** by the **TypeScript** compiler.

**Comment by acklenx** [comment]
One of the things I like about JavaScript is that it's JavaScript.

**Comment by RyanZim** [comment]
I'm not real active here, so no need for me to block it, but I'm not a fan of TS.

**Comment by mde** [comment]
We can drop support for lots of the older Nodes, which will let us write pretty up-to-date JavaScript. The client-side version has to go through a build step anyhow, and we could build with a target of much older runtimes for that if we wanted to.

TypeScript is not necessary for doing that.

Also, it's worth reading up on how provable the benefits of static typing are, or are not: https://danluu.com/empirical-pl/

**Comment by mde** [comment]
I've thought a lot about this, and I am not sold enough on the benefits to want to add the complexity. I'm going to close this issue.
