### ISSUE TITLE
Drop support for old Node versions

### ISSUE THREAD

**Issue by ExE-Boss** [mde/ejs#462]
**EJS v2** has declared support for **Node 0.10** and newer.

I’d like to drop support for **Node < 8**, since those versions are no longer supported, and **Node 8** will become unsupported at the end of the year.

**Comment by mde** [comment]
This seems sensible, although people do run older versions of Node in production for longer than people might imagine.

**Comment by CaseyPeters** [comment]
Hey @mde I'm the older version of node in production dev. We are using Node v4.2.2 (i know... i know... but it is what it is) and this change that dropped support for Node 4 just broke our docker builds. Is it possible for me to request that a major version bump be done and Node 4 gets added back for version 2.7.4?

**Comment by mde** [comment]
It was trivial to do, so I just got it working again on v4. Dropping support for ancient Node versions doesn't really qualify as a major semver upgrade. There are no API changes or incompatibilities. Node v4 was EOL'd well over a year and a half ago, after extended maintenance LTS.

I'll try to keep support for v4 working for a reasonable amount of time, but you can't count on a semver major version bump for something like that. If you really can't upgrade, you should just install a specific known-good version. That's the whole point of hermetic builds.

**Comment by CaseyPeters** [comment]
@mde I appreciate the quick fix ❤️ We are just in a bit of a rough spot we've been working hard to replace our node code completely and have not been making any effort to upgrade it. Unfortunately, without the ability to shrinkwrap our devDependencies which didn't get released until npm v3.10.8 this will continue to happen for us.

I wish we could just hard code the version, but we have no control over a dependency which points to `ejs`

Thanks again!

**Comment by mde** [comment]
You can upgrade NPM separately from Node. That might be an option for you.

**Comment by mde** [comment]
Dropped 4 and 6, with a major bump to v3. Apologies if this breaks things, but semver is your friend here.
