### ISSUE TITLE
Infinity is transformed to null

### ISSUE THREAD

**Issue by RomainJamet** [mde/ejs#467]
I'm using ejs as incorporated in the framework SailsJS, so I cannot confirm this is actually a problem with ejs, but I'm trying to pass an object from my controller to the front, and it has numerical fields in it. Since JS supports an "Infinity" value, I use it, but once on the .ejs file, the Infinity values become null. 

Now I can just tell my front-end functions to replace null with Infinity before comparing, but I think it might be worth testing.

**Comment by RyanZim** [comment]
This is not an issue with EJS itself: https://runkit.com/embed/44avsl2zcr2i
