### ISSUE TITLE
Infinite scrolling?

### ISSUE THREAD

**Issue by BrianAKass** [mde/ejs#473]
Is there a way to do this? Currently All i can think of is sending a get request for loading more DB items and somehow pushing into my rendered foreach loop. the only other thing i can think of is utilizing pagination logic and somehow tacking it on the render, but im not seeing the solution. Any help would be greatly appreciated on this. https://stackoverflow.com/questions/58828185/infinite-scrolling-in-ejs

**Comment by mde** [comment]
The commenter on your post is correct. Just fetch another page of data, then use EJS to render another chunk of the table. (Likely doing a `forEach` over a list of rows of data, and rendering each into a `tr` element in your table, or into `div` tags. This is not anything specific to EJS, so I'm going to close this issue.
