### ISSUE TITLE
Console spam in 2.7.2

### ISSUE THREAD

**Issue by ryangrahamnc** [mde/ejs#475]
Installing the newest version adds spam to the console logs:
```
> node -e "console.log('Thank you for installing \u001b[35mEJS\u001b[0m: built with the \u001b[32mJake\u001b[0m JavaScript build tool (\u001b[32mhttps://jakejs.com/\u001b[0m)\n');"

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
```

**Comment by ExE-Boss** [comment]
@mde

Why&nbsp;did you&nbsp;decide to&nbsp;add&nbsp;this in&nbsp;https://github.com/mde/ejs/commit/b9b6ddde9b832ceb70ca2ef03c344e05fe5b1985?

**Comment by mde** [comment]
I built Jake circa Node version 0.2, but never bothered to promote it, an eventually ended up being forced to use other JavaScript build tools which are frankly poorly conceived or implemented. I'm thrilled to be in a position to use Jake again, and realized that it could use some visibility for a change. EJS has a very large distribution, and can provide some of that visibility.

I certainly understand how some folks might perceive that as spammy, but I have also seen people use that post-install message to advertise their Patreon account, ask for donations, etc. This is simply making people aware of the existence of an open-source tool that could potentially be very useful to them, and allow them to use JS for something many people are stuck doing in Ruby, Python, or other languages. The message is friendly, unintrusive, and doesn't hurt anyone.

**Comment by vdh** [comment]
@mde Advertisements via post-install are banned, actually: https://www.zdnet.com/article/npm-bans-terminal-ads/

**Comment by mde** [comment]
I appreciate the concern, but I would also like to be 100% clear on the fact that this is not an advertisement. It does not ask for donations, or solicit the use of any sort of commercial service. However, having said that, I can understand how it might annoy people. It has served its purpose, and I'll happily remove it.
