### ISSUE TITLE
Remove old `include` preprocessor directive

### ISSUE THREAD

**Issue by mde** [mde/ejs#476]
This was a feature left over from the previous version, left for backward compat. It's time to remove it.

**Comment by mde** [comment]
Done with major version bump to v3.

**Comment by moeiscool** [comment]
the `<%- include() %>` method doesn't work the same way, is there an equivalent to this way to include? i declare variables in other blocks but with the new way i have to keep passing the variables :/

**Comment by mde** [comment]
It's just JavaScript. You can always execute a block of JS that creates global variables if you want them.
