### ISSUE TITLE
throws error "require is not defined" if run with "node (script).js"

### ISSUE THREAD

**Issue by uAliFurkanY** [mde/ejs#479]
To test:
```
const ejs = require("ejs");
console.log(ejs.render("<%= require %>"));
```
save this in a file and run "node (filename)", it will throw an error.

now run node, type ".load (filename)" and it works.

Node 12

**Comment by mde** [comment]
This is a result of how Node loads and run modules, and the scope that an EJS template runs in.

EJS templates are created using the `Function` constructor, and these functions execute in the global scope. Node loads and runs modules (including the main script run with `node`) in a module scope. `require` is a module-scoped variable.

Consider the following JS file:

```javascript
console.log(global === this);
console.log(typeof global.require);
console.log(typeof require);
let f = new Function('return global === this;');
console.log(f());
```
This gives you the following output:

```bash
dargo:test mde$ node req.js
false
undefined
function
true
```

This tells you the following:

 - `this` is not the global object in a normally run Node script (it's a module scope)
 - `require` is not a global variable; it's a module-scoped variable
 - Functions created with the `Function` constructor run in the global scope (not in the Node-created module scope that has the added `require`)

I'm not sure what Node is doing differently in the REPL with `load`, but the bottom line here is that this is not a bug in EJS.

**Comment by uAliFurkanY** [comment]
thanks for the response. do I need to manually add anything other than require?

**Comment by mde** [comment]
I guess that depends on what you're trying to do. You probably shouldn't be accessing system-level objects like `require` from inside your template anyhow. You should be passing it data, and rendering some kind of content, like JSON or HTML.
