### ISSUE TITLE
Render both .html and .ejs by default

### ISSUE THREAD

**Issue by Nsikak1** [mde/ejs#480]
It would be a nice feature if ejs could render both by default, like the way blade (php) renders .blade.php and .php
 I can make it render .html file with:

```
app.engine('html', require('ejs').renderFile)
app.set('view engine', 'html');
```

Reason: most editor don't style .ejs files and there are some html features the editor may have that requires a .html file
Thanks.

**Comment by RyanZim** [comment]
I believe this is an issue with express, not EJS itself

**Comment by Nsikak1** [comment]
Ok Closing the issue then
