### ISSUE TITLE
Update NPMJS package Includes section to read the same as the Wiki.

### ISSUE THREAD

**Issue by opiyonico** [mde/ejs#483]
The include section on the [Wiki](https://github.com/mde/ejs) reads:

> NOTE: Include preprocessor directives (<% include user/show %>) are not supported in v3.0+.

In NPM JS Usage section for [NPMJS EJS](https://www.npmjs.com/package/ejs) the include section reads:

> NOTE: Include preprocessor directives (<% include user/show %>) are still supported.

Please update this to read the same as the Wiki.

**Comment by ExE-Boss** [comment]
This is because the latest readme hasn't yet been published to npm.

**Comment by mde** [comment]
Yes, we made the doc changes after the face. These README changes will be propagated to the NPM package in the next release.

**Comment by opiyonico** [comment]
Thanks for the update.
