### ISSUE TITLE
Documentation : "client-side support" section unclear

### ISSUE THREAD

**Issue by n49o7** [mde/ejs#485]
The given code excerpt gives the error :
`"ReferenceError: require is not defined ejs.js:47:10"`

Are additional steps necessary ?

**Comment by RyanZim** [comment]
You're apparently using the code from the git repo; you need to download the browser version from the releases page. However, I just noticed that browser versions haven't been uploaded for any release since https://github.com/mde/ejs/releases/tag/v2.6.2 Attn @ExE-Boss @mde

**Comment by n49o7** [comment]
Thanks! Closing since I can confirm that the example works fine, at least with 2.6.2.

**Comment by mde** [comment]
@RyanZim Thank you, sir. It's easy to forget since it's a manual step. I need to automate that using GH's release API.
