### ISSUE TITLE
Includes and renderFile

### ISSUE THREAD

**Issue by hacdias** [mde/ejs#486]
Hey!

I'm trying to find a way to correctly use EJS without Express.js. I'm trying to use `renderFile` but I'm failing to find the includes!

```javascript
const ejs = require('ejs')

ejs.fileLoader = (layout) => {
  console.log(layout)
  return fs.readFileSync(join(config.viewsDir, `${layout}.ejs`))
}

console.log(await ejs.renderFile(layout, data, {
  filename: layout,
  async: true
}))
```

I've tried changing `filename` to `join(config.viewsDir, `${layout}.ejs`)` but it didn't work. Also, the file loader only seems to be called for the layout I explicitly call. The include can't be found anyway...

I tried to search through the issues but I couldn't find anything

**Comment by RyanZim** [comment]
You shouldn't need to define `fileLoader`; that's only needed if you're doing weird stuff. Also, no need to pass the `filename` option directly if you're using `renderFile`.

**Comment by hacdias** [comment]
Thank you @RyanZim. It works. Also, looking at the [docs], it seems that the signature of `renderFile` should be:

`renderFile (file, data, options, callback)`

However, without using a callback it seems to return the HTML. Is that correct?

**Comment by RyanZim** [comment]
If you don't pass a callback, it will return a promise that resolves to the HTML.

**Comment by hacdias** [comment]
Thanks! Closing this now.
