### ISSUE TITLE
3.0.1 : Cannot find module '/opt/application/node_modules/ejs/postinstall.js'

### ISSUE THREAD

**Issue by gastg77** [mde/ejs#487]
Hello there !

I'm trying to install ejs@3.0.1 but I can't because of this error :
```
npm install --save ejs

> ejs@3.0.1 postinstall /opt/application/node_modules/ejs
> node ./postinstall.js

internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module '/opt/application/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@3.0.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@3.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-12T17_08_35_562Z-debug.log
```

Version of node : 
```
node --version
v13.6.0
```

Regarding the number of "Weekly Downloads" on the NPM interface, I am sure it is not a dedicated issue. But I'm trying to understand what can be wrong. I checked on the tag, I saw the file. But after that, I have limited knowledge on how npm deployed node modules.

Thanks,

Seb

**Comment by mde** [comment]
You're correct — this is not a general issue. I can't reproduce your problem either:

```bash
dargo:test mde$ npm install ejs

> ejs@3.0.1 postinstall /Users/mde/Documents/test/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm WARN test No description
npm WARN test No repository field.
npm WARN test No license field.

+ ejs@3.0.1
added 1 package from 1 contributor, updated 1 package and audited 2 packages in 1.712s
found 0 vulnerabilities
```
I would start by checking to see if the postinstall script has actually been downloaded in node_modules/ejs.

**Comment by ExE-Boss** [comment]
@gastg77 What&nbsp;you can&nbsp;try to&nbsp;do, is&nbsp;run:
```
npm install ejs --ignore-scripts
```

This&nbsp;will cause&nbsp;**npm** to&nbsp;not&nbsp;attempt to&nbsp;run the&nbsp;`postinstall`&nbsp;script, which&nbsp;only&nbsp;logs the&nbsp;above&nbsp;message.

**Comment by gastg77** [comment]
> 
> 
> You're correct — this is not a general issue. I can't reproduce your problem either:
> 
> ```shell
> dargo:test mde$ npm install ejs
> 
> > ejs@3.0.1 postinstall /Users/mde/Documents/test/node_modules/ejs
> > node ./postinstall.js
> 
> Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
> 
> npm WARN test No description
> npm WARN test No repository field.
> npm WARN test No license field.
> 
> + ejs@3.0.1
> added 1 package from 1 contributor, updated 1 package and audited 2 packages in 1.712s
> found 0 vulnerabilities
> ```
> 

I tried yesterday on another computer with the last version of node JS and it worked. Something is definitely wrong on my Debian container. Let's see when I will work on the CI/CD on my project.

> I would start by checking to see if the postinstall script has actually been downloaded in node_modules/ejs.

The thing is, I can't. Because when npm exited, I don't have access to the file. It is like either npm did not downloaded the module or deleted all the file. The "ejs" directory in "node_modules" does not exist. Kind of hard to debug what is going on.

Anyway, I installed the module with yarn and It worked.


> This will cause **npm** to not attempt to run the `postinstall` script, which only logs the above message.

Thanks for the tip. I didn't know this argument.

Considering the dedicated issue, I think it's better to close the issue.

Thank you for the reply :+1:
