### ISSUE TITLE
Vote: VSCode Color Styling

### ISSUE THREAD

**Issue by Betanu701** [mde/ejs#488]
First this is not an issue. I will close this after about a week if it does not get closed before that.

Second, I want a vote to see what others prefer. In VSCode, my extension currently colors the ejs tags the same as other html tags. I honestly think it makes the code more readable using the "muted" way. 

Would people rather it stay the way it is or have the tags "muted"

Current way
![image](https://user-images.githubusercontent.com/5798012/72648085-1a4e7780-3948-11ea-95af-6a70fe05c32d.png)

Proposed way:
![image](https://user-images.githubusercontent.com/5798012/72648029-f68b3180-3947-11ea-9812-f4dc7e38f465.png)

**Comment by ExE-Boss** [comment]
Well, I&nbsp;use a&nbsp;colour scheme&nbsp;that&nbsp;makes the&nbsp;tags more&nbsp;muted.

**Comment by Betanu701** [comment]
@ExE-Boss Wouldn't all the tags be muted though in your color scheme? My proposal makes the tags stand out from the other html tags. In this case ejs muted and html vibrant/normal. 

I am not sure how useful it would be to others having the ejs tags look significantly different when scanning a document.

**Comment by mde** [comment]
I use Vim, so I don't have a strong opinion here. But it always kind of annoys me that most color highlighting just treats it as HTML.

**Comment by Betanu701** [comment]
I think I will change it to have the ejs tags slightly different. I will go ahead and close this. 

Thanks for the feedback!
