### ISSUE TITLE
Optional chaining doesn't seem to be supported currently

### ISSUE THREAD

**Issue by rosenfeld** [mde/ejs#490]
npm install -g ejs
    node

<pre>
> ejs = require('ejs');
> ejs.compile('<% const a = window?.document; %>');
SyntaxError: Unexpected token . while compiling ejs
</pre>

**Comment by RyanZim** [comment]
This is not yet supported by Node itself. It is available behind a flag in v13.4.0+ https://node.green/#ES2020-features-optional-chaining-operator-----
