### ISSUE TITLE
EJS variable inside script tag

### ISSUE THREAD

**Issue by idiglove** [mde/ejs#491]
![image](https://user-images.githubusercontent.com/29911508/72858515-ae776080-3cf3-11ea-8f82-84f054078dc9.png)

I need an ejs variable inside a script tag which is inside an ejs file. How do I do this? Thanks

**Comment by TyrionGraphiste** [comment]
Hi, one way is to write the id inside a [data attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) and then, get the value inside your script.

**Comment by mde** [comment]
If that script tag is part of a larger EJS file, then what you have there ought to work. You just have to make sure whatever is rendering that string of EJS from the file passes in the value of `lms_id`.

**Comment by mde** [comment]
Please let us know if this gets you unstuck or not, so we can close this issue.

**Comment by Betanu701** [comment]
I can confirm this is an issue at least in VSCode. I have not been able to identify the culprit. My guess is the linter but I am not able to confirm that. 

The ejs does work properly, but vscode is throwing an error being an "expression expected"

![image](https://user-images.githubusercontent.com/5798012/73206358-c34b5e00-4110-11ea-88d6-bee69071f880.png)

**Comment by mde** [comment]
This is clearly a problem with VSCode not understanding EJS tags vs. script tags. It is not a problem with EJS, so there's really nothing for us to do here. I'm going to close this issue.

**Comment by Ashi-s** [comment]
@idiglove You are just missing the quotes(").
I know I'm a bit late.

Try this.
`var lms_id = "<%= lms_id %>"`

**Comment by fireMan-34** [comment]
Hello, I am find the way how to solve it on Stackflow. 
[this is problem and answer ](url)
