### ISSUE TITLE
EJS with optional chaining

### ISSUE THREAD

**Issue by Tim-arts** [mde/ejs#492]
Hello, I would like to know if it would be possible to use EJS with the optional chaining option (described [here](https://github.com/tc39/proposal-optional-chaining)).
I'm currently using Babelify (Browserify transform for Babel) and it's possible to use the option by using an [NPM](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining).

So basically instead of writing this kind of code inside an EJS file:
`<input type="text" value="<%= locals.cosmo ? locals.cosmo.names.en : '' %>" required />`

We could write it this way:
`<input type="text" value="<%= locals.cosmo?.names.en %>" required />`

Thank you!

**Comment by RyanZim** [comment]
EJS doesn't support babel currently.

**Comment by TyrionGraphiste** [comment]
That's quite an issue.

**Comment by mde** [comment]
It's not a feature that people are clamoring for, but I'd be happy to take a look at a PR that implements it.

**Comment by TyrionGraphiste** [comment]
Beside the fact it could be cool and very useful to support such functionalities, JavaScript is evolving, so EJS should do because it's based on.

My example with optional chaining is only one of them and users from today don't write JavaScript the same way they did in 2010. If you could enhance the JS support it would be awesome!

**Comment by mreis1** [comment]
+1 for optional chaining

**Comment by anonymous675** [comment]
+1 for optional chaining, could be useful in input validation with express-validator. (`<%= errors?.username?.msg %>`)

**Comment by sor-barroso** [comment]
:+1:

**Comment by RyanZim** [comment]
Since Node v14.0.0, optional chaining is natively supported.

**Comment by AyushPowerPlay** [comment]
still EJS support the optional chaining or not?

**Comment by RyanZim** [comment]
Yes, it's supported since Node 14, as stated above.
