### ISSUE TITLE
include file not work

### ISSUE THREAD

**Issue by callor** [mde/ejs#497]
-- error message --
Unexpected identifier in /nodework/Node_04/views/index.ejs while compiling ejs If the above error is not helpful, you may want to try EJS-Lint: https://github.com/RyanZim/EJS-Lint Or, if you meant to create an async function, pass `async: true` as an option.

```
-- index.ejs --


<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <link rel='stylesheet' href='/stylesheets/style.css' />
  </head>
  <body>
    <h1><%= title %></h1>
    <p>Welcome to <%= title %></p>
  </body>
  <% include test.ejs %>
</html>


-- test.ejs --
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title></title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body>
    <h3>Test</h3>
    <h4><%= title %></h4>
</body>
</html>

```

**Comment by RyanZim** [comment]
> NOTE: Include preprocessor directives (<% include user/show %>) are not supported in v3.0+.

https://github.com/mde/ejs#includes

**Comment by callor** [comment]
> > NOTE: Include preprocessor directives (<% include user/show %>) are not supported in v3.0+.
> 
> https://github.com/mde/ejs#includes

Thank you It worked out, Have nice today
