### ISSUE TITLE
[FEATURE] Add includer function to options

### ISSUE THREAD

**Issue by leomp12** [mde/ejs#500]
Hello,

I really need more flexible way to resolve `include` path and Imo [node-sass importer](https://github.com/sass/node-sass#importer--v200---experimental) is a good approach, is it feasible to do something similar for EJS? An `includer` function passed through options?

I think it may also be useful for other users and I can give a try here if you agree :smile: 

Thanks!

**Comment by mde** [comment]
I would definitely be down to implement something like this. Happy to work with you on it, if you'd like to give it a try.

**Comment by leomp12** [comment]
@mde great!
I'm a little busy now but I give a try until the end of this month, is it okay for you to wait a while?

**Comment by mde** [comment]
Sure, no rush. :)

**Comment by leomp12** [comment]
I was thinking about, I guess it can be also useful to create a truly full featured `ejs-loader` for Webpack.
I relaxed here because https://github.com/mde/ejs/pull/501 solves my initial problem, but without further ado, I'm going to work on this next week :smile:

**Comment by leomp12** [comment]
https://github.com/mde/ejs/pull/515
