### ISSUE TITLE
Package is not compatible with node 0.10.0

### ISSUE THREAD

**Issue by andreaazzara** [mde/ejs#502]
package.json declares

`"node": ">=0.10.0"`

however some parts of the package (see postInstall.js script) use keywords incompatible with older versions of node.js

**Comment by mde** [comment]
Apologies for the inconvenience. It's been such a long time, I completely forgot that v0.10 and v0.12 required the `--harmony` flag passed before you could even flip on strict mode. Fixed, and published to NPM in v3.0.2.

Also verified that EJS itself is usable with v0.10 and v0.12, if you pass the `--harmony` flag to the Node executable.

Thanks for flagging this!
