### ISSUE TITLE
Issue with guilds.forEach() is not a function 

### ISSUE THREAD

**Issue by TrissieTheHusky** [mde/ejs#503]
I’ve tried everything it doesn’t wanna take my Authorised account

**Comment by TrissieTheHusky** [comment]
I’m running the latest version

**Comment by mde** [comment]
Very sorry, but you'll have to give us a lot more information before we can help debug this — a code snippet, a way to reproduce the bug, something.

**Comment by TrissieTheHusky** [comment]
So basically this is what I'm getting when this happens
![Image Debug]{https://trissiefiles.ga/AULh)

**Comment by RyanZim** [comment]
Looks like `guilds` is not an array.

**Comment by TrissieTheHusky** [comment]
How would I define that as an array?

**Comment by TrissieTheHusky** [comment]
I would have to make that a string right like something like this ```guilds.array().map(g => g.name)```

**Comment by mde** [comment]
This is clearly an issue in your application code, and nothing specific to EJS. Please feel free to reopen this if you're having an actual issue with EJS itself.
