### ISSUE TITLE
Is there a way to prevent or catch ejs rendering error to show an user-friendly page?

### ISSUE THREAD

**Issue by salatielq** [mde/ejs#506]
I'm searching for a way to show a user-friendly page to the user if I got an error in EJS. 

Even adding `if`s everywhere would be nice to make sure that users can't see EJS errors in production.

Does it have a way or some idea on how to do this?

**Comment by mde** [comment]
Generally this is part of whatever framework you're using. In Express, it would be something like:

```javascript
res.render('index', function (err, html) {
  if (err) {
    res.status(500).send({ error: 'something blew up' });
  }
  else {
    res.send(html);
  }
});
```
If you're using EJS raw, you can try/catch the `render` method.
