### ISSUE TITLE
Javascript file not working

### ISSUE THREAD

**Issue by Quark03** [mde/ejs#511]
I don't know if this is an ejs bug or if it's just me but I can't make my script tag work locally (I'm using bootstrap so it works)  I'm using express too

`<script type="text/javascript" src="http://localhost/scripts/dashboard.js"></script>`

cause my file doesn't even run

My file: 
`console.log('[START] Dashboard JS loaded!');`
`const button = document.getElementById('button-prefix');`
`button.addEventListener('click', function (e) {`
`console.log('button was clicked');`
`});`

If the issue is mine pls tell me

**Comment by mde** [comment]
This is almost certainly not a bug in EJS. We have an extensive battery of tests we run for every release. Maybe you could check the Network tab in your browser's developer tools to see if the file is even being loaded. If you have an actual issue that involves EJS not rendering a template properly, please feel free to reopen, or open another issue.

**Comment by Sharif-Minhaz** [comment]
> This is almost certainly not a bug in EJS. We have an extensive battery of tests we run for every release. Maybe you could check the Network tab in your browser's developer tools to see if the file is even being loaded. If you have an actual issue that involves EJS not rendering a template properly, please feel free to reopen, or open another issue.

Hi, I'm also facing the same issue. In my case, 
```
<script src="/dist/js/owl.carousel.min.js"></script>
<script src="/scripts/main.js"></script>
```
I have 2 scripts but the ejs only accept the first script file and ignore the second javascript file unless the other file is any kind of CDN src. But if I write the inline javascript code inside the ejs file with <script></script> then it's works. and also if I connect a partial with a javascript file then both file works. But it somehow does not work with multiple js files in a single ejs file. 
what is the problem? I don't understand. 😥
