### ISSUE TITLE
res.render called more than once

### ISSUE THREAD

**Issue by khanbaba** [mde/ejs#512]
Hi, I am using express v4.6 and ejs v2.5.6.
The problem is that in async usage the res.render called more than once.
I have posted the problem here: https://stackoverflow.com/questions/61455213/express-ejs-res-render-called-more-than-once

**Comment by mde** [comment]
`res.render` is an express method. This is almost certainly not an issue with EJS. Please feel free to re-open if you can provide a minimal example that demonstrates an actual problem with EJS itself.

**Comment by khanbaba** [comment]
https://github.com/eh3rrera/node-amp-live-list
run this program and go to localhost://127.0.0.1:3000.
and add a log for render calls in server.js

**Comment by mde** [comment]
This is an Express application, and does not demonstrate an actual problem with EJS. The `res` in Express is an object that calls out to EJS. If you are trying to show something happening specifically with EJS, you'll need to write a Node script that does a simple `require` of EJS. You can have a look at the EJS tests to get an idea of how that works.
