### ISSUE TITLE
Uglify (Minify) output HTML

### ISSUE THREAD

**Issue by Fonger** [mde/ejs#52]
Add an option to output pretty html or ugly (minify) HTML as [How Jade does](http://stackoverflow.com/questions/5276892/expressjs-how-to-output-pretty-html).

**Comment by TimothyGu** [comment]
Jade doesn't uglify it. It just doesn't beautify it (it strips all the `\n`) (plus they don't even recommend the use of prettification).

EJS doesn't beautify it, it just doesn't uglify it (literal output) and keeps all the `\n` and spaces in the input EJS file.

We really want to keep EJS small and maintainable. You can always hook EJS output up to some html prettifier easily yourself.

**Comment by TimothyGu** [comment]
Also seems like it is a dup #51.

**Comment by Fonger** [comment]
@TimothyGu However, to improve the performance, it is recommended to minify the content.

At least `ejs` should provide an intermediate function to help hook EJS output as you said.
In production mode, `ejs` static portion will be **cached** in memory in EJS.
It is best to cache the minified version in EJS so I think provide an intermediate function to process the output html will be a great idea.

For example,
```js
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(ejs({intermediate: function(input) {
    return minify(input);
}})
```

**Comment by mde** [comment]
Having some sort of hook to allow minifying what gets cached doesn't seem totally crazy. Feel free to open a new issue for that.
