### ISSUE TITLE
Check Application Environment Before Throwing Error

### ISSUE THREAD

**Issue by jaydadarkar** [mde/ejs#527]
I have been working with EJS for my framework @jaydadarkar/nitromvc. Here, I have an env file where I can set the app environment. EJS, regardless of the environment, throws error to browser. What if EJS checks the Environment, if testing, throw error to browser, if production, log the error to a file (storage/logs/nitrolog.log) and throw a 500 response and I can then render my error template 500.ejs.

**Comment by mde** [comment]
EJS is just a library for rendering templates. It's not a Web app framework. Deciding what to do with rendering errors is the job of whatever framework you're using EJS with.
