### ISSUE TITLE
npm run devdoc fails

### ISSUE THREAD

**Issue by musicin3d** [mde/ejs#541]
Readme states that docs are available by running `npm run doc` or `npm run devdoc`. However, neither of those two commands exist. Should this be removed from the readme? Also, has the lower level documentation moved, or must we read the source instead?

**Comment by musicin3d** [comment]
Note: I was able to run `npx jsdoc lib`

**Comment by musicin3d** [comment]
I was hoping for some guidance on interfacing directly with a `Template` object or using the `client` parameter. Alas, I'll just have to experiment for a while. :(

**Comment by mde** [comment]
I've updated the README to reflect reality, and separated out what was a single `jake` command with flag, into two separate commands for generating doc. Sorry for the inconvenience. If you have specific questions or thoughts about lower-level constructs, I am happy to answer them. Thanks!
