### ISSUE TITLE
Can't render template when key name = "A.a.1"

### ISSUE THREAD

**Issue by wz71014q** [mde/ejs#542]
HTML:

```html
   <p>Name</p>
   <p><%= form.A.a.1%></p>
```

data from interface:

```json
{
  "A.a.1": "something",
  "A.a.2": "something"
}
```

and then throw an error:

```js
missing ) after argument list in XXX.ejs while compiling ejs
```

Do I have to convert "A.a.1" into something else like "A_a_1"?

**Comment by ExE-Boss** [comment]
That’s because you need to do `form["A.a.1"]`, since the property name is `"A.a.1"`.

If you did `form.A.a["1"]`, you’d get a `TypeError` at runtime because `form.A` is `undefined`.

**Comment by wz71014q** [comment]
> That’s because you need to do `form["A.a.1"]`, since the property name is `"A.a.1"`.
> 
> If you did `form.A.a["1"]`, you’d get a `TypeError` at runtime because `form.A` is `undefined`.

It works now,  Thanks！
I've tried form[A.a.1], but I forgot to put it in double quotes!
