### ISSUE TITLE
Documentation is not beginner friendly

### ISSUE THREAD

**Issue by aoliadi** [mde/ejs#544]
There's no info on what files to create, the extension to use for the file (.html or .ejs?), how to link the files and more tangible and very basic info. I need to make a dynamic html template for a project and I'm running around. No blog post nor videos able to bring me up to date. I eagerly await a reply. Thank you. And keep up the good work.

**Comment by mde** [comment]
Hi there. I'm not entirely sure what sort of tutorial you'd need here. People usually use EJS as a part of some other project, like inside an Express server. EJS itself is just the thing that takes the template and data, and turns it into a rendered string.

In any case, the top result for "EJS with Express" was this step-by-step blog post, that would seem to give you at least some of the information you need:

https://scotch.io/tutorials/use-ejs-to-template-your-node-application

Hope that answers your question.

**Comment by mde** [comment]
Feel free to submit a PR to make improvements. The repo for the docs is here: [https://github.com/mde/ejs-site](https://github.com/mde/ejs-site) (for the doc site, [https://ejs.co/](https://ejs.co/))
