### ISSUE TITLE
Doku: Non-html Files

### ISSUE THREAD

**Issue by aersamkull** [mde/ejs#545]
Hi there

EJS seems to be all about generating HTML, at least thats what the docu looks for me. Is there anything that would not work if targeting something else? Say, I want to generate some JavaScript Code or any exotic text? I think this should be documented.

**Comment by mde** [comment]
I am happy to entertain suggestions for the docs. You could submit a PR for the README on this repo, or for the documentation site, which is here: https://github.com/mde/ejs-site/

**Comment by mde** [comment]
I'm going to go ahead and close this issue for housekeeping, but feel free to open a PR, and we can discuss.
