### ISSUE TITLE
Failed at the ejs@2.7.4 postinstall script 'node ./postinstall.js'.

### ISSUE THREAD

**Issue by Grace1115** [mde/ejs#547]
[2020-09-29T19_11_17_796Z-debug.log](https://github.com/mde/ejs/files/5301890/2020-09-29T19_11_17_796Z-debug.log)
[2020-09-29T19_11_17_796Z-debug.log](https://github.com/mde/ejs/files/5301892/2020-09-29T19_11_17_796Z-debug.log)

npm ERR! Windows_NT 10.0.18363
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp" "yo" "@microsoft/generator-sharepoint" "--global"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ejs@2.7.4 postinstall script 'node ./postinstall.js'.
npm ERR! This is most likely a problem with the ejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ejs
npm ERR! There is likely additional logging output above.

**Comment by mde** [comment]
Postinstall has been removed in recent versions. Please install the current version of EJS to fix this.
