### ISSUE TITLE
Where is browser support?

### ISSUE THREAD

**Issue by psociety** [mde/ejs#548]
Website says "Download a browser build from the latest release, and use it in a script tag.", but i:
1. Downloaded a build
2. Grabbed the `/lib/ejs.js`
3. Applied it to html via `<script src="ejs.js"></script>`
3. Got "Uncaught ReferenceError: require is not defined"

**Comment by crossphoton** [comment]
I haven't used ejs in browser though but what I think you have to do is build the script using some bundler like webpack/parcel and then use it.

One option is to use CDNs like here: [https://data.jsdelivr.com/v1/package/npm/ejs/badge](https://www.jsdelivr.com/package/npm/ejs)

**Comment by sseide** [comment]
we are using the latest 2.7 version in the browser - just use the `/ejs.min.js` (not from lib folder) and use this in the browser.

We have not moved to 3.x as that version requires lots of unnecessary dependencies only fetched to provied a cli. And cli is useless inside the browser... see #510
