### ISSUE TITLE
Express static doesn't automatically render indexes

### ISSUE THREAD

**Issue by AuracleTech** [mde/ejs#558]
When I visit a directory where there's an index.ejs file it doesn't automatically renders it, I have to manually verify if it's a directory, and if the directory contains a file called index.ejs, or if it's a file link and the file extension is .ejs

`app.use(express.static(__dirname + '\\www\\'));` Do not render ejs automatically

**Comment by mde** [comment]
That is a feature of Web servers, like Apache/Nginx/IIS, not a low-level rendering library like EJS.
