### ISSUE TITLE
Variable.forEach is not a function

### ISSUE THREAD

**Issue by renanxx1** [mde/ejs#559]
```
 <script>
     
   $(function () {
        
    var atividades = "<%=atividades%>"
          
  atividades.forEach(function (atividade, index) {
             
   alert(atividade[index].grupo)
           
 })
       
 });
    </script>
```

When I try to run this code inside the tag script, I get the error that atividades.forEach is not a function, what can be done to solve it? The "<%=atividades%>" comes from the sequelize.

**Comment by mde** [comment]
I have no idea what you're trying to do here, or how it involves EJS. I wish I could help you, but this is clearly not a problem with the EJS library.
