### ISSUE TITLE
this.templateText.replace is NOT A FUNCTION (SERIOUS ISSUE)

### ISSUE THREAD

**Issue by Backup-eric645** [mde/ejs#561]
I got an exception, not from the templating engine at all, but from the Node V8.
```
########\node_modules\ejs\lib\ejs.js:720
    this.templateText.replace(/[ \t]*<%_/gm, '<%_').replace(/_%>[ \t]*/gm, '_%>');
```

**Comment by jimbo8098** [comment]
This was an issue for me but I managed to get it working. Can you provide a code sample to recreate it? Sorry I can't be more help, but I might remember with a sample.

**Comment by emmyarty** [comment]
This should only happen if the template compiler isn't receiving a template in string form. Are you accidentally passing a promise object or something?

**Comment by ralyodio** [comment]
This happens to me on basic example

```
// Define the data to be used in the template
const data = {
	title: 'EJS Template Example',
	message: 'Hello, World!'
};

// Render the template with the data
const output = ejs.render(data, { filename: 'template.ejs' });
```

template.ejs

```
Dear <%= title %>,

<%= message %>

```

**Comment by emmyarty** [comment]
> This happens to me on basic example
> 
> ```
> // Define the data to be used in the template
> const data = {
> 	title: 'EJS Template Example',
> 	message: 'Hello, World!'
> };
> 
> // Render the template with the data
> const output = ejs.render(data, { filename: 'template.ejs' });
> ```
> 
> template.ejs
> 
> ```
> Dear <%= title %>,
> 
> <%= message %>
> ```

You're not using the function correctly, check the documentation

https://ejs.co/#docs

The template string is the first param, the data object is the second

You're passing them in the wrong way around as well as into the wrong function; if you need general help with learning JS and its ecosystem there are plenty of Discord servers out there, but this isn't legitimate issues with EJS

**Comment by jimbo8098** [comment]
Indeed, should be:

// Define the data to be used in the template
const data = {
	title: 'EJS Template Example',
	message: 'Hello, World!'
};

ejs.renderFile('template.ejs', data, null, function(err, str){
    console.log(str)
});

**Comment by ralyodio** [comment]
Chat-GPT sucks at programming :100:
