### ISSUE TITLE
Idea: Remove Partial

### ISSUE THREAD

**Issue by alhassanv** [mde/ejs#563]
Right know I have buttons on my website that redirect to another page, however if I could unload/remove partials it would be great!

**Comment by mde** [comment]
I'm not sure what you mean by this. Could you describe it better?

**Comment by official-garlic** [comment]
If you plan to unload anyways, Why not only load in the ones that you need? That's the point of partials, no?

**Comment by alhassanv** [comment]
> I'm not sure what you mean by this. Could you describe it better?

Alright so lets suppose I have a page which has a sidebar, and with this sidebar I want to control the content of the middle section of the page. If I click first option loads X template and unload others, second option I load Y template and unload others.

**Comment by mde** [comment]
This would be the purview of whatever framework is using EJS. The most straightforward thing would be to re-render the entire tree, and conditionally call the `include` function. EJS is intentionally simple, and it will stay that way.
