### ISSUE TITLE
Minor Markup Typo on EJS Docs Home Page

### ISSUE THREAD

**Issue by tannerdolby** [mde/ejs#567]
Hey ejs team,

I noticed this closing `<li>` tag managed to find its way into the `<character>` tag on the docs [ejs Home Page](https://ejs.co/)

<img width="308" alt="Screen Shot 2021-01-12 at 8 36 26 PM" src="https://user-images.githubusercontent.com/48612525/104407184-e3d51980-5515-11eb-9fa8-e4e4ec42d5bc.png">

_The closing list item tag within the `<character>` tag_
<img width="470" alt="Screen Shot 2021-01-12 at 8 38 23 PM" src="https://user-images.githubusercontent.com/48612525/104407307-2860b500-5516-11eb-9fc6-b3ae866d38d7.png">

Maybe this isn't a bug or typo but I wanted to bring it to your attention anyways.

**Comment by mde** [comment]
Fixed, thanks. FYI, for future reference, the site is its own GH project: https://github.com/mde/ejs-site/

**Comment by tannerdolby** [comment]
@mde Your welcome. And ok cool, thanks for the heads up. If I see anything in the future I will head over the to `mde/ejs-site` repo and submit the issue or PR there.
