### ISSUE TITLE
Error: Unknown encoding in Node.js 0.8

### ISSUE THREAD

**Issue by dougwilson** [mde/ejs#57]
I tried to update the Express test suite to use ejs 2.2.4, but there were suddenly a lot of failures with `Error: Unknown encoding`

Partial stack trace:
```
Error: Unknown encoding
    at Buffer.toString (buffer.js:440:13)
    at Object.fs.readFileSync (fs.js:241:33)
    at handleCache (/home/travis/build/strongloop/express/node_modules/ejs/lib/ejs.js:75:19)
    at View.exports.renderFile [as engine] (/home/travis/build/strongloop/express/node_modules/ejs/lib/ejs.js:195:14)
    at View.render (/home/travis/build/strongloop/express/lib/view.js:9:2917)
```

Looks like it's coming from https://github.com/mde/ejs/blob/v2.2.4/lib/ejs.js#L75 , which is not using `fs.readFileSync` correctly (at least in Node.js 0.8).

Did ejs drop Node.js 0.8 compatibility suddenly without a major version bump? It looks like there was a note in the 2.1.1.

Let me know if you're going to support Node.js 0.8. If not, I'll look for another templating engine.

**Comment by TimothyGu** [comment]
We don't officially support Node.js 0.8, but I would be happy to apply fixes for it if it's not too ugly.

It seems to me that node 0.10 changed the second argument to `readFileSync` from a string specifying the encoding to an object containing that.

I'll push a fix using `readFileSync(file).toString('utf8')` using the `Buffer.prototype.toString()` function that did not change since 0.8. See if that fixes your problem.

**Comment by TimothyGu** [comment]
See also 4ffd77f4e3258009f3c13e8a939b1657387dbe98 and 58e7f75d5ab3922ea73e3665f782a72a4a68888a. The latter commit was by me who saw 4ffd77f4e3258009f3c13e8a939b1657387dbe98.

**Comment by dougwilson** [comment]
I believe `fs.readFileSync(fileName, 'utf8')` still works on post Node.js 0.8, so that could be a solution as well (replace the options object with a string).

**Comment by dougwilson** [comment]
https://github.com/joyent/node/blob/v0.10.24/lib/fs.js#L274-L275

**Comment by TimothyGu** [comment]
True but I'd rather use documented behavior.

**Comment by TimothyGu** [comment]
I just tested on:

```
> console.log(process.versions)
{ http_parser: '1.0',
  node: '0.8.28',
  v8: '3.11.10.26',
  ares: '1.7.5-DEV',
  uv: '0.8',
  zlib: '1.2.3',
  openssl: '1.0.0m' }
```

Everything seems to work fine with Node.js 0.8. We are still not officially supporting 0.8 though because some of our devDependencies don't support it anymore.

**Comment by dougwilson** [comment]
Thanks, I appreciate making the change anyway :)

**Comment by mde** [comment]
@dougwilson Do you need a bugfix release with this change?

**Comment by dougwilson** [comment]
@mde , no, take your time, I'm in no rush.

**Comment by mde** [comment]
:+1:
