### ISSUE TITLE
EJS template data not rendering on home page

### ISSUE THREAD

**Issue by KirkM9** [mde/ejs#579]
I am using ejs, and the data through my ejs template won't load, despite it showing it loads in my node server. This is how I am attempting to bring it in on my index.ejs home page: 
```
<div class= "data">
        <%- include ('template.ejs', { data }); %>   
        </div>
```
 and in my backend (index.js) , this is how I am rendering the data on my home page 

```
res.render('index', {
          data: data
      });
```
  
Is there anything wrong with this approach?

**Comment by jaydave1412** [comment]
I have some questions 
are you getting any ejs rendering errors
is template.ejs in the same folder as this file(is the path correct)
```
<%= data %>
<div class= "data">
        <%- include ('template.ejs', { data }); %>   
 </div>
```

try doing this and see are you getting any value for data
if yes try printing the value in the template file 

```
<%# template.ejs %>
<%= data %>
```

**Comment by KirkM9** [comment]
Resolved it myself. Was an issue with my express server
