### ISSUE TITLE
Error for missing variable is platform-dependent

### ISSUE THREAD

**Issue by jamisonprianos** [mde/ejs#593]
When templating a string and missing a variable, the EJS tests look for an error message of `Variable_Name is not defined`. This is the case when running in node as well as Chrome. However, running the same code in Safari or iOS browsers results in an error of `Can't find variable: Variable_Name`.

These error values are not documented, so I'm aware they shouldn't be depended on, but they are tested for and consistency would help for edge case handling.

Opening the following HTML page on Chrome results in `Reported Error: "missingVariable is not defined"` while opening it in Safari results in `Reported Error: "Can't find variable: missingVariable"`

```
<!doctype html>
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/ejs@3.1.6/ejs.min.js"></script>
    </head>
    <body>
        <div id="content"></div>
        <script>
            try {
                ejs.render('<%= missingVariable %>', {});
            } catch (error) {
                const message = error.message.split('\n').pop();
                document.getElementById('content').innerHTML = `Reported Error: "${message}"`;
            }
        </script>
    </body>
</html>
```

**Comment by RyanZim** [comment]
This is rooted in the way these browsers handle JS errors themselves; these errors come directly from the browser; they're not generated by EJS itself. As a result, there's no good way for us to fix this.
