### ISSUE TITLE
Add id attributes to the headings on https://ejs.co/ so folks can actually link to specific sections?

### ISSUE THREAD

**Issue by Pomax** [mde/ejs#596]
It would be super useful if I could link someone to the "includes" section, or any other section, but there are no `id` attributes to be found on any of the headings... and that be improved?

**Comment by mde** [comment]
The repo for the site is here: github.com/mde/ejs-site/ I'd be happy to merge a pull request that adds ids.

**Comment by Pomax** [comment]
If I had to time to dive into another documentation codebase, I would. Unfortunately, I don't, so hopefully you (or someone else familiar with that codebase) can add title links so that the entire world can better link to the EJS documentation =)

**Comment by mde** [comment]
It's one single HTML file. I probably won't have time to get to it for a while. Please feel free to re-open this if you feel like pitching ine.

**Comment by Pomax** [comment]
Might as well keep it open and put a "good first bug" on it the? No reason to close it, if it's open source.
