### ISSUE TITLE
Why EJS v2 delete a line break at the end of file

### ISSUE THREAD

**Issue by knjcode** [mde/ejs#60]
I'm just curious. Why EJS v2 delete a line break at the end of file.
I might want to keep it in an original state. What do you think?

**Comment by rogeriopvl** [comment]
+1
 I wrote `gulp-ejs` and I had to keep the `ejs` version at `1.*` because with the removal of the EOL my tests don't pass.

**Comment by TimothyGu** [comment]
I don't care either way on this issue, but if people are relying on this behavior I believed it should be restored.

The restoration process itself looks fairly simple (just remove `.trim()` at the end of the generated function).

**Comment by rogeriopvl** [comment]
@TimothyGu Don't get me wrong.

This is not a matter of "people relying on this behavior". This is a [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_205) that should be respected by `ejs`.

**Comment by TimothyGu** [comment]
@rogeriopvl OK I will fix it. Do note that I didn't write this code.

**Comment by rogeriopvl** [comment]
@TimothyGu thanks :+1:

**Comment by knjcode** [comment]
@TimothyGu @rogeriopvl Thanks.:+1:
