### ISSUE TITLE
Does Node 14 + Gulp 4 + EJS 5 work together?

### ISSUE THREAD

**Issue by OlifemB** [mde/ejs#600]
Error on first occurrence

`ReferenceError in plugin "gulp-ejs"`

Does Node 14 + Gulp 4 + EJS 5 work together or do I need an early version of Node and, accordingly, Gulp 3?

**Comment by mde** [comment]
Sounds like an issue with the Gulp plugin. EJS just executes JavaScript, and is compatible with all modern Node versions. Since this is not an issue with the EJS library itself, I am closing it. Please feel free to open a new one if there is an issue with EJS itself.
