### ISSUE TITLE
EJS Templates playground

### ISSUE THREAD

**Issue by vicjicaman** [mde/ejs#602]
Hi

I just wanted to share a tool that I am working on to edit EJS templates.
You can edit a template and also the style, pre/post javascript and some page configurations.

[https://table.listws.com/table/canvas](https://table.listws.com/table/canvas)

I use it a lot on my projects, I hope that this will be useful for you as well.
Let me know any feedback!

**Comment by mde** [comment]
This looks fantastic. Thank you so much for sharing this with the community!

I will close this issue now. Thanks for sharing your awesome work. :)
