### ISSUE TITLE
Docs update request

### ISSUE THREAD

**Issue by qwerty472123** [mde/ejs#605]
In c6bca15b0ac56f7e9f97a15afae4dd9a759dc1e0, legacy preprocessor include has been removed.

However, [/docs/syntax.md](https://github.com/mde/ejs/blob/0f88383409d9591c910132b313e58f0d70bacdf9/docs/syntax.md) still exist description for “Preprocessor” directive without any warning.

**Comment by RyanZim** [comment]
Fixed in https://github.com/mde/ejs/pull/606.
