### ISSUE TITLE
why button onClick is not working in ejs file?

### ISSUE THREAD

**Issue by Nandakishorpalei** [mde/ejs#607]
<%- include("partials/header") -%>

<button onClick=<%= function(){ return console.log("hello")}; %>

type="submit" name="optionSelect" value="man" >man</button>

<%- include("partials/footer")-%>

**Comment by mde** [comment]
I can't quite tell from your code what it is you're trying to do here, but this is not how EJS works. The code inside the EJS script blocks only renders the template text and returns an HTML string. It doesn't handle client-side interactivity. Right now your script block just contains a function object that EJS will evaluate and throw away at render time.

**Comment by Nandakishorpalei** [comment]
> I can't quite tell from your code what it is you're trying to do here, but this is not how EJS works. The code inside the EJS script blocks only renders the template text and returns an HTML string. It doesn't handle client-side interactivity. Right now your script block just contains a function object that EJS will evaluate and throw away at render time.

> how to execute a function in same ejs through button onClick function  in ejs ?

**Comment by Kalud-Z** [comment]
@Nandakishorpalei Im also trying to accomplish the same thing. Did you figure out how to use the event attribute onclick() on a button ?
