### ISSUE TITLE
How to escape ejs tag within a string?

### ISSUE THREAD

**Issue by anhlu8** [mde/ejs#615]
```
<%
   let myString = "this is a string %> with special characters";
   let myOtherString = "this is a string <% with special characters";
   // Do something
%>
```

I need to use these special characters in my JS string `<%` and/or `%>` . But EJS template would return errors: `Could not find matching close tag for "<%"` or `SyntaxError: Invalid or unexpected token while compiling ejs` for `%>`

How should I go about this?

**Comment by RyanZim** [comment]
See https://github.com/mde/ejs/blob/master/docs/syntax.md#literal-tags for details. In your example, you would write:
```
<%
   let myString = "this is a string %%> with special characters";
   let myOtherString = "this is a string <%% with special characters";
   // Do something
%>
```
