### ISSUE TITLE
arrow function getting interpreted as closing tag

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [mde/ejs#618]
I want to use an arrow function inside an ejs scriplet tag as shown below:
 `<button type="button" class="loveButton" id="<%= post._id %>" onclick=<% () => loveFunc(event) %> >` However the arrowhead is being interpreted as the closing tag for the ejs tag there.

**Comment by jkalandarov** [comment]
If you already declared `loveFunc` function, why do you still want to use anonymous function?
You can simply use `onclick=<% loveFunc(event) %>`

**Comment by Ankur-Khandelwal** [comment]
@jkalandarov because without using the anonymous function, the function is getting called even without clicking the button.

**Comment by Kalud-Z** [comment]
@Ankur-Khandelwal did you figure out how to do this ? Im stuck also

**Comment by Ankur-Khandelwal** [comment]
@Kalud-Z No I couldn't.

**Comment by RyanZim** [comment]
You're confusing templating and HTML event attributes. You can't call a function in your EJS onclick.
