### ISSUE TITLE
You can render strings that use ejs tags

### ISSUE THREAD

**Issue by jcubic** [mde/ejs#620]
```
<% "<% %>" %>
```
This should work. In comparison JavaScript template literals have no issue with object literals inside:

```
`say: ${{toString: () => "hello"}} world`
```

To fix this, you need a JavaScript parser.

**Comment by RyanZim** [comment]
This is what we have literal tags for: https://github.com/mde/ejs/blob/main/docs/syntax.md#literal-tags
