### ISSUE TITLE
contentFor not working

### ISSUE THREAD

**Issue by rahulkathet** [mde/ejs#623]
ContentFor() not working when adding inline script tag.

<img width="334" alt="Screenshot 2021-09-05 at 8 56 11 AM" src="https://user-images.githubusercontent.com/813913/132113928-61db1d13-c71f-4954-9629-1714bef972d4.png">
<img width="249" alt="Screenshot 2021-09-05 at 8 56 00 AM" src="https://user-images.githubusercontent.com/813913/132113930-c405a455-67a0-4877-90b5-f3938c80c3bd.png">
<img width="458" alt="Screenshot 2021-09-05 at 8 55 50 AM" src="https://user-images.githubusercontent.com/813913/132113931-84290199-3588-4817-802d-a617b36132a1.png">

**Comment by mde** [comment]
ContentFor is neither JavaScript, nor part of the EJS API. Looks like it's something from Sinatra or Handlebars? Anyhow, it's not EJS. Closing this issue. Please feel free to reopen if there is an actual problem with EJS.

**Comment by rahulkathet** [comment]
> ContentFor is neither JavaScript, nor part of the EJS API. Looks like it's something from Sinatra or Handlebars? Anyhow, it's not EJS. Closing this issue. Please feel free to reopen if there is an actual problem with EJS.

Thank you for the information, just sharing if someone else is looking for a solution.

The issue was with "express-ejs-layouts"

Not working when it is set to "true"
`sampleapp.set("layout extractScripts", true)`

Resolved when set to false
`sampleapp.set("layout extractScripts", false)`
