### ISSUE TITLE
How to refresh the EJS page from the node server

### ISSUE THREAD

**Issue by vinodhreddygs** [mde/ejs#636]
Hi,
How can I update the new data to the EJS page (to the page which already rendered), on every DB update.
I tried out with the below code snippet but its not updating the new data to the ejs page:
  ```
res.rerender('index', {
                data: orderdetails
            });
```
Thanks in advance.

**Comment by mde** [comment]
This is a problem with Express, or whatever Web framework you're using, not with EJS itself. You're better off submitting this question to the community for that Web framework.
