### ISSUE TITLE
How to render jsp comment

### ISSUE THREAD

**Issue by laampui** [mde/ejs#643]
i want to render this line:
`
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
`

i tried below, they didn't work
`
<%%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%%>
`
`
<%- <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%> %>
`

**Comment by mde** [comment]
You don't need the double percent when closing a literal comment. It's only an opening tag:

```javascript
> let ejs = require('./ejs');
undefined
> ejs.render('<%%@ foo="bar" %>');
'<%@ foo="bar" %>'
```
