### ISSUE TITLE
Why <%= title %> and welcome.. not removed from the template?

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [mde/ejs#65]
I've removed <%=title%> code from all my template files but they are still visible in output. Why? Am i missing something?

**Comment by mde** [comment]
Sounds like template strings are being cached. Can you verify whether or not this is the case?

**Comment by RyanZim** [comment]
This thread is over a year old. I'm giving @AhtashamImtiyaz 7 days to respond or I'll close this.

**Comment by RyanZim** [comment]
No Response; Closing.

**Comment by mde** [comment]
:+1:
