### ISSUE TITLE
vulnerability detected in ejs 3.1.6

### ISSUE THREAD

**Issue by vjram555** [mde/ejs#650]
we are getting vulnerability in fortify scan sonatype issue when using ejs 3.1.6 version
currently am using node 12.14.0 version
Is there any recommendation node version or ejs version available to avoid this issue ?

**Comment by mde** [comment]
These automated scans often result in false positives. Can you point me to the specific supposed vulnerability?

**Comment by python-coding-404** [comment]
gkvuyjtgjhhzdfifoskjksfmf,fsfsdf
