### ISSUE TITLE
Variable gets pushed out of tag?

### ISSUE THREAD

**Issue by 7heMech** [mde/ejs#652]
Why does this:
![this](https://user-images.githubusercontent.com/83923848/158232981-4dac1d35-0ac6-44cf-8138-4b3b2c9db727.PNG)
Compile to this:
![CaptureResult](https://user-images.githubusercontent.com/83923848/158233260-5ca300c2-a26e-49b0-ba1b-33e6b5b4d562.PNG)

Code in Image:
```html
<table class="table table-sm table-bordered">
   <tbody>
      <tr>
         test
      </tr>
   </tbody>
</table>
```

**Comment by mde** [comment]
First of all, `test` is not a variable. It's not inside any EJS delimiters. Secondly, the reason it likely renders outside your table is because you are missing `<td>` tags.
