### ISSUE TITLE
How to pass data from main script to <script>tag when rendering ? 

### ISSUE THREAD

**Issue by rsa408** [mde/ejs#661]
In `index.ejs ` I have a word cloud that is using wordcloud2.js @timdream.

```
<canvas id="canvas"></canvas>
            <script>
                WordCloud(document.getElementById('canvas'), {
                    list: <=%targetlist%>
}); 
            </script>
```
In the main script(app.js) which is using express the following code generates targetlist and after that index.ejs will render again. I try to send the targetlist from the main script to the front to generate word cloud.

```
for (const [key, value] of Object.entries(output.list)) {
               targetlist.push([`${key}`, value]);            
            }        
            response.render('index',{targetlist:targetlist});

``` 
it is not passing data to script tag.

**Comment by mde** [comment]
The <script> tags is for rendering EJS in the browser. Looks like you want to run it in the server. There are many examples online for how to use EJS with Express in this way.

Having said that, this is not a problem with EJS. This is a problem with your application code. I am going to close this issue. Please feel free to reopen if you have an actual issue with EJS itself.
