### ISSUE TITLE
Missing release assets on 3.1.7

### ISSUE THREAD

**Issue by StaberindeZA** [mde/ejs#670]
Hello

It looks like for release 3.1.7, the release assets are missing the following 2 assets that were available in the previous releases.
- `ejs.js`
- `ejs.min.js`

Will these assets be added at a later stage? I did find this closed issue #564 , but I thought I'd still check to make sure.

Thank you in advance.

**Comment by mde** [comment]
I pushed the release and had to start my workday. I'll add the compressed assets as soon as I can. Thanks for the gentle nudge!

**Comment by pdehaan** [comment]
Thanks @mde! 🎉

**Comment by mde** [comment]
Again, apologies. I've added the assets. It's been a manual process up to this point. Looks like it's time to consider automating this using GH's release API.

**Comment by StaberindeZA** [comment]
Woah, thanks for the quick turn around in adding the assets. That fixes our issue. Much appreciated, thank you! 🙏
