### ISSUE TITLE
Using Spread operator

### ISSUE THREAD

**Issue by alannaidon** [mde/ejs#682]
I'm wondering if is possible/allowed to use **spread operator** with EJS. like:

```
my.test( `<%= userId %>`, { data: { name: `<%= user.name %>`,  code: `<%= user.code %> ` } } )

// do something like

my.test( `<%= userId %>`, { data: { name: `<%= user.name %>`,  code: `<%= user.code %> ` ,  `<%= ...user.metadata %> } } )
```  

Tried this, but when I check the html, It is shown as `[object Object]` and I can't see the real value.

**Comment by RyanZim** [comment]
The spread operator works in EJS if your runtime supports it. However, the spread operator does not produce strings, so you can't use it to output values. `JSON.stringify(object)` will print the JSON for an object, which is one way to see the contents of an object (assuming it's plain data that can be rendered as JSON).

**Comment by alannaidon** [comment]
Hi @RyanZim . Thanks for the quick reply!

But should it be throwing **Error 500** ?

If I just place the object like
`<%= user.metadata %>` I get the `[object Object]` 

but with spread operator it throws **error 500**  even if the object isn't empty.  
`<%= ...user.metadata %>` OR `<%= ...(user.metadata ?? {}) %>`
