### ISSUE TITLE
Parse required variables from file

### ISSUE THREAD

**Issue by willwill96** [mde/ejs#683]
Apologies if this has already been asked or if this is the wrong place to put this question.

It's typical for me to create a CLI command along with my ejs templates. It would be nice if I could automate some of the argument and/or type definitions.

What I'm looking for is a utility to scaffold typescript types based on my ejs template. I am not looking for anything too complicated (I'm not looking for type inference). 

At a minimum, just getting a list of all required variable names would be good enough for my purposes. 

It feels like this is something that may already be available somewhere in `.ejs`, but maybe it's not part of the public API, or my google skills are just rusty :laughing:

**Comment by mde** [comment]
I'm not sure what you're asking for here. EJS already ships with a CLI itself. And of course, as it's EJS (not ETS), we don't do types. Could you flesh this request out a bit more?
