### ISSUE TITLE
Markdown as a feature

### ISSUE THREAD

**Issue by LebCit** [mde/ejs#688]
Hello EJS team,

Thank you so much for your time and all your efforts, EJS really rocks !
It would be a great feature if we could write post(s) content with markdown (with front matters) and include it in an EJS template.
This idea came while writing a [beginner guide](https://lebcit.github.io/posts/templating-a-nodejs-app-with-ejs/).

Thanks again for everything.

SYA,
LebCit

**Comment by mde** [comment]
Very nice Beginner's Guide!

Unfortunately, Markdown is a completely different templating language. It would be outside of the scope of what EJS is supposed to be. EJS is simply templating using JavaScript.

**Comment by LebCit** [comment]
Hello,

Thank you very much for your response.
After a lot of research and tries and fails, I've managed to achieve my simple goal : [Markdown blog with EJS](https://lebcit.github.io/posts/markdown-blog-with-ejs/)

Thank you for your time and all your efforts

SYA,
LebCit

**Comment by mde** [comment]
Trial and error is how you become a good software developer. Very nice work!
