### ISSUE TITLE
We Can't edit data from browser side js

### ISSUE THREAD

**Issue by mhasnat142** [mde/ejs#692]
i want to edit data after ajax request but i searched a lot nothing found about how to edit data form browsersie js

**Comment by mde** [comment]
You'll have to retrieve the data, and then use EJS to render a template. Update the DOM with the new template content, using innerHTML or similar. This isn't really an issue with EJS itself, and I can't tell you how to architect your app, so I'll be closing this issue now. If you discover an actual problem with EJS itself, feel free to open another issue.
