### ISSUE TITLE
ejs raises error when include in for loop

### ISSUE THREAD

**Issue by TrueXPixells** [mde/ejs#695]
code; 
```ejs
    <% rand.forEach(function (x) { %>
    <%- await include("util/botcard", {bot: x}) %>
    <%})%>
```
raises
```
SyntaxError: missing ) after argument list in ./views/index.ejs while compiling ejs
```

but this code not raises error;
```ejs
    <% rand.forEach(function (x) { %>
    <%- include("util/botcard", {bot: x}) %>
    <%})%>
```
my ejs render;
```js
            const standole = await ejs.renderFile("", {}, { async: true });
            res.send(standole);
```

**Comment by mde** [comment]
I'm not certain about the specific error you're seeing, but for starters, `forEach` does not work with `await`. And I'd have to go back to the code to be sure, but I don't think `include` is async in the first place?

**Comment by TrueXPixells** [comment]
i dont know but ejs has a LOT OF issuses;
i solved this problem but include renders html to last point (with await loop, bad eng im sry)
ok. im closing this issuse

**Comment by mde** [comment]
Again, this is not any sort of issue with EJS. There is an extensive suite of tests we run for every release, and millions of installations every week. There are a tiny number of reported issues, and these types of problems are almost always in the userland code.
