### ISSUE TITLE
Why is the result of using await to obtain promise in ejs [object promise]?

### ISSUE THREAD

**Issue by xiaowang-create** [mde/ejs#697]
Our company's native development encountered this problem, help!

**Comment by RyanZim** [comment]
Without any example code, it's hard for me to figure out what issue you're encountering.

**Comment by ben1one** [comment]
Try set async to false
```
const html = await ejs.renderFile(
    path.resolve("src/template", "index.ejs"),
    {},
    { async: false, cache: false },
);
```

**Comment by mde** [comment]
The `async` setting needs to be set to true, yes. Also worth noting that only the file I/O is async. It's generally more efficient if you can to do your I/O up front and keep template strings in a cache if you can.
