### ISSUE TITLE
Unescaped Values Won't Display Inside <textarea>

### ISSUE THREAD

**Issue by bmills23** [mde/ejs#699]
I'm trying to render unescaped html inside a <textarea> element, and it doesn't render.

e.g.

`<textarea> <%- blog[i].content %> </textarea>` outputs something like 
`<p>Example Text</p>` within the textarea box.

This won't work for text inputs as well.  I'm wondering if there's a way around this.

**Comment by mde** [comment]
"The textarea element represents a multi-line plain-text editing control":

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea 

I am guessing you want a content editable div:

https://stackoverflow.com/questions/4705848/rendering-html-inside-textarea
