### ISSUE TITLE
Unable to resolve module fs in react native project

### ISSUE THREAD

**Issue by TomCorvus** [mde/ejs#700]
Hi,

I have a dependency in a React Native which need EJS and when I start my app, I have this error :

```
error: Error: Unable to resolve module fs from /Users/.../node_modules/ejs/lib/ejs.js: fs could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  46 |
  47 |
> 48 | var fs = require('fs');
     |                   ^
  49 | var path = require('path');
  50 | var utils = require('./utils');
```

How to avoid this error?

Thank you

**Comment by RyanZim** [comment]
You'll need to bundle your app in a way that it stubs the `fs` module.

**Comment by TomCorvus** [comment]
Thanks @RyanZim. Any idea to fix this?

**Comment by RyanZim** [comment]
Not a RN dev, so can't really help here; https://github.com/tradle/rn-nodeify might be useful though.
