### ISSUE TITLE
javascript value inside ejs script tags in side <script> in html

### ISSUE THREAD

**Issue by VidulHB** [mde/ejs#702]
this is the code:
![image](https://user-images.githubusercontent.com/66768720/200749458-950f27cd-661e-4422-ba56-f87f10350599.png)
in the website it becomes this:
![image](https://user-images.githubusercontent.com/66768720/200749584-4e55f3b6-b922-4dbc-9b6e-dcd846bf0540.png)
but i if remove 'i' and 1 it works
how do i make the code work?

**Comment by mde** [comment]
That looks like you're mixing EJS and JavaScript template literals. I'm not sure what you're trying to do there, but I can't help people debug their application code. If you can demonstrate a specific problem with EJS itself, please feel free to reopen this issue.
