### ISSUE TITLE
Ejs snippets add a whitespace character after the output

### ISSUE THREAD

**Issue by Arti-Art** [mde/ejs#705]
Hi, I was wondering why all EJS snippets add a whitespace character after the output.
Example: `<p>ejsout+tab</p>` will result in `<p><%=  %> </p>`, and not `<p><%=  %></p>`
Is there a reason for it? Or is it a setting to tweak? It is annoying to manually remove those whitespaces.

**Comment by mde** [comment]
From the docs, at http://ejs.co/:

 <img width="574" alt="Screen Shot 2022-12-16 at 22 54 47" src="https://user-images.githubusercontent.com/757/208229801-027a658f-4844-43fe-b050-38816d58a506.png">
