### ISSUE TITLE
Not an issue. Blog-Doc : a tiny blog and documentation SSG app.

### ISSUE THREAD

**Issue by LebCit** [mde/ejs#712]
Hello,

Just letting you know that I've created a Node.js app that can be directly used (on a Node.js server) to create a personal/docs site.
On the other hand, this app can be used to generate a static site out of the Node.js app.

Blog-Doc is written in JavaScript, using **EJS as a templating language** and Markdown to write and format the markup of the generated posts and pages.

You can see a live demo of the Node.js app on [Blog-Doc homepage](https://blog-doc.deta.dev/)
You can see a live demo of the static site on [Blog-Doc static homepage](https://blog-doc-static-express.deta.dev/)

Read more about it on it's [documentation page](https://blog-doc.deta.dev/doc)
[GitHub repository](https://github.com/LebCit/blog-doc)

Comments, feedback, suggestions and ideas are mostly welcome and appreciated 😃

SYA

**Comment by mde** [comment]
Looks great. Best of luck!
