### ISSUE TITLE
extend and block feature in ejs

### ISSUE THREAD

**Issue by mdtausifiqbal** [mde/ejs#713]
I came from jinja2 templating, and feeling there is a lack of block and extend features in ejs. please add this feature to ejs.

**Comment by mde** [comment]
EJS has partials. Anything you might want to do with block or extend, you can do with partials.

**Comment by RobotoSkunk** [comment]
Yeah, partials exist, but they're not efficient as blocks if the layout uses stuff like containers.

They can be done with partials, but in a dirtiest way
