### ISSUE TITLE
Use vanilla js (browser) content in ejs

### ISSUE THREAD

**Issue by AngeloCore** [mde/ejs#714]
For example:
```ejs
<% let test = %> getSomething();

<h1><%= test %></h1> //SOMETHING

<script>
function getSomething() {
  let smh = 'SOMETHING';
  return smh
}
</script>
```

**Comment by mde** [comment]
This will actually work, if your function `getSomething` is defined in the global context (and before you attempt to execute), and you put the function reference inside the JS block: `<% let test = getSomething(); %>`.

The key here is understanding that all EJS does is build a string of executable JavaScript that it then runs in the global context, when you render the template. That's it.
