### ISSUE TITLE
Not able to start the text from new page

### ISSUE THREAD

**Issue by EvolverPawan** [mde/ejs#716]
Hi Team, 

Is there a way I can start printing from next page.
Problem we are facing: while creating pdf image/text in continuation is cutting and split into two pages. If there a way we can explicitly demand for next page.

**Comment by mde** [comment]
This has nothing to do with EJS. However, you might be looking for the `break-after` CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/break-after
