### ISSUE TITLE
Can Ejs be used in a Chrome Extension?

### ISSUE THREAD

**Issue by MRYingLEE** [mde/ejs#723]
I tried but couldn't find a way to use it. 
There was always an error:

_Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*"._

The suggested policy was declined by Chrome.

Any ideas?

**Comment by MRYingLEE** [comment]
Sorry, I just found the issue was duplicated. The issue was closed for there is no practical way to fix it yet.

**Comment by ExE-Boss** [comment]
Duplicate of <https://github.com/mde/ejs/issues/468>
