### ISSUE TITLE
document which operators are available

### ISSUE THREAD

**Issue by kevinburkeshyp** [mde/ejs#73]
from the README it looks like `if` is available. how about `else if`, `else`, `or`, etc.? I cannot find this information in the docs on http://ejs.co or the README

**Comment by mde** [comment]
I didn't think we needed to explain -- it's just JavaScript. You can run any arbitrary JS that you want in a tag. That means all the JS operators are available.

**Comment by RyanZim** [comment]
@mde, any reason to keep this open?

**Comment by mde** [comment]
:+1:
