### ISSUE TITLE
ejs v3.1.9 is vulnerable to server-side template Injection

### ISSUE THREAD

**Issue by saimanepalli** [mde/ejs#736]
Please help me to fix the ejs v3.1.9 is vulnerable to server-side template Injection. I have gone through all the links but they don't have valid fix.
https://github.com/advisories/GHSA-j5pp-6f4w-r5r6

**Comment by mde** [comment]
There is already a ticket for this:

https://github.com/mde/ejs/issues/720

 It is not a vulnerability. We are waiting for them to remove this report. It is not valid.
