### ISSUE TITLE
Multi line comments break rendering

### ISSUE THREAD

**Issue by bladeSk** [mde/ejs#74]
There doesn't seem to be any way of commenting out certain pieces of code spanning multiple lines. For instance this code throws an error `Could not find matching close tag for "<%".`:
```javascript
<% /*if (true) { %>
    <p>hello</p>
<% }*/ %>
```
..as does this one:
```javascript
<% /*
    <% if (true) { %>
        <p>hello</p>
    <% } %>
*/ %>
```
..and even this breaks:
```javascript
<%# /*
    <% if (true) { %>
        <p>hello</p>
    <% } %>
*/ %>
```

Not being able to use block comments is very inconvenient. Sometimes it's useful to experiment with a few versions of code without completely deleting it or having to move it outside of the file.

A simple way of fixing this would be adding support for standard block comments - e.g. when a `<% /*` tag is found, EJS would search for a matching `*/ %>` or perhaps adding a multi-line comment tag `<%## ... #%>'.

**Comment by TimothyGu** [comment]
Your first case works fine here.

EJS uses a very naïve bracket matcher, so cascaded tags do not and are not supposed to work. Hence your second and third examples don't work.

**Comment by TimothyGu** [comment]
Make sure that you have the newest version of ejs installed.

**Comment by bladeSk** [comment]
Oh, sorry, the first one really does work with the latest version, my npm had cached an older version.

But still, the second example should work too. Without that working, you just can't comment out any piece of code (with nested tags). I think it's pretty easy to implement with the current naive matcher, adding just one condition should be enough - when encountering a `<% /*`, ignore everything until finding a `*/ %>`.

I could fix it and make a pull request, if you wish. It's just a matter of tweaking `generateSource()` a bit.

**Comment by TimothyGu** [comment]
Yes you can:

```js
<% /* %>
    <% if (true) { %>
        <p>hello</p>
    <% } %>
<% */ %>
```

I don't like the idea of special casing `<% /*`. EJS is designed to be simple, and too much special casing is the exact opposite of what we are trying to do.
