### ISSUE TITLE
Support for full file paths in includes?

### ISSUE THREAD

**Issue by cfreman** [mde/ejs#75]
Is there anyway to pass a full path instead of a relative one to an Include?

We have the code split into different components. Since Express now supports multiple views folders there is no problem there, but when we want to include an ejs from another component (such as common header for a page) we have to things like `<% include ../../../../../components/header.ejs%>` which looks horrible.

I've created a function to get all the views, extract the full path and transform something like
`<%- include(getView('components/header.ejs')); %>` into `<%- include ('/projectpath/common/components/header.ejs');%>`

However since full paths are not supported this obviously doesn't work. Is there a workaround for it? Is this going to be supported at some point in the future?

**Comment by TimothyGu** [comment]
It should work. See #11, #15.

**Comment by cfreman** [comment]
Thanks!

**Comment by TimothyGu** [comment]
In general [docs/syntax.md](https://github.com/mde/ejs/blob/master/docs/syntax.md) is the definite specification on EJS syntax. I assume that by "documentation" you meant README.md, which is meant to be a quick-start guide.

But in any case I tried to clarify a bit more in both documents. See 832bba83b4f6dfc6b8779d64827c23d45dc4e56c and d9f1df9b0cd19660d0ae3bb8708eee4228da28ab.
