### ISSUE TITLE
Meterian Scan - Security Issue (concat-map version 0.0.1)

### ISSUE THREAD

**Issue by nesho84** [mde/ejs#750]
Meterian Scan in our Gitlab CICD found a Critical Security Issue about .ejs which is using a very old version of “concat-map:0.0.1” dependency.

Is there any new Update comming soon?

Thank You :)

**Comment by vigvuv-jozNa4-hycnas** [comment]
** **

**Comment by vigvuv-jozNa4-hycnas** [comment]
#The most common type is the following three 3️⃣ to the right of the left side 25.74

**Comment by mde** [comment]
EJS v4 coming soon.

**Comment by vigvuv-jozNa4-hycnas** [comment]
The god
