### ISSUE TITLE
How to replace filter functionnality

### ISSUE THREAD

**Issue by jmcollin78** [mde/ejs#76]
Hello,

Due to release upgrade my code don't work anymore due to this piece of code:
`ejs.filters.toLocaleDateString = function(d) {...}`

I wonder how to replace the filters fonctionnality that was in V1 ?
Have a guide line for doing that ?

Thank's in advance,

Jean-Marc

**Comment by mde** [comment]
It looks like someone has added a custom filter that does nothing but call `toLocaleString()` on date objects. If this is something you do a lot in your code, you can create a helper method, and load that helper into the locals, so it's available in all your templates. EJS is really just plain executed JS, so you can do anything you'd do in plain vanilla JS.

**Comment by jmcollin78** [comment]
Hi mde !

Thank's for your answer. This helps a lot.

**Comment by TimothyGu** [comment]
Using locals does bring some performance hit, as they are called at render time rather than compile time, like now-removed filters are.

**Comment by IgorDePaula** [comment]
I received thie error

![error](https://cloud.githubusercontent.com/assets/2833993/6852627/830854c4-d3c4-11e4-97f4-084769f9a82a.png)

**Comment by mde** [comment]
Filters were removed in v2; they weren't part of core EJS functionality, and they're easy to implement with your own helpers.

**Comment by IgorDePaula** [comment]
How I implement a custom helper?

2015-03-26 16:14 GMT-03:00 Matthew Eernisse <notifications@github.com>:

**Comment by IgorDePaula** [comment]
When I use app.locals the ejs engine throw error because he dont recognize
the tag <%- %>, if I use <%= the function body is printed on screen.

2015-03-26 16:20 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by mde** [comment]
Write a JavaScript function, and pass it in with your local vars, or make an object with all your helper functions on it, or run your EJS in a context that get a reference to some helper object you've created. Ex:

```javascript
var people = ['geddy', 'neil', 'alex'],
    helperFunc = function (inputString) { return inputString.toUpperCase(); };
    html = ejs.render('<%= helperFunc(people.join(", ")); %>', {people: people, helperFunc: helperFunc});
```

**Comment by mde** [comment]
That's not a valid tag. Here are the docs: http://ejs.co/#docs

**Comment by IgorDePaula** [comment]
The docs says that is a valida tag yeah
Tags

   - <% 'Scriptlet' tag, for control-flow, no output
   - <%= Outputs the value into the template (HTML escaped)
   - <%- Outputs the unescaped value into the template
   - <%# Comment tag, no execution, no output
   - <%% Outputs a literal '<%'
   - %> Plain ending tag
   - -%> Trim-mode ('newline slurp') tag, trims following newline

I'll try again..


thanks for your attention


2015-03-26 16:37 GMT-03:00 Matthew Eernisse <notifications@github.com>:

**Comment by mde** [comment]
Oop, sorry, distracted, totally misread your code. `<%-` is indeed a valid opening tag. It just doesn't escape the output.

**Comment by IgorDePaula** [comment]
My index.ejs is :

<p>Welcome to <%= title %></p>
<%= menuMounter()%>

In app.js is:

var ejs = require('ejs');

app.locals.menuMounter = function menuMounter() {
    var menu = require('./config/menu.json');
    var template = fs.readFileSync('./lib/menumounter/menu.ejs', 'utf-8');
    return ejs.render(template, menu);
  };

I received this error:

SyntaxError: C:\Users\Analista-02\projetos\teste-express\views\index.ejs:10
    8|     <h1><%= title %></h1>
    9|     <p>Welcome to <%= title %></p>
 >> 10| <%= menuMounter()%>
    11|   </body>
    12| </html>
    13|

Unexpected token % while compiling ejs



2015-03-26 16:58 GMT-03:00 Matthew Eernisse <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Sorry, I start understand now. Sorry again.

2015-03-26 17:08 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by IgorDePaula** [comment]
I do the function work, but I can't use it recursively. Any suggestions?

2015-03-26 17:28 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by mde** [comment]
We should probably open a new ticket for this. This ticket has nothing to do with this issue, and has been closed.

**Comment by IgorDePaula** [comment]
Ok,I resolved already. Thnaks.

2015-03-26 17:44 GMT-03:00 Matthew Eernisse <notifications@github.com>:
