### ISSUE TITLE
How to deply express app with ejs files on netlify.

### ISSUE THREAD

**Issue by h-a-entertainment** [mde/ejs#767]
Movie-App/
├── node_modules/
│   └── files related to modules
├── public/
│   ├── css/
│   │   └── theme_1.css
│   ├── js/
│   │   ├── app.min.js
│   │   └── search.js
│   ├── images/
│   │   └── logo.png
├── views/
│   ├── cast.ejs
│   ├── contact-us.ejs
│   ├── country.ejs
│   ├── filter.ejs
│   ├── genre.ejs
│   ├── index.ejs
│   ├── movie.ejs
│   ├── movies.ejs
│   ├── production.ejs
│   ├── search.ejs
│   ├── series.ejs
│   ├── terms.ejs
│   ├── top-imdb.ejs
│   ├── tv-series.ejs
│   └── watch-movie.ejs 
│   └── watch-series.ejs 
├── .env
├── app.js
├── package.json
├── package-lock.json
├── netlify.toml
└── netlify/functions/
    └── api.js
This is my directory 
when i deploy my project on netlify on my main url error occurs "Cannot GET /" that i define in route to work with index.ejs
but i can access my css and js file from main url "https://***entertainment.netlify.app/css/theme_1.css"
how could i deploy my project using ejs files to show in main url on nrtlify

**Comment by Zafkiel45** [comment]
I don't know if Netlify works well with Node.js. As far as I know, it works perfectly well with Front-end.


Given that Node.js is specifically for back-end, other deployment providers like “Renders” might be better. They have free plans to try out and it basically works like a normal Front-end site. 

The only difference is that the site is server-side, something like what Next.js does (but not the same).

If you've already checked whether Netlify works with Backend applications well, disregard my comment and I apologize for not being so helpful :)

**Comment by mde** [comment]
Even if we had full access to application code, we could not spend time debugging people's apps. Happy to address problems that are specifically with EJS itself. If you can show us a specific problem, or provide a minimal test demonstrating some kind of breakage with actual EJS, we are happy to take a look.
