### ISSUE TITLE
[Nest.js + EJS Template] getting Error: Cannot find module 'ejs' deploy on vercel

### ISSUE THREAD

**Issue by Govindsavaliya** [mde/ejs#775]
in main.ts
 app.setBaseViewsDir(join(__dirname, '..', 'Views'));
  app.setViewEngine('ejs');
  app.useStaticAssets(join(__dirname, '..', 'public'));
  
  
![image](https://github.com/user-attachments/assets/fa694201-d699-4967-8200-ff084e5eafa3)

in vercel.json
![image](https://github.com/user-attachments/assets/b73405f8-ff5e-4d76-a41e-4f7c139775e9)

**Comment by RyanZim** [comment]
I'm guessing you don't have ejs defined as a dependency in your package.json. In any case, not an issue with the ejs library itself.
