### ISSUE TITLE
Inconsistent Behavior When Rendering EJS Template with Undefined Variable

### ISSUE THREAD

**Issue by Simon-barbier** [mde/ejs#776]
When using the following EJS template:

```
<% if (user) { %>
  USER <%= user.id %>
<% } else { %>
  NO USER
<% } %>
```

Rendering the template without defining the user variable in the data object (e.g., `ejs.render(template, {})`) results in the error:
```
ReferenceError: user is not defined
```

This behavior is inconsistent with other scenarios where no error is thrown, such as:
- `ejs.render(template, { user: undefined })`
- `ejs.render(template, { user: null })`

The current behavior is problematic, especially when working with JSON-encoded data, as JSON encoding excludes undefined properties by default. While it is reasonable for EJS to throw an error if attempting to directly print or access properties of an undefined variable, the inconsistency makes handling such cases cumbersome.

This inconsistency complicates workflows and handling dynamic data structures. Could EJS handle undefined variables in a more consistent manner?

Demo: https://codesandbox.io/p/sandbox/yhxn2h

**Comment by Simon-barbier** [comment]
I discovered a workaround by using the following:
`<% if (typeof user !== 'undefined') { %>`

However, this approach is inconsistent. For example, the following template does not cause an issue:
```
<% if (info.user) { %>
  <h2><%= info.user.name %></h2>
<% } else { %>
  NO USER
<% } %>
```

when rendered with an "unprovided" user:
`ejs.render(template, { "info": {} }).`

**Comment by mde** [comment]
As you may have discovered, this is how JavaScript itself handles undeclared variables (throws) vs. declared variables set to empty values such as `null` or `undefined`, or unset properties on an object (returns the value `undefined`, which is falsy). This is how JavaScript works.

**Comment by Simon-barbier** [comment]
Indeed, 

now, that sounds stupid after figuring out.

Somehow got confused by the first example of the doc where `data` is not detailed.

**Comment by mde** [comment]
All programming languages have weird things, and JS is no exception. Live and learn. :)
