### ISSUE TITLE
Add features to support to validate templates

### ISSUE THREAD

**Issue by jskungfu** [mde/ejs#80]
Currently there is no support to html lint/hint. This will be really great addition so that we can sanitize html to reduce possible errors.

**Comment by RyanZim** [comment]
Not sure what you are referring to, could you clarify a bit?

**Comment by RyanZim** [comment]
@jskungfu, I'm giving you 7 more days to respond or I will close this.

**Comment by mde** [comment]
I think what this person is asking for might be HTML validation, which is way beyond the purview of what EJS should do.

**Comment by RyanZim** [comment]
No Response; Closing.
