### ISSUE TITLE
using "include" keyword un-delimited causes odd error

### ISSUE THREAD

**Issue by kylemac** [mde/ejs#81]
okay, this is a weird issue so bare with me. i'm attempting to use EJS to output [jade](http://jade-lang.com/) templates. when trying to do so, i uncovered a very peculiar bug that has something to do with how EJS includes are being interpreted. 

i've created an example to demonstrate the weirdness - http://runnable.com/VSwsiwZIeMpRgeDw

#### the basic info
trying to render template that includes the words `include` un-delimited with <% %> or any EJS template tags causes an error UNLESS there is other content on the preceding line. 

#### some details
it looks like including the `include` keyword triggers EJS to evaluate it like it's a regular <% include %> even when it's not within the template tags. this issue goes away if you put some content on the preceding line. this indicates to me that there is something wrong with how you are scanning for includes but i truly don't know enough about the internals of EJS to diagnose it. 

Please let me know if I can clarify anything beyond the example link i've provided - http://runnable.com/VSwsiwZIeMpRgeDw

**Comment by RyanZim** [comment]
This weird behavior was fixed in v2.3.3.
It works fine when you upgrade.
My apologies that this wasn't answered sooner.

**Comment by kylemac** [comment]
thanks for the update @RyanZim
