### ISSUE TITLE
WIP: benchmark test cases

### ISSUE THREAD

**Issue by JacksonTian** [mde/ejs#82]
Today, I find `ejs` module on NPM is not related to tj's ejs project. The source code was changed a lot, some features were added. As a old user of ejs, hope to see any more benchmark test cases to make sure the performance is stable.

**Comment by TimothyGu** [comment]
See https://gist.github.com/TimothyGu/2c43a88789d5302d81f9#file-result-md

"v2 orig" is this module.

"v2 new" is my fork: https://github.com/TimothyGu/ejs-tj
