### ISSUE TITLE
Optimize compiled size

### ISSUE THREAD

**Issue by dominykas** [mde/ejs#83]
`ejs@2.x` produces significantly larger compiled functions than `ejs@1.x`. Here's a sample from our system (we have 3 browserified browser bundles, I'm only including the size of templates in the table):

| raw.ejs | v1 | v2 | v2/v1 | v1.min | v2.min | v2/v1 | v1.gz | v2.gz | v2/v1 |
| --: | --: | --: | --: | --: | --: | --: | --: | --: | --: |
| 6394 | 8167 | 11606 | +42% | 7525 | 9960 | +32% | 1876 | 2059 | +10% |
| 13914 | 20626 | 27833 | +35% | 18495 | 24874 | +34% | 3074 | 3359 | +9% |
| 6851 | 9053 | 11708 | +29% | 8780 | 10967 | +25% | 1643 | 1794 | +9% |

Whether the size difference matters is another day's discussion - it all depends on project size and many other factors. Also, whereas only `gz` matters for download, `min` does matter for parsing.

The primary reason for the increase, as far as I can tell, is that `v1` used to `buf.push(chunk, chunk, chunk)` and v2 does `buf.push(chunk); buf.push(chunk); buf.push(chunk)`. I might be wrong, but I think this is to improve the sourcemaps support, isn't it?

Some ideas for improvement:
- move `var __output` _inside_ the `with` and wrap with an IIFE, so that `__output` is _really_ known to be a local variable and so minifiers can rename it. In our case - minified is ~16-19%, gzip ~5-6% larger than v1
- under minified version, 5 bytes per chunk can be saved by having a `__outputPush = __output.push.bind(__output)` local function (might actually result in larger size, if there's fewer than ? chunks, also doesn't work in older browsers). In our case - minified is ~10-12%, gzip ~5% larger than v1. 
- I never figured it out... but is there a way to somehow share the `escape` function? Maybe do some magic with a compile time param for "require this module for escape function" (for browserify case)? Potentially only do the magic via [`ejsify`](https://www.npmjs.com/package/ejsify)?

I can probably PR this, if there are no objections?

**Comment by TimothyGu** [comment]
> move `var __output` _inside_ the `with` and wrap with an IIFE, so that `__output` is _really_ known to be a local variable and so minifiers can rename it. In our case - minified is ~16-19%, gzip ~5-6% larger than v1

Good idea. I'll see if I can do this on the weekend, but PRs welcome.

> under minified version, 5 bytes per chunk can be saved by having a __outputPush = __output.push.bind(__output) local function (might actually result in larger size, if there's fewer than ? chunks, also doesn't work in older browsers). In our case - minified is ~10-12%, gzip ~5% larger than v1.

```js
function a () {
var __output = []
var __outputPush = __output.push.bind(__output)

__outputPush('a')
/*arbitrary code*/
__outputPush('b', 'c')
/*arbitrary code*/
__outputPush('c')
/*arbitrary code*/
__outputPush('d')
}
```

71 characters

```js
function a () {
var __output = []

__output.push('a')
/*arbitrary code*/
__output.push('b', 'c')
/*arbitrary code*/
__output.push('c')
/*arbitrary code*/
__output.push('d')
}
```

74 characters

So 3 code sections should be enough to make it smaller.

> I never figured it out... but is there a way to somehow share the `escape` function?

NO, although a PR is welcome for an option that lifts the function out.

**Comment by dominykas** [comment]
First (and most beneficial) step done - waiting for comments.

For the `push` I assume it's OK to use `bind` then and tell the users of the lib to use a `bind` shim or something? Any ideas on a way to detect if the `push` extraction is really worth it, or can we just assume that most templates have 4+ code sections, so it's an overall win? Come to think of it... if a template has at least one var usage, then it has at least 3 sections (unless the var comes first/last)? And if there are no vars - why even use ejs...

As for `escape` - will revisit next week earliest, unless someone gets there faster :)

**Comment by TimothyGu** [comment]
> First (and most impactful) step done - waiting for comments.

Merged.

> Any ideas on a way to detect if the `push` extraction is really worth it, or can we just assume that most templates have 4+ code sections, so it's an overall win?

I think it's worth it. Nobody really cares about 16 bytes more minified anyway.

> As for `escape` - will revisit next week earliest, unless someone gets there faster :)

Cool :smiley:

**Comment by RyanZim** [comment]
@dominykas, are you still planning to revisit this?

**Comment by dominykas** [comment]
@RyanZim this was merged, but then pulled back due to a bug (lost context), which now has a PR pending again: https://github.com/mde/ejs/pull/101

**Comment by dominykas** [comment]
Oh, I planned to revisit sharing the `escape`... Probably not anymore - to little time right now.

**Comment by RyanZim** [comment]
OK, thanks.
Will try to get the ball rolling on #101.

**Comment by mde** [comment]
I've revisited `escape` a bit here: aa1771e Are we going to pick this ball back up again?

**Comment by dominykas** [comment]
stalebot-ing myself.
