### ISSUE TITLE
new line slurp and filter not available? 

### ISSUE THREAD

**Issue by s-a** [mde/ejs#86]
try to use some build in features at https://github.com/s-a/deep-js/blob/master/template/markdown.MD 
 - ```-%>``` has no effect.
And filters are not available?

**Comment by TimothyGu** [comment]
Filters were removed in ejs v2. What is your expected and current outputs of the `-%>` tag?

**Comment by s-a** [comment]
i expected an output without line breaks but he ouput includes linebreaks.

**Comment by mde** [comment]
We have tests that verify this feature: https://github.com/mde/ejs/blob/master/test/ejs.js#L480

Also can verify in the Node REPL:

```javascript
var ejs = require('./lib/ejs');
> ejs.render('<%= "foo" %>\nbar');
'foo\nbar'
> ejs.render('<%= "foo" -%>\nbar');
'foobar'
```
Trim-mode only trims the trailing line-break after the tag.
