### ISSUE TITLE
Supporting custom {{ name }} delimiters without =

### ISSUE THREAD

**Issue by metakermit** [mde/ejs#88]
Would it be possible to support overriding the whole first part `<%=` of the template tag with a custom delimiter like `{{`? This would enable the `{{ name }}` syntax which is used very widely - e.g. in Django, Jinja2, Ansible.

This is something that was possible in the [lodash template engine](https://lodash.com/docs#template) using the interpolate option.

```
// using custom template delimiters
_.templateSettings.interpolate = /{{([\s\S]+?)}}/g;
var compiled = _.template('hello {{ user }}!');
compiled({ 'user': 'mustache' });
// → 'hello mustache!'
```

Now that ejs is used in [Yeoman](https://github.com/yeoman/yeoman.io/commit/76d1c03c66a16cda73049bc7eca1afebd2fccd9f), I find it difficult to properly "massage" some of my files.

**Comment by rla** [comment]
This is partially related to https://github.com/mde/ejs/issues/55

**Comment by RyanZim** [comment]
@metakermit: total custom delimiters were turned down in #55.
However, `open` and `close` options for specifying custom tag markers instead of `<` and `>` were suggested in #115. This would allow for tags like `{{=` for instead of `<%=`. You're welcome to submit a PR for that issue.
