### ISSUE TITLE
mocha-phantomjs v1.9.8 __.ouput is not defined

### ISSUE THREAD

**Issue by KaoruDev** [mde/ejs#95]
**Error** when running `mocha-phantomjs test.html`

```
TypeError: check-auth-iframe-template.ejs:1
 >> 1| <iframe src="<%= sso_login_source %>" frameborder="0" style="display: none !important;"></iframe>
    2|

'undefined' is not a function (evaluating '__output.push.bind(__output)')
```

I am using webpack to bundle all the files together but i don't suspect that is the issue. I suspect this line is throwing something off, but i'm not 100%

https://github.com/mde/ejs/compare/17ce07dc23f1aa3b8667d2c76017ed422fceb301...a4cc57a15b891288a29bcf69a22737037cc43590#diff-0d9afaa7ce3db4d8cac4ca2abf3584baR424

I reverted to 2.8.1 and the issue went away.

**Comment by mde** [comment]
Could you provide a little more context, or perhaps a minimal failing test? What is in the test.html?

**Comment by KaoruDev** [comment]
https://github.com/KaoruDev/mde-ejs-2.8.2-error

How about a repo with the issue? =)

`npm install`

`gulp` to create `spec-bundle.js`

`phantomjs-mocha test.html` to see error

**Comment by mde** [comment]
![carl-sagan-youre-awesome](https://cloud.githubusercontent.com/assets/757/8423288/c3481606-1e9b-11e5-8464-a87be8bd4080.gif)

**Comment by mde** [comment]
I can't repro this error with the code in the repo. Here are the steps I followed (I already had Phantom installed at `/usr/local/bin/phantomjs`):

```bash
git clone git@github.com:KaoruDev/mde-ejs-2.8.2-error.git
cd mde-ejs-2.8.2-error
npm install
sudo npm install -g gulp
sudo npm install -g mocha-phantomjs
gulp
mocha-phantomjs test.html
```
I get this (no errors):
```bash
  0 passing (0ms)
```

**Comment by mde** [comment]
Oh, now I remember that Phantom 1.x is based on an incredibly old version of WebKit which is missing Function#bind. I'm not sure why I can't repro the error -- I have Phantom 1.9.8.

```
phantomjs> var foo = function () {};
undefined
phantomjs> typeof foo;
"function"
phantomjs> foo.toString();
"function () {}"
phantomjs> typeof foo.call;
"function"
phantomjs> typeof foo.bind
"undefined"
```

Phantom 2 is out -- not sure how long EJS should support really old runtimes.

**Comment by KaoruDev** [comment]
yeah i thought it was `bind` that was causing the issue so i patched it in test.html 

https://github.com/KaoruDev/mde-ejs-2.8.2-error/blob/master/test.html#L23-L44

But i still get that error. I can't remember why i don't use phantom 2. Let me try upgrading to phantom 2 and see if that will fix this

**Comment by TimothyGu** [comment]
@KaoruDev ping. Any updates?

**Comment by KaoruDev** [comment]
@TimothyGu thanks for the ping, thing got busy and luckily you pinged me at the right time.

I upgraded to phantomjs 2.0 and the issue went away =)
