### ISSUE TITLE
Templating Jade

### ISSUE THREAD

**Issue by adammockor** [mde/ejs#98]
Hello,

Yeoman guys recently switch to EJS templates. This creates weird issue for me:

I'm using yo genarator (0.20.1) to prepare Jade templates and I got line like this:
```
<% if (condition) { %> include ../mixins/_mixin <% } %>
```
And it gives me this error:
```
Error: ENOENT, no such file or directory 'generator-lb/app/templates/views/mixins/_mixin.ejs'
```
If I put there: `_mixin.jade`, generator will inline the mixin which is also not desired.

**Comment by metzuda** [comment]
Not familiar with Yeoman , but why not ```<% if (condition) {  include ../mixins/_mixin } %>```

By having the closing tag there you're stopping the script tag in it's tracks.

**Comment by TimothyGu** [comment]
@metzuda we don't want the `include` to be in the `if` because 1. it is not a valid JavaScript statement, and 2. @adammockor doesn't want to inline the `include` call.

**Comment by adammockor** [comment]
Exactly as @TimothyGu said. 
This:
```
<% if (true) { %> include ../mixins/_mixin <% } %>
```
should result to (after compilation):
```
include ../mixins/_mixin
```

**Comment by SBoudrias** [comment]
Looks like we can close that issue :)

**Comment by TimothyGu** [comment]
@SBoudrias thanks!

**Comment by adammockor** [comment]
Nice!
